/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "lldpStatistics.h"
#include <lldp/proto_lldp.h>


typedef struct
{
	u_long lldpStatsRemTablesLastChangeTime;		
    u_long lldpStatsRemTablesInserts;
    u_long lldpStatsRemTablesDeletes;
    u_long lldpStatsRemTablesDrops;
    u_long lldpStatsRemTablesAgeouts;
}lldpStatData_t;

static lldpStatData_t s_lldpStatData;

/*    
	lldpStatDataLoad   
	-- Load group data from somewhere
*/
static int lldpStatDataLoad(lldpStatData_t *data)
{
    int ret;
    lldp_statistic_t lldp_statistic;

    memset(&lldp_statistic, 0, sizeof(lldp_statistic));

    ret = sal_lldp_statistic_get(&lldp_statistic);
    if (ret != 0)
    {
        return 0;
    }          

    data->lldpStatsRemTablesLastChangeTime = 0;
    data->lldpStatsRemTablesInserts = lldp_statistic.insertion;
    data->lldpStatsRemTablesDeletes = lldp_statistic.deletion;
    data->lldpStatsRemTablesDrops = lldp_statistic.drop;
    data->lldpStatsRemTablesAgeouts = lldp_statistic.age_out;
    
	/* XXX */
	return 1;
}





/* ## ENDIF ## */


/* ## Handle functions ## */

static int handle_lldpStatsRemTablesLastChangeTime(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpStatDataLoad(&s_lldpStatData);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_integer(requests->requestvb, ASN_TIMETICKS, s_lldpStatData.lldpStatsRemTablesLastChangeTime);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static int handle_lldpStatsRemTablesInserts(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpStatDataLoad(&s_lldpStatData);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_integer(requests->requestvb, ASN_TIMETICKS, s_lldpStatData.lldpStatsRemTablesInserts);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static int handle_lldpStatsRemTablesDeletes(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpStatDataLoad(&s_lldpStatData);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_integer(requests->requestvb, ASN_TIMETICKS, s_lldpStatData.lldpStatsRemTablesDeletes);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static int handle_lldpStatsRemTablesDrops(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpStatDataLoad(&s_lldpStatData);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_integer(requests->requestvb, ASN_TIMETICKS, s_lldpStatData.lldpStatsRemTablesDrops);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

static int handle_lldpStatsRemTablesAgeouts(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpStatDataLoad(&s_lldpStatData);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_integer(requests->requestvb, ASN_TIMETICKS, s_lldpStatData.lldpStatsRemTablesAgeouts);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


/*
 * Our initialization routine, called automatically by the agent 
 * (Note that the function name must match init_FILENAME()) 
 */
void init_lldpStatistics(void)
{
    const oid lldpStatsRemTablesLastChangeTime_oid[] = {1,0,8802,1,1,2,1,2,1};
    const oid lldpStatsRemTablesInserts_oid[] = {1,0,8802,1,1,2,1,2,2};
    const oid lldpStatsRemTablesDeletes_oid[] = {1,0,8802,1,1,2,1,2,3};
    const oid lldpStatsRemTablesDrops_oid[] = {1,0,8802,1,1,2,1,2,4};
    const oid lldpStatsRemTablesAgeouts_oid[] = {1,0,8802,1,1,2,1,2,5};

    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpStatsRemTablesLastChangeTime", 
										handle_lldpStatsRemTablesLastChangeTime,
										lldpStatsRemTablesLastChangeTime_oid, 
										OID_LENGTH(lldpStatsRemTablesLastChangeTime_oid),
										HANDLER_CAN_RONLY
										)
							);


    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpStatsRemTablesInserts", 
										handle_lldpStatsRemTablesInserts,
										lldpStatsRemTablesInserts_oid, 
										OID_LENGTH(lldpStatsRemTablesInserts_oid),
										HANDLER_CAN_RONLY
										)
							);


    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpStatsRemTablesDeletes", 
										handle_lldpStatsRemTablesDeletes,
										lldpStatsRemTablesDeletes_oid, 
										OID_LENGTH(lldpStatsRemTablesDeletes_oid),
										HANDLER_CAN_RONLY
										)
							);

    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpStatsRemTablesDrops", 
										handle_lldpStatsRemTablesDrops,
										lldpStatsRemTablesDrops_oid, 
										OID_LENGTH(lldpStatsRemTablesDrops_oid),
										HANDLER_CAN_RONLY
										)
							);

    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpStatsRemTablesAgeouts", 
										handle_lldpStatsRemTablesAgeouts,
										lldpStatsRemTablesAgeouts_oid, 
										OID_LENGTH(lldpStatsRemTablesAgeouts_oid),
										HANDLER_CAN_RONLY
										)
							);    
  
   /* Trying to load group data as default values */
   lldpStatDataLoad(&s_lldpStatData);
   
   //TODO: register callback function for data update
}

