/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef LLDPREMTABLE_H
#define LLDPREMTABLE_H

/* function declarations */
void init_lldpRemTable(void);
void initialize_table_lldpRemTable(void);
Netsnmp_Node_Handler lldpRemTable_handler;
Netsnmp_First_Data_Point  lldpRemTable_get_first_data_point;
Netsnmp_Next_Data_Point   lldpRemTable_get_next_data_point;

/* column number definitions for table lldpRemTable */
       #define COLUMN_LLDPREMTIMEMARK		1
       #define COLUMN_LLDPREMLOCALPORTNUM		2
       #define COLUMN_LLDPREMINDEX		3
       #define COLUMN_LLDPREMCHASSISIDSUBTYPE		4
       #define COLUMN_LLDPREMCHASSISID		5
       #define COLUMN_LLDPREMPORTIDSUBTYPE		6
       #define COLUMN_LLDPREMPORTID		7
       #define COLUMN_LLDPREMPORTDESC		8
       #define COLUMN_LLDPREMSYSNAME		9
       #define COLUMN_LLDPREMSYSDESC		10
       #define COLUMN_LLDPREMSYSCAPSUPPORTED		11
       #define COLUMN_LLDPREMSYSCAPENABLED		12
#endif /* LLDPREMTABLE_H */
