/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef __LLDPPORTCONFIGTABLE_H__
#define __LLDPPORTCONFIGTABLE_H__

/* function declarations */
void init_lldpPortConfigTable(void);

#endif /* LLDPPORTCONFIGTABLE_H */
