/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "lldpStatsTxPortTable.h"
#include <lldp/proto_lldp.h>

/* function declarations for table lldpStatsTxPortTable */
static void initialize_table_lldpStatsTxPortTable(void);

static Netsnmp_Node_Handler lldpStatsTxPortTable_handler;
static Netsnmp_First_Data_Point  lldpStatsTxPortTable_get_first_data_point;
static Netsnmp_Next_Data_Point   lldpStatsTxPortTable_get_next_data_point;


/* column number definitions for table lldpStatsTxPortTable */
#define COLUMN_LLDPSTATSTXIFINDEX		1
#define COLUMN_LLDPSTATSTXPORTFRAMESTOTAL		2

struct lldpStatsTxPortTable_entry
{
    /* Index values */
    long lldpStatsTxIfIndex;
	/* Column values */
	u_long lldpStatsTxPortFramesTotal;
	 
	 /* Illustrate using a simple linked list */ 
	 int   valid; 
	 struct lldpStatsTxPortTable_entry *next;
};

static struct lldpStatsTxPortTable_entry  *lldpStatsTxPortTable_head = NULL;

static void tableFreeAll(struct lldpStatsTxPortTable_entry *head)
{
    struct lldpStatsTxPortTable_entry *this, *that, *tmp;      

    for ( this = head; this; this=that ) 
    {                  
        that = this->next;
        SNMP_FREE( this );  /* XXX - release any other internal resources */
  
    } 
}

/*    
	tableDataLoad   
	-- Load table data from somewhere
*/
static int tableDataLoad(struct lldpStatsTxPortTable_entry *entry)
{
    int ret, num, i;
    struct lldpStatsTxPortTable_entry *new = NULL;
    struct lldpStatsTxPortTable_entry *tmpHead = NULL;   
    struct lldpStatsTxPortTable_entry *oldHead = NULL; 
    lldp_statistic_t lldp_statistic;

    memset(&lldp_statistic, 0, sizeof(lldp_statistic));

    ret+= sal_lldp_statistic_get(&lldp_statistic);
    if (ret != 0)
    {
        return 0;
    }          

    for (i = 0; i < SYS_USER_PORT_NUM(0); i ++)
    {
        new = SNMP_MALLOC_TYPEDEF(struct lldpStatsTxPortTable_entry );
        if (!new)
        {
            goto safe_exit;
        }            
    
        memset(new, 0, sizeof(struct lldpStatsTxPortTable_entry ));

        new->lldpStatsTxIfIndex = LP2UP(i);
        new->lldpStatsTxPortFramesTotal = lldp_statistic.port_statistics[i].tx_frame;

        new->next = tmpHead ;
        tmpHead  = new;              
    }

    oldHead = lldpStatsTxPortTable_head;
    lldpStatsTxPortTable_head = tmpHead;      

    tableFreeAll(oldHead);  

safe_exit:
    
    /* XXX */
    return 1;

}

static int tableCacheLoad( netsnmp_cache *cache, void *vmagic ) 
{
    tableDataLoad(NULL);		
    return 0;  /* OK */
}

static void tableCacheFree( netsnmp_cache *cache, void *vmagic ) 
{
    //do nothing
}

/** Initializes the lldpStatsTxPortTable module */
void init_lldpStatsTxPortTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
    initialize_table_lldpStatsTxPortTable();
}


/** Initialize the lldpStatsTxPortTable table by defining its contents and how it's structured */
static void initialize_table_lldpStatsTxPortTable(void)
{
    const oid lldpStatsTxPortTable_oid[] = {1,0,8802,1,1,2,1,2,6};
    const size_t lldpStatsTxPortTable_oid_len   = OID_LENGTH(lldpStatsTxPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("lldpStatsTxPortTable:init", "initializing table lldpStatsTxPortTable\n"));

    reg = netsnmp_create_handler_registration(
											  "lldpStatsTxPortTable",     
											  lldpStatsTxPortTable_handler,
											  lldpStatsTxPortTable_oid, 
											  lldpStatsTxPortTable_oid_len,
											  HANDLER_CAN_RONLY
											  );

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	
    netsnmp_table_helper_add_indexes(
									table_info,
									ASN_INTEGER,  /* index: lldpStatsTxIfIndex */
									0
									);
						   
    table_info->min_column = COLUMN_LLDPSTATSTXIFINDEX;
    table_info->max_column = COLUMN_LLDPSTATSTXPORTFRAMESTOTAL;
    
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	
    iinfo->get_first_data_point = lldpStatsTxPortTable_get_first_data_point;
    iinfo->get_next_data_point  = lldpStatsTxPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator(reg, iinfo);
	
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(5,
                                  tableCacheLoad,
								  tableCacheFree,
								  lldpStatsTxPortTable_oid,
								  lldpStatsTxPortTable_oid_len),
								  TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
	tableDataLoad(NULL);
}


/* create a new row in the (unsorted) table */
static struct lldpStatsTxPortTable_entry *lldpStatsTxPortTable_createEntry(
											long  lldpStatsTxIfIndex) 
{

	struct lldpStatsTxPortTable_entry *entry;
	
    entry = SNMP_MALLOC_TYPEDEF(struct lldpStatsTxPortTable_entry);
    if (!entry)
    {
        return NULL;
    }
	
    entry->lldpStatsTxIfIndex = lldpStatsTxIfIndex;
    entry->next = lldpStatsTxPortTable_head;
    lldpStatsTxPortTable_head = entry;
	
    return entry;
}


/* remove a row from the table */
static void lldpStatsTxPortTable_removeEntry(struct lldpStatsTxPortTable_entry *entry) 
{
    struct lldpStatsTxPortTable_entry *ptr, *prev;

    if (!entry)
    {
        return;    /* Nothing to remove */
    }
    
	for (ptr = lldpStatsTxPortTable_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next) 
	{
        if (ptr == entry)
    	{
            break;
		}
    }
	
    if (!ptr)
    {
        return;    /* Can't find it */
    }
    
	if (prev == NULL)
	{
        lldpStatsTxPortTable_head = ptr->next;
    }
	else
	{
        prev->next = ptr->next;
	}

    SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
static netsnmp_variable_list *lldpStatsTxPortTable_get_first_data_point(
									void **my_loop_context,
									void **my_data_context,
									netsnmp_variable_list *put_index_data,
									netsnmp_iterator_info *mydata
									)
{
    *my_loop_context = lldpStatsTxPortTable_head;
	
    return lldpStatsTxPortTable_get_next_data_point(
									 my_loop_context, 
									 my_data_context,
                                     put_index_data,
                                     mydata
									 );
}


static netsnmp_variable_list *lldpStatsTxPortTable_get_next_data_point(
									void **my_loop_context,
									void **my_data_context,
									netsnmp_variable_list *put_index_data,
									netsnmp_iterator_info *mydata
									)
{
    struct lldpStatsTxPortTable_entry *entry = (struct lldpStatsTxPortTable_entry *)*my_loop_context;
	
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
	{
        snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->lldpStatsTxIfIndex);
        idx = idx->next_variable;
	  	
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
		
        return put_index_data;
    }
	else 
	{
        return NULL;
    }
}


/** handles requests for the lldpStatsTxPortTable table */
static int lldpStatsTxPortTable_handler(
					netsnmp_mib_handler           *handler,
					netsnmp_handler_registration  *reginfo,
					netsnmp_agent_request_info    *reqinfo,
					netsnmp_request_info          *requests
					) 
{

    netsnmp_request_info       	*request;
    netsnmp_table_request_info 	*table_info;
    struct lldpStatsTxPortTable_entry          *table_entry;
	
	int ret;

    DEBUGMSGTL(("lldpStatsTxPortTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) 
	{
		/*
		 * Read-support (also covers GetNext requests)
		 */
		case MODE_GET:
			{
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct lldpStatsTxPortTable_entry *)netsnmp_extract_iterator_context(request);
                                    if(!table_entry)
                                    {
                                        continue;
                                    }  
                                                            
					table_info  = netsnmp_extract_table_info(request);
			
					switch (table_info->colnum)
					{
						case COLUMN_LLDPSTATSTXIFINDEX:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER, table_entry->lldpStatsTxIfIndex);
							}
							break;
						case COLUMN_LLDPSTATSTXPORTFRAMESTOTAL:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsTxPortFramesTotal);
							}
							break;
							
							
						default:
							{
								netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
							}
							break;
					}
				}
			}
			break;

	}
	
    return SNMP_ERR_NOERROR;
}
