/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "lldpRemTable.h"
#include <lldp/proto_lldp.h>

    /* Typical data structure for a row entry */
struct lldpRemTable_entry {
    /* Index values */
    u_long lldpRemTimeMark;
    long lldpRemLocalPortNum;
    long lldpRemIndex;

    /* Column values */
    long lldpRemChassisIdSubtype;
    char lldpRemChassisId[256];
    size_t lldpRemChassisId_len;
    long lldpRemPortIdSubtype;
    char lldpRemPortId[256];
    size_t lldpRemPortId_len;
    char lldpRemPortDesc[256];
    size_t lldpRemPortDesc_len;
    char lldpRemSysName[256];
    size_t lldpRemSysName_len;
    char lldpRemSysDesc[256];
    size_t lldpRemSysDesc_len;
    char lldpRemSysCapSupported[2];
    size_t lldpRemSysCapSupported_len;
    char lldpRemSysCapEnabled[2];
    size_t lldpRemSysCapEnabled_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct lldpRemTable_entry *next;
};

struct lldpRemTable_entry  *lldpRemTable_head = NULL;

static char highLowSwap(char v)
{
    char tmp;
    
    tmp =
    ((v & 0x01)<<7)
    |((v & 0x02)<<5)
    |((v & 0x04)<<3)
    |((v & 0x08)<<1)
    |((v & 0x10)>>1)
    |((v & 0x20)>>3)
    |((v & 0x40)>>5)
    |((v & 0x80)>>7);    

    return tmp;
}

static void tableFreeAll(struct lldpRemTable_entry *head)
{
    struct lldpRemTable_entry *this, *that, *tmp;      

    for ( this = head; this; this=that ) 
    {                  
        that = this->next;
        SNMP_FREE( this );  /* XXX - release any other internal resources */
  
    } 
}

/*    
	tableDataLoad   
	-- Load table data from somewhere
*/
static int tableDataLoad(struct lldpRemTable_entry *entry)
{    
    int ret, num, i, j;
    display_entry_t lldp_entry;
    struct lldpRemTable_entry *new = NULL;
    struct lldpRemTable_entry *tmpHead = NULL;   
    struct lldpRemTable_entry *oldHead = NULL; 

    for (i = 0; i < SYS_USER_PORT_NUM(0); i ++)
    {
        for (j = 0; j < LLDP_MAX_ENTRY_PER_PORT; j ++)
        {
            memset(&lldp_entry, 0, sizeof( display_entry_t ));
            
            ret = sal_lldp_portRemoteEntryInfo_valid_get(i, j, &lldp_entry);
            if(0 != ret)
            {
                continue;
            }

            new = SNMP_MALLOC_TYPEDEF(struct lldpRemTable_entry );
            if (!new)
            {
                goto SAFE_EXIT;
            }            
            memset(new, 0, sizeof(struct lldpRemTable_entry ));
           
            new->lldpRemTimeMark = 1;
            new->lldpRemLocalPortNum = LP2UP(lldp_entry.logicPort);
            new->lldpRemIndex = j;

            new->lldpRemChassisIdSubtype = lldp_entry.chasis_id.iSubtype;
            if (new->lldpRemChassisIdSubtype == CHASSIS_ID_MAC_ADDRESS)
            {
                memcpy(new->lldpRemChassisId, lldp_entry.chasis_id.iId, 6);
                new->lldpRemChassisId_len = 6;
            }
            else
            {
                if ((strlen(lldp_entry.chasis_id.id) > 0) && (strlen(lldp_entry.chasis_id.id) < 256))
                {
                    strcpy(new->lldpRemChassisId, lldp_entry.chasis_id.id);
                    new->lldpRemChassisId_len = strlen(new->lldpRemChassisId);  
                }
            }

            new->lldpRemPortIdSubtype = lldp_entry.port_id.iSubtype;
            if (new->lldpRemPortIdSubtype == PORT_ID_MAC_ADDRESS)
            {
                memcpy(new->lldpRemPortId, lldp_entry.port_id.id, 6);
                new->lldpRemPortId_len = 6;
            }
            else
            {
                if ((strlen(lldp_entry.port_id.id) > 0) && (strlen(lldp_entry.port_id.id) < 256))
                {
                    strcpy(new->lldpRemPortId, lldp_entry.port_id.id);
                    new->lldpRemPortId_len = strlen(new->lldpRemPortId);
                }
            }

            if ((strlen(lldp_entry.port_description) > 0) && (strlen(lldp_entry.port_description) < 256))
            {
                strcpy(new->lldpRemPortDesc, lldp_entry.port_description);
                new->lldpRemPortDesc_len = strlen(new->lldpRemPortDesc);
            }
            if ((strlen(lldp_entry.system_name) > 0) && (strlen(lldp_entry.system_name) < 32))
            {
                strcpy(new->lldpRemSysName, lldp_entry.system_name);
                new->lldpRemSysName_len = strlen(new->lldpRemSysName);
            }
            
            if ((strlen(lldp_entry.system_description) > 0) && (strlen(lldp_entry.system_description) < 256))
            {
                strcpy(new->lldpRemSysDesc, lldp_entry.system_description);
                new->lldpRemSysDesc_len = strlen(new->lldpRemSysDesc);
            }
            new->lldpRemSysCapEnabled[0] = (char)(lldp_entry.system_capabilities.iEnable & 0xFF);
            new->lldpRemSysCapEnabled[1] = (char)(lldp_entry.system_capabilities.iEnable >> 8 & 0xFF);
            new->lldpRemSysCapEnabled_len = 2;
            
            new->lldpRemSysCapSupported[0] = (char)(lldp_entry.system_capabilities.iSupport & 0xFF);
            new->lldpRemSysCapSupported[1] = (char)(lldp_entry.system_capabilities.iSupport >> 8 & 0xFF);
            new->lldpRemSysCapSupported_len = 2;

            new->next = tmpHead ;
            tmpHead  = new;
        }
    }

    oldHead = lldpRemTable_head;
    lldpRemTable_head = tmpHead;      
    
    tableFreeAll(oldHead);  

SAFE_EXIT:
    /* XXX */
    return 1;
}

static int tableCacheLoad( netsnmp_cache *cache, void *vmagic ) 
{
    tableDataLoad(NULL);		
    return 0;  /* OK */
}

static void tableCacheFree( netsnmp_cache *cache, void *vmagic ) 
{
    //do nothing
}

/** Initializes the lldpRemTable module */
void
init_lldpRemTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    //snmp_log(LOG_DEBUG, "init_lldpRemTable init \n");
    initialize_table_lldpRemTable();
}

  //# Determine the first/last column names

/** Initialize the lldpRemTable table by defining its contents and how it's structured */
void
initialize_table_lldpRemTable(void)
{
    static oid lldpRemTable_oid[] = {1,0,8802,1,1,2,1,4,1};
    size_t lldpRemTable_oid_len   = OID_LENGTH(lldpRemTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "lldpRemTable",     lldpRemTable_handler,
              lldpRemTable_oid, lldpRemTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_TIMETICKS,  /* index: lldpRemTimeMark */
                           ASN_INTEGER,  /* index: lldpRemLocalPortNum */
                           ASN_INTEGER,  /* index: lldpRemIndex */
                           0);
    table_info->min_column = COLUMN_LLDPREMLOCALPORTNUM;
    table_info->max_column = COLUMN_LLDPREMSYSCAPENABLED;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = lldpRemTable_get_first_data_point;
    iinfo->get_next_data_point  = lldpRemTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(5,
                                  tableCacheLoad,
								  tableCacheFree,
								  lldpRemTable_oid,
								  lldpRemTable_oid_len),
								  TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
	tableDataLoad(NULL);
}

/* create a new row in the (unsorted) table */
struct lldpRemTable_entry *
lldpRemTable_createEntry(
                 u_long  lldpRemTimeMark,
                 long  lldpRemLocalPortNum,
                 long  lldpRemIndex
                ) {
    struct lldpRemTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct lldpRemTable_entry);
    if (!entry)
        return NULL;

    entry->lldpRemTimeMark = lldpRemTimeMark;
    entry->lldpRemLocalPortNum = lldpRemLocalPortNum;
    entry->lldpRemIndex = lldpRemIndex;
    entry->next = lldpRemTable_head;
    lldpRemTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
lldpRemTable_removeEntry( struct lldpRemTable_entry *entry ) {
    struct lldpRemTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = lldpRemTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        lldpRemTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
lldpRemTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = lldpRemTable_head;
    return lldpRemTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
lldpRemTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct lldpRemTable_entry *entry = (struct lldpRemTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_TIMETICKS, entry->lldpRemTimeMark );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->lldpRemLocalPortNum );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->lldpRemIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the lldpRemTable table */
int
lldpRemTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct lldpRemTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct lldpRemTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            //snmp_log(LOG_DEBUG, "table_info->colnum: %d\n", table_info->colnum);
            switch (table_info->colnum) {
            case COLUMN_LLDPREMLOCALPORTNUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lldpRemLocalPortNum);
                break;
            case COLUMN_LLDPREMINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lldpRemIndex);
                break;
            case COLUMN_LLDPREMCHASSISIDSUBTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lldpRemChassisIdSubtype);
                break;
            case COLUMN_LLDPREMCHASSISID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemChassisId,
                                          table_entry->lldpRemChassisId_len);
                break;
            case COLUMN_LLDPREMPORTIDSUBTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lldpRemPortIdSubtype);
                break;
            case COLUMN_LLDPREMPORTID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemPortId,
                                          table_entry->lldpRemPortId_len);
                break;
            case COLUMN_LLDPREMPORTDESC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemPortDesc,
                                          table_entry->lldpRemPortDesc_len);
                break;
            case COLUMN_LLDPREMSYSNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemSysName,
                                          table_entry->lldpRemSysName_len);
                break;
            case COLUMN_LLDPREMSYSDESC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemSysDesc,
                                          table_entry->lldpRemSysDesc_len);
                break;
            case COLUMN_LLDPREMSYSCAPSUPPORTED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemSysCapSupported,
                                          table_entry->lldpRemSysCapSupported_len);
                break;
            case COLUMN_LLDPREMSYSCAPENABLED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpRemSysCapEnabled,
                                          table_entry->lldpRemSysCapEnabled_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
