/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "lldpLocPortTable.h"
#include <lldp/proto_lldp.h>


/* Typical data structure for a row entry */
struct lldpLocPortTable_entry {
    /* Index values */
    long lldpLocPortNum;

    /* Column values */
    long lldpLocPortIdSubtype;
    char lldpLocPortId[256];
    size_t lldpLocPortId_len;
    char lldpLocPortDesc[256];
    size_t lldpLocPortDesc_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct lldpLocPortTable_entry *next;
};

struct lldpLocPortTable_entry  *lldpLocPortTable_head = NULL;

static void tableFreeAll(struct lldpLocPortTable_entry *head)
{
    struct lldpLocPortTable_entry *this, *that, *tmp;      

    for ( this = head; this; this=that ) 
    {                  
        that = this->next;
        SNMP_FREE( this );  /* XXX - release any other internal resources */
  
    } 
}

/*    
	tableDataLoad   
	-- Load table data from somewhere
*/
static int tableDataLoad(struct lldpLocPortTable_entry *entry)
{    
    int ret, num, i;
    display_entry_t lldpEntry;
    struct lldpLocPortTable_entry *new = NULL;
    struct lldpLocPortTable_entry *tmpHead = NULL;   
    struct lldpLocPortTable_entry *oldHead = NULL; 
        
    for (i = 0; i < SYS_USER_PORT_NUM(0); i ++)
    {
        ret = sal_lldp_portLocalEntryInfo_get(i, &lldpEntry);
        if(0 != ret)
        {
            continue;
        }

        new = SNMP_MALLOC_TYPEDEF(struct lldpLocPortTable_entry );
        if (!new)
        {
            goto safe_exit;
        }
        memset(new, 0, sizeof(struct lldpLocPortTable_entry ));
        
        //snmp_log(LOG_DEBUG, "port: %d\n", i);
        //snmp_log(LOG_DEBUG, "logicPort: %d\n", lldpEntry.logicPort);
        //snmp_log(LOG_DEBUG, "subtype  : %d\n", lldpEntry.port_id.iSubtype);
        //snmp_log(LOG_DEBUG, "desc     : %s\n\n", lldpEntry.port_description);

        new->lldpLocPortNum = LP2UP(lldpEntry.logicPort);
        new->lldpLocPortIdSubtype = lldpEntry.port_id.iSubtype;
        if (new->lldpLocPortIdSubtype == PORT_ID_MAC_ADDRESS)
        {
            memcpy(new->lldpLocPortId, lldpEntry.port_id.id, 6);
            new->lldpLocPortId_len = 6;
        }
        else
        {
            strcpy(new->lldpLocPortId, lldpEntry.port_id.id);
            new->lldpLocPortId_len = strlen(new->lldpLocPortId);                
        }

        strcpy(new->lldpLocPortDesc, lldpEntry.port_description);
        new->lldpLocPortDesc_len = strlen(new->lldpLocPortDesc);            

        new->next = tmpHead ;
        tmpHead  = new;              
    }        

    oldHead = lldpLocPortTable_head;
    lldpLocPortTable_head = tmpHead;      

    tableFreeAll(oldHead); 

safe_exit:
    
    /* XXX */
    return 1;

}

static int tableCacheLoad( netsnmp_cache *cache, void *vmagic ) 
{
    tableDataLoad(NULL);		
    return 0;  /* OK */
}

static void tableCacheFree( netsnmp_cache *cache, void *vmagic ) 
{
    //do nothing
}

/** Initializes the lldpLocPortTable module */
void
init_lldpLocPortTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    //snmp_log(LOG_DEBUG, "init_lldpLocPortTable init \n");
    initialize_table_lldpLocPortTable();
}

 // # Determine the first/last column names

/** Initialize the lldpLocPortTable table by defining its contents and how it's structured */
void
initialize_table_lldpLocPortTable(void)
{
    static oid lldpLocPortTable_oid[] = {1,0,8802,1,1,2,1,3,7};
    size_t lldpLocPortTable_oid_len   = OID_LENGTH(lldpLocPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "lldpLocPortTable",     lldpLocPortTable_handler,
              lldpLocPortTable_oid, lldpLocPortTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: lldpLocPortNum */
                           0);
    table_info->min_column = COLUMN_LLDPLOCPORTNUM;
    table_info->max_column = COLUMN_LLDPLOCPORTDESC;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = lldpLocPortTable_get_first_data_point;
    iinfo->get_next_data_point  = lldpLocPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    #if 1
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(5,
                                  tableCacheLoad,
								  tableCacheFree,
								  lldpLocPortTable_oid,
								  lldpLocPortTable_oid_len),
								  TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
	tableDataLoad(NULL);
	#endif
}

/* create a new row in the (unsorted) table */
struct lldpLocPortTable_entry *
lldpLocPortTable_createEntry(
                 long  lldpLocPortNum
                ) {
    struct lldpLocPortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct lldpLocPortTable_entry);
    if (!entry)
        return NULL;

    entry->lldpLocPortNum = lldpLocPortNum;
    entry->next = lldpLocPortTable_head;
    lldpLocPortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
lldpLocPortTable_removeEntry( struct lldpLocPortTable_entry *entry ) {
    struct lldpLocPortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = lldpLocPortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        lldpLocPortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
lldpLocPortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = lldpLocPortTable_head;
    return lldpLocPortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
lldpLocPortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct lldpLocPortTable_entry *entry = (struct lldpLocPortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->lldpLocPortNum );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the lldpLocPortTable table */
int
lldpLocPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct lldpLocPortTable_entry          *table_entry;

    //snmp_log(LOG_DEBUG, "requests-mode: %d\n", reqinfo->mode);
    //snmp_log(LOG_DEBUG, "requests-name: %s\n", requests->parent_data->name);

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct lldpLocPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_LLDPLOCPORTNUM:
            	if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lldpLocPortNum);
            	break;
            case COLUMN_LLDPLOCPORTIDSUBTYPE:
                //snmp_log(LOG_DEBUG, "COLUMN_LLDPLOCPORTIDSUBTYPE port %d\n", table_entry->lldpLocPortNum);
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->lldpLocPortIdSubtype);
                break;
            case COLUMN_LLDPLOCPORTID:
                //snmp_log(LOG_DEBUG, "COLUMN_LLDPLOCPORTID port %d\n", table_entry->lldpLocPortNum);
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpLocPortId,
                                          table_entry->lldpLocPortId_len);
                break;
            case COLUMN_LLDPLOCPORTDESC:
                //snmp_log(LOG_DEBUG, "COLUMN_LLDPLOCPORTDESC port %d\n", table_entry->lldpLocPortNum);
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->lldpLocPortDesc,
                                          table_entry->lldpLocPortDesc_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
