/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef __LLDPSTATSTXPORTTABLE_H__
#define __LLDPSTATSTXPORTTABLE_H__

/* function declarations */
void init_lldpStatsTxPortTable(void);

#endif /* LLDPSTATSTXPORTTABLE_H */
