/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17821 2009-11-11 09:00:00Z dts12 $
 */
#ifndef LLDPLOCPORTTABLE_H
#define LLDPLOCPORTTABLE_H

/* function declarations */
void init_lldpLocPortTable(void);
void initialize_table_lldpLocPortTable(void);
Netsnmp_Node_Handler lldpLocPortTable_handler;
Netsnmp_First_Data_Point  lldpLocPortTable_get_first_data_point;
Netsnmp_Next_Data_Point   lldpLocPortTable_get_next_data_point;

/* column number definitions for table lldpLocPortTable */
       #define COLUMN_LLDPLOCPORTNUM		1
       #define COLUMN_LLDPLOCPORTIDSUBTYPE		2
       #define COLUMN_LLDPLOCPORTID		3
       #define COLUMN_LLDPLOCPORTDESC		4
#endif /* LLDPLOCPORTTABLE_H */
