/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "lldpLocalSystemData.h"
#include <lldp/proto_lldp.h>


typedef struct
{
	long lldpLocChassisIdSubtype;		
			
	char lldpLocChassisId[256];// 255 ? 256 todo...
	int lldpLocChassisId_len;
			
	char lldpLocSysName[256];
	int lldpLocSysName_len;
			
	char lldpLocSysDesc[256];
	int lldpLocSysDesc_len;
			
	char lldpLocSysCapSupported[2];
	int lldpLocSysCapSupported_len;
			
	char lldpLocSysCapEnabled[2];
	int lldpLocSysCapEnabled_len;
			
}lldpLocSysData_t;

static lldpLocSysData_t s_lldpLocSys;

static char highLowSwap(char v)
{
    char tmp;
    
    tmp =
    ((v & 0x01)<<7)
    |((v & 0x02)<<5)
    |((v & 0x04)<<3)
    |((v & 0x08)<<1)
    |((v & 0x10)>>1)
    |((v & 0x20)>>3)
    |((v & 0x40)>>5)
    |((v & 0x80)>>7);    

    return tmp;
}
/*    
	lldpLocSysDataLoad   
	-- Load group data from somewhere
*/
static int lldpLocSysDataLoad(lldpLocSysData_t *data)
{
    int ret = 0;
    char *p;
    sys_mac_t macaddr;
    uint32 ipaddr;
    uint32 netmask;
    char ipaddr_str[CAPA_IPV4_STR_LEN];
    char netmask_str[CAPA_IPV4_STR_LEN];
    char macaddr_str[CAPA_MAC_STR_LEN];
    uint8 strIpAddr[CAPA_IPV6_STR_LEN];
    char sysModel[CAPA_SYS_NAME_LEN + 1];
    char sysname[CAPA_SYS_NAME_LEN + 1];
    display_entry_t lldpEntry;

    ret = sal_sys_macAddr_get(&macaddr);
    ret = sal_lldp_portLocalEntryInfo_get(1, &lldpEntry);

    if (!ret)
    {
        data->lldpLocChassisIdSubtype = 4;
        
        memcpy(data->lldpLocChassisId, macaddr.octet, 6);
        data->lldpLocChassisId_len = 6;
        
        strcpy(data->lldpLocSysName, lldpEntry.system_name);
        data->lldpLocSysName_len = strlen(lldpEntry.system_name);
        
        strcpy(data->lldpLocSysDesc, lldpEntry.system_description);
        data->lldpLocSysDesc_len = strlen(lldpEntry.system_description);

        data->lldpLocSysCapEnabled[0] = (char)(lldpEntry.system_capabilities.iEnable & 0xFF);
        data->lldpLocSysCapEnabled[1] = (char)(lldpEntry.system_capabilities.iEnable >> 8 & 0xFF);
        data->lldpLocSysCapEnabled_len = 2;
        
        data->lldpLocSysCapSupported[0] = (char)(lldpEntry.system_capabilities.iSupport & 0xFF);
        data->lldpLocSysCapSupported[1] = (char)(lldpEntry.system_capabilities.iSupport >> 8 & 0xFF);
        data->lldpLocSysCapSupported_len = 2;
    }
	/* XXX */
	return 1;
}

/* ## ENDIF ## */

/* ## Handle functions ## */
static int handle_lldpLocChassisIdSubtype(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpLocSysDataLoad(&s_lldpLocSys);
  
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_integer(requests->requestvb, ASN_INTEGER, s_lldpLocSys.lldpLocChassisIdSubtype);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


static int handle_lldpLocChassisId(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpLocSysDataLoad(&s_lldpLocSys);
  
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, s_lldpLocSys.lldpLocChassisId, s_lldpLocSys.lldpLocChassisId_len);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


static int handle_lldpLocSysName(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpLocSysDataLoad(&s_lldpLocSys);
        
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, s_lldpLocSys.lldpLocSysName, s_lldpLocSys.lldpLocSysName_len);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


static int handle_lldpLocSysDesc(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpLocSysDataLoad(&s_lldpLocSys);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, s_lldpLocSys.lldpLocSysDesc, s_lldpLocSys.lldpLocSysDesc_len);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


static int handle_lldpLocSysCapSupported(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpLocSysDataLoad(&s_lldpLocSys);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, s_lldpLocSys.lldpLocSysCapSupported, s_lldpLocSys.lldpLocSysCapSupported_len);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


static int handle_lldpLocSysCapEnabled(
					netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info   *reqinfo,
                    netsnmp_request_info         *requests
					)
{
    lldpLocSysDataLoad(&s_lldpLocSys);
    
    switch(reqinfo->mode)
	{
        case MODE_GET:
			{
				snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, s_lldpLocSys.lldpLocSysCapEnabled, s_lldpLocSys.lldpLocSysCapEnabled_len);
			}
			break;
        default:
			return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


/*
 * Our initialization routine, called automatically by the agent 
 * (Note that the function name must match init_FILENAME()) 
 */
void init_lldpLocalSystemData(void)
{
    const oid lldpLocChassisIdSubtype_oid[] = {1,0,8802,1,1,2,1,3,1};
    const oid lldpLocChassisId_oid[] = {1,0,8802,1,1,2,1,3,2};
    const oid lldpLocSysName_oid[] = {1,0,8802,1,1,2,1,3,3};
    const oid lldpLocSysDesc_oid[] = {1,0,8802,1,1,2,1,3,4};
    const oid lldpLocSysCapSupported_oid[] = {1,0,8802,1,1,2,1,3,5};
    const oid lldpLocSysCapEnabled_oid[] = {1,0,8802,1,1,2,1,3,6};

    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpLocChassisIdSubtype", 
										handle_lldpLocChassisIdSubtype,
										lldpLocChassisIdSubtype_oid, 
										OID_LENGTH(lldpLocChassisIdSubtype_oid),
										HANDLER_CAN_RONLY
										)
							);
    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpLocChassisId", 
										handle_lldpLocChassisId,
										lldpLocChassisId_oid, 
										OID_LENGTH(lldpLocChassisId_oid),
										HANDLER_CAN_RONLY
										)
							);
    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpLocSysName", 
										handle_lldpLocSysName,
										lldpLocSysName_oid, 
										OID_LENGTH(lldpLocSysName_oid),
										HANDLER_CAN_RONLY
										)
							);
    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpLocSysDesc", 
										handle_lldpLocSysDesc,
										lldpLocSysDesc_oid, 
										OID_LENGTH(lldpLocSysDesc_oid),
										HANDLER_CAN_RONLY
										)
							);
    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpLocSysCapSupported", 
										handle_lldpLocSysCapSupported,
										lldpLocSysCapSupported_oid, 
										OID_LENGTH(lldpLocSysCapSupported_oid),
										HANDLER_CAN_RONLY
										)
							);
    netsnmp_register_scalar(
							netsnmp_create_handler_registration(
										"lldpLocSysCapEnabled", 
										handle_lldpLocSysCapEnabled,
										lldpLocSysCapEnabled_oid, 
										OID_LENGTH(lldpLocSysCapEnabled_oid),
										HANDLER_CAN_RONLY
										)
							);
  
   /* Trying to load group data as default values */
   lldpLocSysDataLoad(&s_lldpLocSys);
   
   //TODO: register callback function for data update
}

