/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "lldpStatsRxPortTable.h"
#include <lldp/proto_lldp.h>

/* function declarations for table lldpStatsRxPortTable */
static void initialize_table_lldpStatsRxPortTable(void);

static Netsnmp_Node_Handler lldpStatsRxPortTable_handler;
static Netsnmp_First_Data_Point  lldpStatsRxPortTable_get_first_data_point;
static Netsnmp_Next_Data_Point   lldpStatsRxPortTable_get_next_data_point;


/* column number definitions for table lldpStatsRxPortTable */
#define COLUMN_LLDPSTATSRXDESTIFINDEX		1
#define COLUMN_LLDPSTATSRXPORTFRAMESDISCARDEDTOTAL		2
#define COLUMN_LLDPSTATSRXPORTFRAMESERRORS		3
#define COLUMN_LLDPSTATSRXPORTFRAMESTOTAL		4
#define COLUMN_LLDPSTATSRXPORTTLVSDISCARDEDTOTAL		5
#define COLUMN_LLDPSTATSRXPORTTLVSUNRECOGNIZEDTOTAL		6
#define COLUMN_LLDPSTATSRXPORTAGEOUTSTOTAL		7

/* Typical data structure for a row entry */
struct lldpStatsRxPortTable_entry
{
     long lldpStatsRxDestIfIndex;

     /* Column values */
     u_long lldpStatsRxPortFramesDiscardedTotal;
     u_long lldpStatsRxPortFramesErrors;
     u_long lldpStatsRxPortFramesTotal;
     u_long lldpStatsRxPortTLVsDiscardedTotal;
     u_long lldpStatsRxPortTLVsUnrecognizedTotal;
     u_long lldpStatsRxPortAgeoutsTotal;   //todo ...
	 
	 /* Illustrate using a simple linked list */ 
	 int   valid; 
	 struct lldpStatsRxPortTable_entry *next;
};

static struct lldpStatsRxPortTable_entry  *lldpStatsRxPortTable_head = NULL;

static void tableFreeAll(struct lldpStatsRxPortTable_entry *head)
{
    struct lldpStatsRxPortTable_entry *this, *that, *tmp;      

    for ( this = head; this; this=that ) 
    {                  
        that = this->next;
        SNMP_FREE( this );  /* XXX - release any other internal resources */
  
    } 
}

/*    
	tableDataLoad   
	-- Load table data from somewhere
*/
static int tableDataLoad(struct lldpStatsRxPortTable_entry *entry)
{
    int ret, num, i;
    struct lldpStatsRxPortTable_entry *new = NULL;
    struct lldpStatsRxPortTable_entry *tmpHead = NULL;   
    struct lldpStatsRxPortTable_entry *oldHead = NULL; 
    lldp_statistic_t lldp_statistic;

    memset(&lldp_statistic, 0, sizeof(lldp_statistic));

    ret+= sal_lldp_statistic_get(&lldp_statistic);
    if (ret != 0)
    {
        return 0;
    }          
    for (i = 0; i < SYS_USER_PORT_NUM(0); i ++)
    {
        new = SNMP_MALLOC_TYPEDEF(struct lldpStatsRxPortTable_entry );
        if (!new)
        {
            goto safe_exit;
        }            
    
        memset(new, 0, sizeof(struct lldpStatsRxPortTable_entry ));

        new->lldpStatsRxDestIfIndex = LP2UP(i);
        new->lldpStatsRxPortFramesDiscardedTotal = lldp_statistic.port_statistics[i].rx_discard_frame;
        new->lldpStatsRxPortFramesErrors = lldp_statistic.port_statistics[i].rx_error_frame;
        new->lldpStatsRxPortFramesTotal = lldp_statistic.port_statistics[i].rx_frame;
        new->lldpStatsRxPortTLVsDiscardedTotal = lldp_statistic.port_statistics[i].rx_discard_tlv;
        new->lldpStatsRxPortTLVsUnrecognizedTotal = lldp_statistic.port_statistics[i].rx_unRecognize_tlv;
        new->lldpStatsRxPortAgeoutsTotal = lldp_statistic.port_statistics[i].rx_ageOut;

        new->next = tmpHead ;
        tmpHead  = new;              
    }

    oldHead = lldpStatsRxPortTable_head;
    lldpStatsRxPortTable_head = tmpHead;      

    tableFreeAll(oldHead);  

safe_exit:
    
    /* XXX */
    return 1;

}

static int tableCacheLoad( netsnmp_cache *cache, void *vmagic ) 
{
    tableDataLoad(NULL);		
    return 0;  /* OK */
}

static void tableCacheFree( netsnmp_cache *cache, void *vmagic ) 
{
    //do nothing
}

/** Initializes the lldpStatsRxPortTable module */
void init_lldpStatsRxPortTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
    initialize_table_lldpStatsRxPortTable();
}


/** Initialize the lldpStatsRxPortTable table by defining its contents and how it's structured */
static void initialize_table_lldpStatsRxPortTable(void)
{
    const oid lldpStatsRxPortTable_oid[] = {1,0,8802,1,1,2,1,2,7};
    const size_t lldpStatsRxPortTable_oid_len   = OID_LENGTH(lldpStatsRxPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("lldpStatsRxPortTable:init", "initializing table lldpStatsRxPortTable\n"));

    reg = netsnmp_create_handler_registration(
											  "lldpStatsRxPortTable",     
											  lldpStatsRxPortTable_handler,
											  lldpStatsRxPortTable_oid, 
											  lldpStatsRxPortTable_oid_len,
											  HANDLER_CAN_RONLY
											  );

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	
    netsnmp_table_helper_add_indexes(
									table_info,
									ASN_INTEGER,  /* index: lldpStatsRxDestIfIndex */
									0
									);
						   
    table_info->min_column = COLUMN_LLDPSTATSRXDESTIFINDEX;
    table_info->max_column = COLUMN_LLDPSTATSRXPORTAGEOUTSTOTAL;
    
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	
    iinfo->get_first_data_point = lldpStatsRxPortTable_get_first_data_point;
    iinfo->get_next_data_point  = lldpStatsRxPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator(reg, iinfo);
	
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(5,
                                  tableCacheLoad,
								  tableCacheFree,
								  lldpStatsRxPortTable_oid,
								  lldpStatsRxPortTable_oid_len),
								  TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
	tableDataLoad(NULL);
}


/* create a new row in the (unsorted) table */
static struct lldpStatsRxPortTable_entry *lldpStatsRxPortTable_createEntry(
											long  lldpStatsRxDestIfIndex) 
{

	struct lldpStatsRxPortTable_entry *entry;
	
    entry = SNMP_MALLOC_TYPEDEF(struct lldpStatsRxPortTable_entry);
    if (!entry)
    {
        return NULL;
    }
	
    entry->lldpStatsRxDestIfIndex = lldpStatsRxDestIfIndex;
    entry->next = lldpStatsRxPortTable_head;
    lldpStatsRxPortTable_head = entry;
	
    return entry;
}


/* remove a row from the table */
static void lldpStatsRxPortTable_removeEntry(struct lldpStatsRxPortTable_entry *entry) 
{
    struct lldpStatsRxPortTable_entry *ptr, *prev;

    if (!entry)
    {
        return;    /* Nothing to remove */
    }
    
	for (ptr = lldpStatsRxPortTable_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next) 
	{
        if (ptr == entry)
    	{
            break;
		}
    }
	
    if (!ptr)
    {
        return;    /* Can't find it */
    }
    
	if (prev == NULL)
	{
        lldpStatsRxPortTable_head = ptr->next;
    }
	else
	{
        prev->next = ptr->next;
	}

    SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
static netsnmp_variable_list *lldpStatsRxPortTable_get_first_data_point(
									void **my_loop_context,
									void **my_data_context,
									netsnmp_variable_list *put_index_data,
									netsnmp_iterator_info *mydata
									)
{
    *my_loop_context = lldpStatsRxPortTable_head;
	
    return lldpStatsRxPortTable_get_next_data_point(
									 my_loop_context, 
									 my_data_context,
                                     put_index_data,
                                     mydata
									 );
}


static netsnmp_variable_list *lldpStatsRxPortTable_get_next_data_point(
									void **my_loop_context,
									void **my_data_context,
									netsnmp_variable_list *put_index_data,
									netsnmp_iterator_info *mydata
									)
{
    struct lldpStatsRxPortTable_entry *entry = (struct lldpStatsRxPortTable_entry *)*my_loop_context;
	
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
	{
        snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->lldpStatsRxDestIfIndex);
        idx = idx->next_variable;

        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    }
	else 
	{
        return NULL;
    }
}


/** handles requests for the lldpStatsRxPortTable table */
static int lldpStatsRxPortTable_handler(
					netsnmp_mib_handler           *handler,
					netsnmp_handler_registration  *reginfo,
					netsnmp_agent_request_info    *reqinfo,
					netsnmp_request_info          *requests
					) 
{

    netsnmp_request_info       	*request;
    netsnmp_table_request_info 	*table_info;
    struct lldpStatsRxPortTable_entry          *table_entry;
	
	int ret;

    DEBUGMSGTL(("lldpStatsRxPortTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) 
	{
		/*
		 * Read-support (also covers GetNext requests)
		 */
		case MODE_GET:
			{
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct lldpStatsRxPortTable_entry *)netsnmp_extract_iterator_context(request);
                                    if(!table_entry)
                                    {
                                        continue;
                                    }  
                                                                 
					table_info  = netsnmp_extract_table_info(request);
			
					switch (table_info->colnum)
					{
						case COLUMN_LLDPSTATSRXDESTIFINDEX:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER, table_entry->lldpStatsRxDestIfIndex);
							}
							break;
						case COLUMN_LLDPSTATSRXPORTFRAMESDISCARDEDTOTAL:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsRxPortFramesDiscardedTotal);
							}
							break;
							
						case COLUMN_LLDPSTATSRXPORTFRAMESERRORS:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsRxPortFramesErrors);
							}
							break;
							
						case COLUMN_LLDPSTATSRXPORTFRAMESTOTAL:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsRxPortFramesTotal);
							}
							break;
							
						case COLUMN_LLDPSTATSRXPORTTLVSDISCARDEDTOTAL:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsRxPortTLVsDiscardedTotal);
							}
							break;
							
						case COLUMN_LLDPSTATSRXPORTTLVSUNRECOGNIZEDTOTAL:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsRxPortTLVsUnrecognizedTotal);
							}
							break;
							
						case COLUMN_LLDPSTATSRXPORTAGEOUTSTOTAL:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								//todo...
								//snmp_set_var_typed_integer(request->requestvb, , table_entry->lldpStatsRxPortAgeoutsTotal);
								snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER, table_entry->lldpStatsRxPortAgeoutsTotal);								
							}
							break;
							
						default:
							{
								netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
							}
							break;
					}
				}
			}
			break;

	}
	
    return SNMP_ERR_NOERROR;
}
