/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef __LLDPLOCALSYSTEMDATA_H__
#define __LLDPLOCALSYSTEMDATA_H__

/* function declarations */
void init_lldpLocalSystemData(void);

#endif /* LLDPLOCALSYSTEMDATA_H */
