/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "lldpPortConfigTable.h"
#include <lldp/proto_lldp.h>


/* function declarations for table lldpPortConfigTable */
static void initialize_table_lldpPortConfigTable(void);

static Netsnmp_Node_Handler table_handler;
static Netsnmp_First_Data_Point  table_get_first_data_point;
static Netsnmp_Next_Data_Point   table_get_next_data_point;


/* column number definitions for table lldpPortConfigTable */
#define COLUMN_LLDPPORTCONFIGIFINDEX		1
#define COLUMN_LLDPPORTCONFIGADMINSTATUS		2
#define COLUMN_LLDPPORTCONFIGNOTIFICATIONENABLE		3
#define COLUMN_LLDPPORTCONFIGTLVSTXENABLE		4


/* Typical mask structure for a row entry */
typedef struct
{
	uint32 lldpPortConfigAdminStatus;
	uint32 lldpPortConfigNotificationEnable;
	uint32 lldpPortConfigTLVsTxEnable;
}tableMask_t;


/* Typical data structure for a row entry */
typedef struct
{
    /* Index values */
    long lldpPortConfigIfIndex;

	/* Column values */
	long lldpPortConfigAdminStatus;
	long lldpPortConfigNotificationEnable;
	char lldpPortConfigTLVsTxEnable[255];
}tableData_t;


struct table_entry
{
	 tableData_t data;
	 
	 tableData_t *tmp; 
	 tableMask_t mask;
	 
	 /* Illustrate using a simple linked list */ 
	 int   valid; 
	 struct table_entry *next;
};

static struct table_entry  *table_head = NULL;

static void tableFreeAll(struct table_entry *head)
{
    struct table_entry *this, *that, *tmp;      

    for ( this = head; this; this=that ) 
    {                  
        that = this->next;
        SNMP_FREE( this );  /* XXX - release any other internal resources */
  
    } 
}

/*    
	tableDataLoad   
	-- Load table data from somewhere
*/
static int tableDataLoad(struct table_entry *entry)
{
    int ret, i;
    struct table_entry *new = NULL;
    struct table_entry *tmpHead = NULL;   
    struct table_entry *oldHead = NULL; 
    uint8 lldpPortState;
    lldp_tlv_sel_t lldpTlvSel;
    uint8 lldpTlvEnable = 0;

    for (i = 0; i < SYS_USER_PORT_NUM(0); i ++)
    {
        new = SNMP_MALLOC_TYPEDEF(struct table_entry );
        if (!new)
        {
            goto safe_exit;
        }

        memset(new, 0, sizeof(struct table_entry ));
        sal_lldp_port_get(i, &lldpPortState);
        sal_lldp_portTlvSel_get(i, &lldpTlvSel);
        
        lldpTlvEnable= lldpTlvSel.managementAddrSel >> 0 |
                       lldpTlvSel.maxFrameSizeSel >> 1 |
                       lldpTlvSel.linkAggregationSel >> 2 |
                       lldpTlvSel.macPhySel >> 3 |
                       lldpTlvSel.sysCapabilitySel >> 4 |
                       lldpTlvSel.sysDescriptionSel >> 5 |
                       lldpTlvSel.sysNameSel >> 6 |
                       lldpTlvSel.portDesciptionSel >> 7;
        
        new->data.lldpPortConfigIfIndex = LP2UP(i);
        new->data.lldpPortConfigAdminStatus = lldpPortState;
        new->data.lldpPortConfigNotificationEnable = 1;
        new->data.lldpPortConfigTLVsTxEnable[0] = lldpTlvEnable;
        new->next = tmpHead ;
        tmpHead  = new;
    }

    oldHead = table_head;
    table_head = tmpHead;

    tableFreeAll(oldHead);  

safe_exit:

    /* XXX */
    return 1;
}



/* ## IF WRITABLE ## */

/* 
	tableDataCommit
	-- Commit changes to somewhere 
*/
static int tableDataCommit(struct table_entry  *entry)
{
    int ret, num, i, count = 0;
    lldp_tlv_sel_t lldpTlvSel;

    for (i = 0; i < SYS_USER_PORT_NUM(0); i ++)
    {
        if (i == entry->data.lldpPortConfigIfIndex)
        {
            sal_lldp_port_set(i, (uint8)entry->data.lldpPortConfigAdminStatus);

            for(count = 0; count < 8; count ++)
            {
                switch (count)
                {
                    case 0:
                        lldpTlvSel.portDesciptionSel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 0 & 0x1;
                        break;
                    case 1:
                        lldpTlvSel.sysNameSel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 1 & 0x1;
                        break;
                    case 2:
                        lldpTlvSel.sysDescriptionSel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 2 & 0x1;
                        break;
                    case 3:
                        lldpTlvSel.sysCapabilitySel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 3 & 0x1;
                        break;
                    case 4:
                        lldpTlvSel.macPhySel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 4 & 0x1;
                        break;
                    case 5:
                        lldpTlvSel.linkAggregationSel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 5 & 0x1;
                        break;
                    case 6:
                        lldpTlvSel.maxFrameSizeSel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 6 & 0x1;
                        break;
                    case 7:
                        lldpTlvSel.managementAddrSel = entry->data.lldpPortConfigTLVsTxEnable[0] >> 7 & 0x1;
                        break;
                }
            }
            sal_lldp_portTlvSel_set(i, lldpTlvSel);
        }  
    }

SAFE_EXIT:

    return 1;
}


static int tableCacheLoad( netsnmp_cache *cache, void *vmagic ) 
{
    tableDataLoad(NULL);		
    return 0;  /* OK */
}

static void tableCacheFree( netsnmp_cache *cache, void *vmagic ) 
{
    //do nothing
}

	
/* 
	lldpPortConfigAdminStatus check functions 
	To check values in request if correct for the node
	return 1 if ok, and return 0 if not
*/
static int check_lldpPortConfigAdminStatus(netsnmp_variable_list *requestvb)
{
	/* XXX */
	return 1;

}

	
/* 
	lldpPortConfigNotificationEnable check functions 
	To check values in request if correct for the node
	return 1 if ok, and return 0 if not
*/
static int check_lldpPortConfigNotificationEnable(netsnmp_variable_list *requestvb)
{
	/* XXX */
	return 1;

}

	
/* 
	lldpPortConfigTLVsTxEnable check functions 
	To check values in request if correct for the node
	return 1 if ok, and return 0 if not
*/
static int check_lldpPortConfigTLVsTxEnable(netsnmp_variable_list *requestvb)
{    
	return 1;

}


static check_row(tableData_t *data)
{
	/* XXX */
	return 1;
}


static dirty(struct table_entry * entry)
{
	if (
		entry->mask.lldpPortConfigAdminStatus ||
		entry->mask.lldpPortConfigNotificationEnable ||
		entry->mask.lldpPortConfigTLVsTxEnable
	   )
	{
		return 1;
	}
	
	return 0;
}
	
	
/* 
	setReset
	-- To clear all changes made by setting requests.
*/
static int setReset(struct table_entry * entry)
{
	if (entry->tmp)
	{
		free(entry->tmp);
		entry->tmp = NULL;
	}
	
	memset(&entry->mask, 0, sizeof(entry->mask));
}


static tableData_t *makeTmp(struct table_entry * entry)
{
	if (entry->tmp == NULL)
	{
		entry->tmp = SNMP_MALLOC_TYPEDEF(tableData_t);
		if (!entry->tmp)
		{
			return NULL;
		}
		memcpy(entry->tmp, &entry->data, sizeof(entry->data));
	}
	
	return entry->tmp;
}


/** Initializes the lldpPortConfigTable module */
void init_lldpPortConfigTable(void)
{
	/* here we initialize all the tables we're planning on supporting */
    initialize_table_lldpPortConfigTable();
}


/** Initialize the lldpPortConfigTable table by defining its contents and how it's structured */
static void initialize_table_lldpPortConfigTable(void)
{
    const oid table_oid[] = {1,0,8802,1,1,2,1,1,8};
    const size_t table_oid_len   = OID_LENGTH(table_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("lldpPortConfigTable:init", "initializing table lldpPortConfigTable\n"));

    reg = netsnmp_create_handler_registration(
											  "lldpPortConfigTable",     
											  table_handler,
											  table_oid, 
											  table_oid_len,
											  HANDLER_CAN_RWRITE
											  );

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
	
    netsnmp_table_helper_add_indexes(
									table_info,
									ASN_INTEGER,  /* index: lldpPortConfigIfIndex */
									0
									);
						   
    table_info->min_column = COLUMN_LLDPPORTCONFIGIFINDEX;
    table_info->max_column = COLUMN_LLDPPORTCONFIGTLVSTXENABLE;
    
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);
	
    iinfo->get_first_data_point = table_get_first_data_point;
    iinfo->get_next_data_point  = table_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator(reg, iinfo);
	
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(5,
                                  tableCacheLoad,
								  tableCacheFree,
								  table_oid,
								  table_oid_len),
								  TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
	tableDataLoad(NULL);

}


/* create a new row in the (unsorted) table */
static struct table_entry *table_createEntry(
											long  lldpPortConfigIfIndex) 
{
	struct table_entry *entry;
	
    entry = SNMP_MALLOC_TYPEDEF(struct table_entry);
    if (!entry)
    {
        return NULL;
    }
	
    entry->data.lldpPortConfigIfIndex = lldpPortConfigIfIndex;
    entry->next = table_head;
    table_head = entry;
	
    return entry;
}


/* remove a row from the table */
static void table_removeEntry(struct table_entry *entry) 
{
    struct table_entry *ptr, *prev;

    if (!entry)
    {
        return;    /* Nothing to remove */
    }
    
	for (ptr = table_head, prev = NULL;
         ptr != NULL;
         prev = ptr, ptr = ptr->next) 
	{
        if (ptr == entry)
    	{
            break;
		}
    }
	
    if (!ptr)
    {
        return;    /* Can't find it */
    }
    
	if (prev == NULL)
	{
        table_head = ptr->next;
    }
	else
	{
        prev->next = ptr->next;
	}

    SNMP_FREE(entry);   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
static netsnmp_variable_list *table_get_first_data_point(
									void **my_loop_context,
									void **my_data_context,
									netsnmp_variable_list *put_index_data,
									netsnmp_iterator_info *mydata
									)
{
    *my_loop_context = table_head;
	
    return table_get_next_data_point(
									 my_loop_context, 
									 my_data_context,
                                     put_index_data,
                                     mydata
									 );
}


static netsnmp_variable_list *table_get_next_data_point(
									void **my_loop_context,
									void **my_data_context,
									netsnmp_variable_list *put_index_data,
									netsnmp_iterator_info *mydata
									)
{
    struct table_entry *entry = (struct table_entry *)*my_loop_context;
	
    netsnmp_variable_list *idx = put_index_data;

    if (entry)
	{
        snmp_set_var_typed_integer(idx, ASN_INTEGER, entry->data.lldpPortConfigIfIndex);
        idx = idx->next_variable;
	  	
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
		
        return put_index_data;
    }
	else 
	{
        return NULL;
    }
}


/** handles requests for the lldpPortConfigTable table */
static int table_handler(
					netsnmp_mib_handler           *handler,
					netsnmp_handler_registration  *reginfo,
					netsnmp_agent_request_info    *reqinfo,
					netsnmp_request_info          *requests
					) 
{

    netsnmp_request_info       	*request;
    netsnmp_table_request_info 	*table_info;
    struct table_entry          *table_entry;
	
	int ret;

    switch (reqinfo->mode) 
	{
		/*
		 * Read-support (also covers GetNext requests)
		 */
		case MODE_GET:
			{
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);
                                    if(!table_entry)
                                    {
                                        continue;
                                    }  
                                                            
					table_info  = netsnmp_extract_table_info(request);
			
					switch (table_info->colnum)
					{
						case COLUMN_LLDPPORTCONFIGADMINSTATUS:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER, table_entry->data.lldpPortConfigAdminStatus);
							}
							break;
							
						case COLUMN_LLDPPORTCONFIGNOTIFICATIONENABLE:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER, table_entry->data.lldpPortConfigNotificationEnable);
							}
							break;
							
						case COLUMN_LLDPPORTCONFIGTLVSTXENABLE:
							{
								if (!table_entry) 
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
									continue;
								}
								
								snmp_set_var_typed_value(
														 request->requestvb,
														 ASN_OCTET_STR,
														 table_entry->data.lldpPortConfigTLVsTxEnable,
														 1
														 );
							}
							break;
							
						default:
							{
								netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
							}
							break;
					}
				}
			}
			break;

		/*
		 * Write-support
		 */
		case MODE_SET_RESERVE1:
			{
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);
                                    
					table_info  = netsnmp_extract_table_info(request);
			
					switch (table_info->colnum) 
					{
						case COLUMN_LLDPPORTCONFIGADMINSTATUS:
							{
								/* or possibly 'netsnmp_check_vb_int_range' */
								ret = netsnmp_check_vb_int(request->requestvb);
								if (ret != SNMP_ERR_NOERROR) 
								{
									netsnmp_set_request_error(reqinfo, request, ret);
									return SNMP_ERR_NOERROR;
								}
							}
							break;

						case COLUMN_LLDPPORTCONFIGNOTIFICATIONENABLE:
							{
								/* or possibly 'netsnmp_check_vb_int_range' */
								ret = netsnmp_check_vb_int(request->requestvb);
								if (ret != SNMP_ERR_NOERROR) 
								{
									netsnmp_set_request_error(reqinfo, request, ret);
									return SNMP_ERR_NOERROR;
								}
							}
							break;

						case COLUMN_LLDPPORTCONFIGTLVSTXENABLE:
							{
								/* or possibly 'netsnmp_check_vb_type_and_size' */
								ret = netsnmp_check_vb_type_and_max_size(request->requestvb, ASN_OCTET_STR, sizeof(table_entry->data.lldpPortConfigTLVsTxEnable));
								if (ret != SNMP_ERR_NOERROR) 
								{
									netsnmp_set_request_error(reqinfo, request, ret);
									return SNMP_ERR_NOERROR;
								}
							}
							break;

						default:
						{
							netsnmp_set_request_error(reqinfo, request, SNMP_ERR_NOTWRITABLE);
							return SNMP_ERR_NOERROR;
						}
					}
				}
			}
			break;

		case MODE_SET_RESERVE2:
			{
				/* Check the other requests */
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *) netsnmp_extract_iterator_context(request);
					table_info = netsnmp_extract_table_info(request);

					/* Now, the request should not be nonexistent */
					if (table_entry == NULL)
					{
						netsnmp_set_request_error(reqinfo, request, SNMP_ERR_RESOURCEUNAVAILABLE);
						return SNMP_ERR_NOERROR;
					}

					switch (table_info->colnum)
					{
						case COLUMN_LLDPPORTCONFIGADMINSTATUS:
							{
								/* XXX */
								if (!check_lldpPortConfigAdminStatus(request->requestvb))
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_ERR_BADVALUE);
								}
								else
								{
									makeTmp(table_entry);
									
									netsnmp_get_var_data(&table_entry->tmp->lldpPortConfigAdminStatus, sizeof(table_entry->tmp->lldpPortConfigAdminStatus), request->requestvb);
									table_entry->mask.lldpPortConfigAdminStatus = 1;
								}
							}
							break;

						case COLUMN_LLDPPORTCONFIGNOTIFICATIONENABLE:
							{
								/* XXX */
								if (!check_lldpPortConfigNotificationEnable(request->requestvb))
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_ERR_BADVALUE);
								}
								else
								{
									makeTmp(table_entry);
									
									netsnmp_get_var_data(&table_entry->tmp->lldpPortConfigNotificationEnable, sizeof(table_entry->tmp->lldpPortConfigNotificationEnable), request->requestvb);
									table_entry->mask.lldpPortConfigNotificationEnable = 1;
								}
							}
							break;

						case COLUMN_LLDPPORTCONFIGTLVSTXENABLE:
							{
								/* XXX */
								if (!check_lldpPortConfigTLVsTxEnable(request->requestvb))
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_ERR_BADVALUE);
								}
								else
								{
									makeTmp(table_entry);
									netsnmp_get_var_data(table_entry->tmp->lldpPortConfigTLVsTxEnable, sizeof(table_entry->tmp->lldpPortConfigTLVsTxEnable), request->requestvb);
									table_entry->mask.lldpPortConfigTLVsTxEnable = 1;
								}
							}
							break;

						default:
						{
							netsnmp_set_request_error(reqinfo, request,SNMP_ERR_NOTWRITABLE);
							return SNMP_ERR_NOERROR;
						}
					}
				}	
			}
			break;

		case MODE_SET_FREE:
			{
				/* Remove the rows create in SetReserve2 */
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);
             
					table_info = netsnmp_extract_table_info(request);

					switch (table_info->colnum) 
					{
					}
				} 	   

				/* Free other rows */
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);
                                                        
					table_info = netsnmp_extract_table_info(request);

					/* Do not need to poll every column in requests. */
					if (table_entry && dirty(table_entry))
					{
						setReset(table_entry);
					}
				}       

			}
			break;

		case MODE_SET_ACTION:
			{
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);         
					
					table_info = netsnmp_extract_table_info(request);
			
					switch (table_info->colnum)
					{
						case COLUMN_LLDPPORTCONFIGADMINSTATUS:
							{
								if (!check_row(table_entry->tmp))
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_ERR_BADVALUE);	
								}
								else
								{
									netsnmp_get_var_data(&table_entry->data.lldpPortConfigAdminStatus, sizeof(table_entry->data.lldpPortConfigAdminStatus), request->requestvb);
								}
							}
							break;

						case COLUMN_LLDPPORTCONFIGNOTIFICATIONENABLE:
							{
								if (!check_row(table_entry->tmp))
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_ERR_BADVALUE);	
								}
								else
								{
									netsnmp_get_var_data(&table_entry->data.lldpPortConfigNotificationEnable, sizeof(table_entry->data.lldpPortConfigNotificationEnable), request->requestvb);
								}
							}
							break;

						case COLUMN_LLDPPORTCONFIGTLVSTXENABLE:
							{
								if (!check_row(table_entry->tmp))
								{
									netsnmp_set_request_error(reqinfo, request, SNMP_ERR_BADVALUE);	
								}
								else
								{
								    netsnmp_get_var_data(table_entry->data.lldpPortConfigTLVsTxEnable, sizeof(table_entry->data.lldpPortConfigTLVsTxEnable), request->requestvb);
								}
							}
							break;

					}
				}

			}
			break;

		case MODE_SET_UNDO:
			{
				/* Remove the rows create in SetReserve2 */
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);                    
					table_info = netsnmp_extract_table_info(request);
					
					switch (table_info->colnum) 
					{
					}
				}

				/* Free other rows */
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);
                                                        
					table_info  =  netsnmp_extract_table_info(request);

					/* Do not need to poll every column in request. */
					if (table_entry && dirty(table_entry))
					{
						setReset(table_entry);
					}
				}        
			}
			break;

		case MODE_SET_COMMIT:
			{
				for (request = requests; request; request = request->next) 
				{
					table_entry = (struct table_entry *)netsnmp_extract_iterator_context(request);
              
					table_info = netsnmp_extract_table_info(request);

					/* Do not need to poll every column in request. */
					if (dirty(table_entry))
					{
						tableDataCommit(table_entry);
						
						setReset(table_entry);    		
					}
				}     
			}
			break;

	}
	
    return SNMP_ERR_NOERROR;
}
