/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef __LLDPSTATSRXPORTTABLE_H__
#define __LLDPSTATSRXPORTTABLE_H__

/* function declarations */
void init_lldpStatsRxPortTable(void);

#endif /* LLDPSTATSRXPORTTABLE_H */
