/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "snmpCommunityMIB.h"

/*
 * snmpCommunityMIB_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid snmpCommunityMIB_variables_oid[] = { 1,3,6,1,6,3,18 };

#define TABLE_SIZE 32


#define SNMPCOMMUNITYINDEX      1
#define SNMPCOMMUNITYNAME       2
#define SNMPCOMMUNITYSECURITYNAME       3
#define SNMPCOMMUNITYCONTEXTENGINEID        4
#define SNMPCOMMUNITYCONTEXTNAME        5
#define SNMPCOMMUNITYTRANSPORTTAG       6
#define SNMPCOMMUNITYSTORAGETYPE        7
#define SNMPCOMMUNITYSTATUS     8
#define SNMPTARGETADDRTMASK     9
#define SNMPTARGETADDRMMS       10

#ifdef CONFIG_SYS_SNMPV3
/*
 * variable4 snmpCommunityMIB_variables:
 *   this variable defines function callbacks and type return information
 *   for the snmpCommunityMIB mib section
 */

struct variable7 snmpCommunityMIB_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

{SNMPCOMMUNITYINDEX,  ASN_OCTET_STR,  RONLY,   var_snmpCommunityTable, 4,  { 1,1, 1, 1 }},

{SNMPCOMMUNITYNAME,  ASN_OCTET_STR,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 2 }},

{SNMPCOMMUNITYSECURITYNAME,  ASN_OCTET_STR,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 3 }},

{SNMPCOMMUNITYCONTEXTENGINEID,  ASN_OCTET_STR,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 4 }},

{SNMPCOMMUNITYCONTEXTNAME,  ASN_OCTET_STR,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 5 }},

{SNMPCOMMUNITYTRANSPORTTAG,  ASN_OCTET_STR,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 6 }},

{SNMPCOMMUNITYSTORAGETYPE,  ASN_INTEGER,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 7 }},

{SNMPCOMMUNITYSTATUS,  ASN_INTEGER,  RWRITE,  var_snmpCommunityTable, 4,  { 1,1, 1, 8 }},

{SNMPTARGETADDRTMASK,  ASN_OCTET_STR,  RWRITE,  var_snmpTargetAddrExtTable, 4,  { 1,2, 1, 1 }},

{SNMPTARGETADDRMMS,  ASN_INTEGER,  RWRITE,  var_snmpTargetAddrExtTable, 4,  { 1,2, 1, 2 }},
};
/*    (L = length of the oidsuffix) */



//Rtk add
snmp_com2sec_t *snmpScanPtr = NULL, *snmpComList = NULL;

void snmp_community_removeAll(void)
{
    snmp_com2sec_t *pTmp = NULL;
    snmp_com2sec_t *prev = NULL;
    pTmp = snmpComList;
    while (pTmp)
    {
        prev = pTmp;
        pTmp = pTmp->next;
        SNMP_FREE(prev);
    }
    snmpComList = NULL;
}

void snmp_community_scanAccessInit(void)
{
    snmpScanPtr  = snmpComList;
}


snmp_com2sec_t *snmp_community_scanFirst(void)
{
    return snmpComList;
}

snmp_com2sec_t *snmp_community_scanAccessNext(void)
{
    snmp_com2sec_t *returnval = snmpScanPtr;
    if (snmpScanPtr)
        snmpScanPtr  = snmpScanPtr->next;
    return returnval;
}

snmp_com2sec_t *snmp_communityEntry_get(char *pComName)
{
    if (NULL == pComName)
        return NULL;

    snmpScanPtr  = snmpComList;
    while(snmpScanPtr)
    {
        if ( 0 == osal_strcmp(pComName, snmpScanPtr->comEntry.comName))
            return snmpScanPtr;

        snmpScanPtr = snmpScanPtr->next;
    }

    return NULL;
}

int32 snmp_community_creatEntry(sal_snmp_com2sec_t *pEntry)
{
    snmp_com2sec_t *entry;
    snmp_com2sec_t *pTmp;

    SYS_PARAM_CHK((NULL == pEntry), SYS_ERR_NULL_POINTER);

    entry = SNMP_MALLOC_TYPEDEF(snmp_com2sec_t);
    if(!entry)
        return SYS_ERR_FAILED;

    osal_memset(entry,0,sizeof(snmp_com2sec_t));
    osal_strcpy(entry->comEntry.secName, pEntry->secName);
    osal_strcpy(entry->comEntry.comName, pEntry->comName);
    osal_strcpy(entry->comEntry.sourceNet, pEntry->sourceNet);
    osal_strcpy(entry->comEntry.mask, pEntry->mask);
    entry->comEntry.access = pEntry->access;
    entry->next = NULL;

    if (snmpComList == NULL)
        snmpComList = entry;
    else
    {
        pTmp = snmpComList;
        while(pTmp->next)
        {
            pTmp = pTmp->next;
        }
        pTmp->next = entry;
    }

    return SYS_ERR_OK;
}

int32 snmp_community_entry_get(uint32 *pEntryNum)
{
    sal_snmp_com2sec_t comEntry;
    uint32   entryNum = 0;
    int index;

    SYS_PARAM_CHK((NULL == pEntryNum), SYS_ERR_NULL_POINTER);

    snmp_community_removeAll();

     for ( index = 0; index < CAPA_SNMP_COMMUNITY_NUM; index++)
     {
        SYS_ERR_CHK(sal_snmp_com2sec_get(index, &comEntry));

        if (osal_strlen(comEntry.comName) != 0)
        {
            snmp_community_creatEntry(&comEntry);
            entryNum++;
        }
    }

    *pEntryNum = entryNum;
    return SYS_ERR_OK;
}


/** Initializes the snmpCommunityMIB module */
void
init_snmpCommunityMIB(void)
{

    DEBUGMSGTL(("snmpCommunityMIB", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("snmpCommunityMIB", snmpCommunityMIB_variables, variable7,
               snmpCommunityMIB_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_snmpCommunityMIB():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_snmpCommunityMIB(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_snmpCommunityTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_snmpCommunityMIB above.
 */
unsigned char *
var_snmpCommunityTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    int32 entryNum, i, strLen;
    char comStr[CAPA_SNMP_COMMUNITY_LEN+1];
    snmp_com2sec_t  *pCom;
    static char tmpStr[BOND_SNMP_ENGINEID_LEN_MAX + 1];

    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
       return NULL;
    }

    if (exact) {
        if (*length < 12 || *length > 12+CAPA_SNMP_COMMUNITY_LEN)
            return NULL;

        osal_memset(comStr, 0, sizeof(comStr));
        for (i = 11; i < *length; i++)
        {
            if (name[i] >= 255)
                return NULL;
            comStr[i-11] = (char)name[i];
        }
        pCom = snmp_communityEntry_get(comStr);
    } else {
        if (11 == *length)
        {
            snmp_community_entry_get(&entryNum);
            if(entryNum == 0)
            return NULL;

            osal_memset(comStr, 0 , sizeof(comStr));
            pCom = snmp_community_scanFirst();
        }
        else
        {
            pCom = NULL;
            osal_memset(comStr, 0 , sizeof(comStr));

            if (*length < 12 || *length > 12+CAPA_SNMP_COMMUNITY_LEN)
                return NULL;

            for (i = 11; i < *length; i++)
            {
                if (name[i] >= 255)
                    return NULL;
                comStr[i-11] = (char)name[i];
            }

           snmp_community_scanAccessInit();
           while((pCom = snmp_community_scanAccessNext()) != NULL){
            if ((0 == osal_memcmp(comStr , pCom->comEntry.comName, *length - 11 )) &&
                     (osal_strlen( pCom->comEntry.comName) == osal_strlen(comStr)))
             {
                 pCom = snmp_community_scanAccessNext();
                 break;
             }
           }
         }

        if (pCom) {
            strLen = osal_strlen(pCom->comEntry.comName);
            for (i = 0; i < strLen; i++)
            {
                name[11 + i] = (uint32)(pCom->comEntry.comName[i]);
            }
            *length = 11 + strLen;
        }
    }

    if (pCom == NULL) {
        return NULL;
    }

    *var_len = sizeof(long_ret);
    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case SNMPCOMMUNITYINDEX:
        #if 0
        *var_len = osal_strlen(pCom->comEntry.comName);
        return (u_char*)pCom->comEntry.comName;
        #endif
        return NULL;
    case SNMPCOMMUNITYNAME:
        *write_method = write_snmpCommunityName;
        SYS_MEM_CLEAR(tmpStr);
        osal_strcpy(tmpStr, pCom->comEntry.comName);
        *var_len = osal_strlen(tmpStr);
        return (u_char*)tmpStr;
    case SNMPCOMMUNITYSECURITYNAME:
        *write_method = write_snmpCommunitySecurityName;
        SYS_MEM_CLEAR(tmpStr);
        osal_strcpy(tmpStr, pCom->comEntry.secName);
        *var_len = osal_strlen(tmpStr);
        return (u_char*)tmpStr;
    case SNMPCOMMUNITYCONTEXTENGINEID:
        *write_method = write_snmpCommunityContextEngineID;
        SYS_MEM_CLEAR(tmpStr);
        #ifdef CONFIG_SYS_SNMPV3
        sal_snmp_engineid_get(tmpStr);
        #endif
        *var_len = osal_strlen(tmpStr);
        return (u_char*) tmpStr;
    case SNMPCOMMUNITYCONTEXTNAME:
        *write_method = write_snmpCommunityContextName;
        *var_len = 0;
        osal_memset(tmpStr, 0, sizeof(tmpStr));
        return (u_char*)tmpStr;
    case SNMPCOMMUNITYTRANSPORTTAG:
        *write_method = write_snmpCommunityTransportTag;
        *var_len = 0;
        osal_memset(tmpStr, 0, sizeof(tmpStr));
        return (u_char*)tmpStr;
    case SNMPCOMMUNITYSTORAGETYPE:
        *write_method = write_snmpCommunityStorageType;
        long_ret  = SNMP_STORAGE_NONVOLATILE;
        return (u_char*) &long_ret;
    case SNMPCOMMUNITYSTATUS:
        *write_method = write_snmpCommunityStatus;
        long_ret = 1;
        return (u_char*) &long_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_snmpTargetAddrExtTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_snmpCommunityMIB above.
 */
unsigned char *
var_snmpTargetAddrExtTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case SNMPTARGETADDRTMASK:
        *write_method = write_snmpTargetAddrTMask;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case SNMPTARGETADDRMMS:
        *write_method = write_snmpTargetAddrMMS;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      break;
    }
    return NULL;
}


int
write_snmpCommunityName(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          return SNMP_ERR_NOTWRITABLE;
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpCommunitySecurityName(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

         return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpCommunityContextEngineID(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpCommunityContextName(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpCommunityTransportTag(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpCommunityStorageType(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpCommunityStatus(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpTargetAddrTMask(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_snmpTargetAddrMMS(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to snmpCommunityMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to snmpCommunityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

#endif /*CONFIG_SYS_SNMPV3*/
