/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef SNMPCOMMUNITYMIB_H
#define SNMPCOMMUNITYMIB_H

#include <libsal/sal_snmp.h>

#ifdef CONFIG_SYS_SNMPV3
typedef struct snmp_com2sec_s
{
    sal_snmp_com2sec_t comEntry;
    struct snmp_com2sec_s *next;
}snmp_com2sec_t;
#endif

/* function declarations */
void init_snmpCommunityMIB(void);
FindVarMethod var_snmpCommunityMIB;
FindVarMethod var_snmpCommunityTable;
FindVarMethod var_snmpTargetAddrExtTable;
    WriteMethod write_snmpCommunityName;
    WriteMethod write_snmpCommunitySecurityName;
    WriteMethod write_snmpCommunityContextEngineID;
    WriteMethod write_snmpCommunityContextName;
    WriteMethod write_snmpCommunityTransportTag;
    WriteMethod write_snmpCommunityStorageType;
    WriteMethod write_snmpCommunityStatus;
    WriteMethod write_snmpTargetAddrTMask;
    WriteMethod write_snmpTargetAddrMMS;

#endif /* SNMPCOMMUNITYMIB_H */
