/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * FEATURE: L2
 */
#define CONFIG_SYS_JUMBO_FRAME 1
#define CONFIG_SYS_PROTO_LACP 1

/*
 * Spanning Tree
 */
#define CONFIG_SYS_PROTO_STP 1
#define CONFIG_SYS_PROTO_STP 1
#define CONFIG_SYS_PROTO_STP_MSTP 1
#undef  CONFIG_SYS_PROTO_STP_DEFINE_OPEN
#define CONFIG_SYS_STP_BPDU_FILTER 1
#define CONFIG_SYS_STP_SELFLOOP_PREVENT 1
#undef  CONFIG_SYS_PROTO_LOOPBACK
#define CONFIG_SYS_PROTO_ERPS 1
#undef  CONFIG_SYS_PROTO_GARP

/*
 * FEATURE: L3
 */
#define CONFIG_SYS_RTL838x_L3_ENTRY_NUM 1
#undef  CONFIG_SYS_RTL839x_L3_ENTRY_NUM
#undef  CONFIG_SYS_RTL9300_L3_ENTRY_NUM
#undef  CONFIG_SYS_RTL9310_L3_ENTRY_NUM
#define CONFIG_SYS_L3_INTFLO_NUM 1
#define CONFIG_SYS_L3_INTFVLAN_NUM 15
#define CONFIG_SYS_L3_INTFVLAN_IP_SUB_NUM 2
#define CONFIG_SYS_L3_PREFIX_IPV4_NUM 100
#define CONFIG_SYS_L3_PREFIX_IPV6_NUM 100
#define CONFIG_SYS_L3_HOST_ROUTE_NUM 512
#define CONFIG_SYS_L3_ROUTE 1
#define CONFIG_SYS_APP_IPROUTE2 1
#define CONFIG_SYS_L3_ARCHITECTURE 1
#undef  CONFIG_SYS_L3_ROUTE_RIP
#define CONFIG_SYS_L3_ROUTE_ZEBRA 1
#undef  CONFIG_SYS_L3_ROUTE_OSPF
#undef  CONFIG_SYS_L3_ROUTE_BGP
#undef  CONFIG_SYS_L3_VRRP
#define CONFIG_SYS_DHCP_SERVER 1

/*
 * FEATURE: VLAN
 */
#define CONFIG_SYS_VLAN_MAX_NUM 1024
#define CONFIG_SYS_PROTO_GVRP 1
#define CONFIG_SYS_MACVLAN 1
#define CONFIG_SYS_PROTOCOL_VLAN 1
#define CONFIG_SYS_VLAN_QINQ 1
#define CONFIG_SYS_SURVEILLANCEVLAN 1
#define CONFIG_SYS_VOICEVLAN 1
#undef  CONFIG_SYS_IP_SUBNET
#undef  CONFIG_SYS_VLAN_PORT_MODE_ACCESS
#undef  CONFIG_SYS_VLAN_PORT_MODE_HYBRID
#define CONFIG_SYS_VLAN_PORT_MODE_TRUNK 1

/*
 * FEATURE: Multicast
 */
#define CONFIG_SYS_MCAST_GROUP_NUM 256
#define CONFIG_SYS_PROTO_IGMP_SNOOPING 1
#define CONFIG_SYS_PROTO_IGMPV3_BASIC 1
#define CONFIG_SYS_PROTO_IGMP_SNOOPING_QUERIER 1
#define CONFIG_SYS_PROTO_IGMP_STATIC_ROUTER 1
#define CONFIG_SYS_PROTO_IGMP_STATIC_FORWARD 1
#define CONFIG_SYS_PROTO_IGMP_FILTERING 1
#define CONFIG_SYS_PROTO_IGMP_THROTTLING 1
#define CONFIG_SYS_PROTO_MLD_SNOOPING 1
#define CONFIG_SYS_PROTO_MVR 1

/*
 * FEATURE: QoS
 */
#define CONFIG_SYS_BW_CTRL 1

/*
 * FEATURE: ACL
 */
#define CONFIG_SYS_USER_DEFINED_ACL 1
#undef  CONFIG_SYS_USER_DEFINED_ACL_DENY_ALL

/*
 * FEATURE: Security
 */
#define CONFIG_SYS_AAA 1
#define CONFIG_SYS_AAA_AUTHENTICATION 1
#undef  CONFIG_SYS_AAA_ENABLE_AUTHENTICATION
#define CONFIG_SYS_PROTO_AUTHMGR 1
#define CONFIG_SYS_PROTO_DOT1X 1
#define CONFIG_SYS_PROTO_MACAUTH 1
#define CONFIG_SYS_PROTO_WEBAUTH 1
#define CONFIG_SYS_APP_IPROUTE2 1
#undef  CONFIG_SYS_DEL_DEF_USERNAME
#define CONFIG_SYS_USER_PS_MIX_LENGTH 3
#undef  CONFIG_SYS_CONSOLE_NO_AUTH
#define CONFIG_SYS_BLACK_HOLE_MAC 1
#undef  CONFIG_SYS_FLAPPING_MAC
#define CONFIG_SYS_STP_BPDU_GUARD 1
#define CONFIG_SYS_DEFENCE_ENGINE 1
#define CONFIG_SYS_CPU_QUEUE_UTILIZATION 1
#define CONFIG_SYS_PROTO_DHCPSNOOPING 1
#define CONFIG_SYS_PROTO_DHCP 1
#define CONFIG_SYS_PROTO_DHCPSNOOPING_USERDEFINE_CID 1
#define CONFIG_SYS_DOS_PROTECTION 1
#define CONFIG_SYS_PROTO_DAI 1
#define CONFIG_USER_BOA_WITH_SSL 1
#define CONFIG_SYS_PROTO_ISG 1
#define CONFIG_SYS_PROTO_ISG_NETMASK 1
#define CONFIG_SYS_MANAGEMENT_VLAN 1
#define CONFIG_SYS_MGMT_ACL 1
#define CONFIG_SYS_PORT_SECURITY 1
#define CONFIG_SYS_PORT_ISOLATION 1
#define CONFIG_SYS_LIB_RADIUS 1
#undef  CONFIG_USER_SSH_SSH
#define CONFIG_SYS_APP_SSH 1
#define CONFIG_USER_SSH_SSHKEYGEN 1
#define CONFIG_USER_SSH_SSHD 1
#define CONFIG_SYS_LIB_SSL 1
#define CONFIG_SYS_APP_OPENSSL 1
#define CONFIG_SYS_STORM_CTRL 1
#define CONFIG_SYS_LIB_TACPLUS 1

/*
 * FEATURE: Management
 */
#define CONFIG_SYS_BACKUP_CONFIGURATION 1
#define CONFIG_SYS_UI_CLI 1
#define CONFIG_SYS_UI_CLI_SESSION 8
#define CONFIG_SYS_APP_DHCPC 1
#define CONFIG_SYS_ADVANCE_DNS 1
#define CONFIG_SYS_DUAL_IMAGE 1
#define CONFIG_SYS_EEE 1
#define CONFIG_SYS_PORT_ERR_DISABLED 1
#define CONFIG_SYS_PORT_DESCRIPTION 1
#define CONFIG_SYS_UI_CLI_LINE_MGMT 1
#define CONFIG_SYS_UI_CLI_SESSION_TIMEOUT 1
#define CONFIG_SYS_UI_CLI_PASSRETRY_SILENT 1
#define CONFIG_SYS_USER_ACCESS_METH_VALUE 31
#define CONFIG_SYS_MIB_RMON_MGMT_UI 1
#define CONFIG_SYS_SNMP 1
#define CONFIG_SYS_UI_SNMP 1
#define CONFIG_SYS_SNMPV3 1
#define CONFIG_SYS_APP_MSNTP 1
#define CONFIG_SYS_APP_TELNETD 1
#define CONFIG_USER_TELNETD_DOES_NOT_USE_OPENPTY 1
#undef  CONFIG_SYS_APP_TELNET
#define CONFIG_SYS_UI_WEB 1
#define CONFIG_SYS_APP_HTTPD 1
#define CONFIG_SYS_UI_WEB_LOGIN_PAGE 1
#define CONFIG_SYS_UI_WEB_SESSION_TIMEOUT 1
#undef  CONFIG_SYS_UI_WEB_THREE_LEVEL_TREE
#undef  CONFIG_SYS_APP_EASYCWMP

/*
 * FEATURE: Discovery
 */
#define CONFIG_SYS_PROTO_LLDP 1
#define CONFIG_SYS_PROTO_LLDP_MED 1

/*
 * FEATURE: Diagnotics
 */
#define CONFIG_SYS_BW_UTILIZATION 1
#define CONFIG_SYS_CABLE_DIAG 1
#define CONFIG_SYS_CPU_UTILIZATION 1
#define CONFIG_SYS_OPTICALMOD_STATUS 1
#define CONFIG_SYS_SYSLOG 1
#define CONFIG_USER_SYSLOG_RAM_SIZE_256K 1
#define CONFIG_USER_SYSLOG_FLASH_SIZE_256K 1
#define CONFIG_USER_SYSLOG_RAM_SIZE 18
#define CONFIG_USER_SYSLOG_FLASH_SIZE 18
#define CONFIG_SYS_LOG_SEVERITY_LEVEL 5
#define CONFIG_SYS_MEM_UTILIZATION 1
#define CONFIG_SYS_PING_TEST 1
#define CONFIG_SYS_MIRROR 1
#define CONFIG_SYS_TRACE_ROUTE 1
#define CONFIG_SYS_TECH_SUPPORT 1
#define CONFIG_SYS_PROTO_UDLD 1

/*
 * FEATURE: MIB
 */
#define CONFIG_SYS_MIBII 1
#define CONFIG_SYS_MIB_TRAP 1
#define CONFIG_SYS_MIB_BRIDGE 1
#define CONFIG_SYS_MIB_EXT_BRIDGE 1
#define CONFIG_SYS_MIB_ENTITY 1
#define CONFIG_SYS_MIB_RMON 1
#define CONFIG_SYS_MIB_INTERFACE_GROUP 1
#define CONFIG_SYS_MIB_ETHERLIKE 1
#define CONFIG_SYS_MIB_COMMUNITY 1
#define CONFIG_SYS_MIB_SNMPV3_CONF 1
#define CONFIG_SYS_MIB_SNMP_LLDP_CONF 1
#undef  CONFIG_PRIVATE_MIB
#undef  CONFIG_SYS_MIB_POE_CONF
#define CONFIG_SYS_MIB_HARDWAREINFO_CONF 1
#undef  CONFIG_SYS_MIB_PORTCTRL_CONF
#undef  CONFIG_SYS_MIB_DHCPSNOOPING_CONF

/*
 * SYSTEM : Hardware Board
 */

/*
 * Switch Chip
 */
#define CONFIG_SYS_RTL8380 1
#undef  CONFIG_SYS_RTL8390
#undef  CONFIG_SYS_RTL9300
#undef  CONFIG_SYS_RTL9310
#define CONFIG_SYS_BUTTON 1
#undef  CONFIG_SYS_BUTTON_RESET_INTERRUPT
#define CONFIG_SYS_BUTTON_RESET_POLLING 1
#define CONFIG_SYS_BUTTON_RESET 1
#undef  CONFIG_SYS_DYING_GASP
#define CONFIG_SYS_FIBER 1
#undef  CONFIG_SYS_FIBER_PREFERENCE_INTERRUPT
#define CONFIG_SYS_FIBER_PREFERENCE_POLLING 1
#define CONFIG_SYS_FIBER_PREFERENCE 1
#undef  CONFIG_SYS_FIBER_TXDISABLE
#define CONFIG_SYS_LED 1
#undef  CONFIG_SYS_LED_BLINKING_CONTINUE
#undef  CONFIG_SYS_LED_BLINKING_32MS
#undef  CONFIG_SYS_LED_BLINKING_128MS
#define CONFIG_SYS_LED_BLINKING_512MS 1
#undef  CONFIG_SYS_LED_MODE_OFF
#undef  CONFIG_SYS_RESET
#define CONFIG_SYS_WATCHDOG 1
#undef  CONFIG_SYS_TEST_SW_CHECK
#undef  CONFIG_SYS_UART1
#undef  CONFIG_SYS_HW_USB
#undef  CONFIG_SYS_ENCRYPT
#define CONFIG_SYS_POE 1
#define CONFIG_SYS_POE_SWDOG 1
#define CONFIG_SYS_POE_LED 1
#undef  CONFIG_SYS_POE_CHIP_TPS23861
#undef  CONFIG_SYS_POE_CHIP_TPS23880
#undef  CONFIG_SYS_POE_CHIP_TPS23882
#undef  CONFIG_SYS_POE_CHIP_RTL8238
#undef  CONFIG_SYS_POE_CHIP_RTL8238B
#undef  CONFIG_SYS_POE_CHIP_RTL8239
#undef  CONFIG_SYS_POE_CHIP_MP3924
#define CONFIG_SYS_POE_CHIP_IP808 1
#undef  CONFIG_SYS_BOARD_DEBUG_INFO
#undef  CONFIG_SYS_HO_BOARD

/*
 * SYSTEM : Software Platform
 */
#undef  CONFIG_SYS_BUILD_DEVEL
#define CONFIG_SYS_BUILD_RELEASE 1
#define CONFIG_SYS_KERNEL_LINUX 1
#define CONFIG_SYS_KERNEL_LINUX_MODULE_LOADABLE 1
#define CONFIG_SYS_PLAT_LXBOARD 1
#define CONFIG_SYS_PLAT_LXDEFDB 1
#define CONFIG_SYS_PLAT_LXKSI 1
#define CONFIG_SYS_PLAT_LXSKI 1
#define CONFIG_SYS_PLAT_LXVLAN 1
#define CONFIG_SYS_PLAT_FW 1
#define CONFIG_SYS_APP 1
#define CONFIG_SYS_LIB 1
#undef  CONFIG_SYS_PLAT_AUTOREBOOT
#define CONFIG_SYS_KERNEL_LINUX_COMPRESSED_FS 1
#define CONFIG_SYS_PLAT_CUSMOD 1
#define CONFIG_SYS_PLAT_DBGMOD 1
#define CONFIG_SYS_IPV6 1
#define CONFIG_SYS_APP_DHCP6C 1
#define CONFIG_SYS_APP_DHCP6C_STATELESS 1
#define CONFIG_SYS_FW_SIGNATURE_CHECK 1
#define CONFIG_SYS_FW_UPGRADE_CHECKMEM 1
#define CONFIG_SYS_FW_UPGRADE_SAVEMEM 1
#define CONFIG_SYS_FW_UPGRADE_SAVEMEM_SIZE 10000
#define CONFIG_SYS_LIB_CFG 1
#define CONFIG_SYS_LIB_CMD 1
#define CONFIG_SYS_LIB_CUSTOM 1
#define CONFIG_SYS_LIB_FDS 1
#define CONFIG_SYS_LIB_GCC 1
#define CONFIG_SYS_LIB_GLUE 1
#define CONFIG_SYS_LIB_NCURSES 1
#define CONFIG_SYS_LIB_READLINE 1
#define CONFIG_SYS_LIB_SAL 1
#define CONFIG_SYS_LIB_VTY 1
#define CONFIG_SYS_LIB_IPC 1
#define CONFIG_SYS_APP_INETD 1
#define CONFIG_SYS_APP_INITD 1
#define CONFIG_SYS_APP_KSID 1
#define CONFIG_SYS_APP_POLLD 1

/*
 * OEM    : Factory Settings
 */
#define SYS_OEM_USERNAME "admin"
#define SYS_OEM_PASSWORD "admin"
#define SYS_OEM_NAME "Switch"
#define SYS_OEM_LOCATION "Default"
#define SYS_OEM_CONTACT "Default"
#define SYS_OEM_MANUFACTURER "Default"
#define SYS_OEM_SUPPORT_INFO "Default"
#define SYS_OEM_CONTACT_TELE "Default"
#define SYS_OEM_LOGIN_LOG_NAME "logo_login_ch.png"
#define SYS_OEM_HOME_LOG_NAME "logo_ch.png"
#define SYS_OEM_TIME_ZONE 480
#define CONFIG_SYS_KERNEL_LINUX_3_18_24_X 1
#define CONFIG_SYS_LOADER_UBOOT2011 1
#define PRODUCT_VERSION "1.0.0.9"
#define PLATFORM_NAME "SWGP-42GSFP"
#define COPYRIGHT "Copyright (C) 2025"
#define VENDOR_URL "http://symanitron.ru"
