#ifndef __COMMON_SYS_LOG_DESC_H__
#define __COMMON_SYS_LOG_DESC_H__
#include <common/sys_type.h>
typedef enum log_cat_e
{
    LOG_CAT_AAA,
    LOG_CAT_ACLMGR,
#ifdef CONFIG_SYS_PROTO_AUTHMGR
    LOG_CAT_AUTHMGR,
#endif
    LOG_CAT_CFGMGR,
#ifdef CONFIG_SYS_PROTO_DAI
    LOG_CAT_DAI,
#endif
#ifdef CONFIG_SYS_PROTO_DHCPSNOOPING
    LOG_CAT_DHCP_SNOOPING,
#endif
    LOG_CAT_IMAGEMGR,
#ifdef CONFIG_SYS_PROTO_ISG
    LOG_CAT_IPSG,
#endif
    LOG_CAT_L2,
#ifdef CONFIG_SYS_L3_ROUTE
    LOG_CAT_L3,
#endif
#ifdef CONFIG_SYS_PROTO_LLDP
    LOG_CAT_LLDP,
#endif
    LOG_CAT_LOGGING,
#ifdef CONFIG_SYS_PROTO_IGMP_SNOOPING
    LOG_CAT_MCAST,
#endif
#ifdef CONFIG_SYS_MIRROR
    LOG_CAT_MIRROR,
#endif
    LOG_CAT_PLATFORM,   
    LOG_CAT_PORT,
#ifdef CONFIG_SYS_PORT_SECURITY
    LOG_CAT_PSECURE,
#endif
    LOG_CAT_QOSMGR,
#ifdef CONFIG_SYS_MIB_RMON_MGMT_UI
    LOG_CAT_RMON,
#endif
#ifdef CONFIG_SYS_UI_SNMP
    LOG_CAT_SNMP,
#endif
    LOG_CAT_TIME,
#ifdef CONFIG_SYS_PROTO_STP
    LOG_CAT_STP,
#endif
    LOG_CAT_STORM_CONTROL,
    LOG_CAT_SYSTEM,     
    LOG_CAT_LAG,
#ifdef CONFIG_SYS_PROTO_UDLD
    LOG_CAT_UDLD,
#endif
    LOG_CAT_VLAN,
    LOG_CAT_POE, 
#ifdef CONFIG_SYS_PROTO_ERPS
	LOG_CAT_ERPS,
#endif
#ifdef CONFIG_SYS_PROTO_LOOPBACK
	LOG_CAT_LOOPBACK,
#endif

    LOG_CAT_ALL
} log_cat_t;

typedef enum log_mid_aaa_e
{
#ifdef __KERNEL__
    
#else
    LOG_AAA_CONNECT,
    LOG_AAA_DISCONNECT,
    LOG_AAA_REJECT,
    LOG_AAA_USER_REJECT,
    LOG_AAA_ENABLE_SUCCESS,
    LOG_AAA_ENABLE_FAIL,
    LOG_AAA_USER_ADD,
    LOG_AAA_USER_EDIT,
    LOG_AAA_USER_DEL,
  #ifdef CONFIG_SYS_AAA
    LOG_AAA_METHOD_NEW,
    LOG_AAA_METHOD_FAIL,
    LOG_AAA_AUTH_SUCCESS,
    LOG_AAA_AUTH_FAIL,
    #ifdef CONFIG_SYS_LIB_RADIUS
    LOG_AAA_RADIUS_EMPTY,
    LOG_AAA_RADIUS_CONN_FAIL,
    LOG_AAA_RADIUS_CONN_SUCCESS,
    #endif
    #ifdef CONFIG_SYS_LIB_TACPLUS
    LOG_AAA_TACACS_EMPTY,
    LOG_AAA_TACACS_CONN_FAIL,
    LOG_AAA_TACACS_CONN_SUCCESS,
    LOG_AAA_TACACS_USER_INVALID,
    LOG_AAA_TACACS_REPLYMSG,
    #endif
  #endif
#endif
    LOG_AAA_MAX,
} log_mid_aaa_t;

#ifdef CONFIG_SYS_PROTO_AUTHMGR
typedef enum log_mid_authmgr_e
{
#ifdef __KERNEL__
    LOG_AUTHMGR_START,
    LOG_AUTHMGR_FAIL,
    LOG_AUTHMGR_SUCCESS,
    LOG_AUTHMGR_VLAN_ASSIGN,
    LOG_AUTHMGR_SECURITY_VIOLATION,
    LOG_AUTHMGR_MAC_MOVE,
    LOG_AUTHMGR_LOCK,
    LOG_AUTHMGR_GUESTVLAN,
    LOG_AUTHMGR_FAILOVER,
    LOG_AUTHMGR_NOMORE_METHODS,
    LOG_AUTHMGR_TIMEOUT_INACT,
    LOG_AUTHMGR_TIMEOUT_REAUTH,
    LOG_AUTHMGR_TIMEOUT_QUIET,
    LOG_AUTHMGR_DOT1X_FAIL,
    LOG_AUTHMGR_DOT1X_SUCCESS,
    LOG_AUTHMGR_MACAUTH_FAIL,
    LOG_AUTHMGR_MACAUTH_SUCCESS,
    LOG_AUTHMGR_WEBAUTH_FAIL,
    LOG_AUTHMGR_WEBAUTH_SUCCESS,
#else
    LOG_AUTHMGR_FORCE_UNAUTH,
    LOG_AUTHMGR_FORCE_AUTH,
    LOG_AUTHMGR_RADIUS_EMPTY,
    LOG_AUTHMGR_RADIUS_CONN_FAIL,
    LOG_AUTHMGR_RADIUS_CONN_SUCCESS,
    LOG_AUTHMGR_RADIUS_VLAN_INVALID,
    LOG_AUTHMGR_RADIUS_VLAN_NOTFOUND,
    LOG_AUTHMGR_RADIUS_TUNNELMEDIUMTYPE_INVALID,
    LOG_AUTHMGR_RADIUS_TUNNELTYPE_INVALID,
#endif
    LOG_AUTHMGR_MAX,
} log_mid_authmgr_t;
#endif

typedef enum log_mid_acl_e
{
#ifdef __KERNEL__
  #ifdef CONFIG_SYS_MGMT_ACL
    LOG_ACLMGR_MGMT_HTTP_DENY,
    LOG_ACLMGR_MGMT_HTTPS_DENY,
    LOG_ACLMGR_MGMT_SSH_DENY,
    LOG_ACLMGR_MGMT_TELNET_DENY,
    LOG_ACLMGR_MGMT_SNMP_DENY,
    LOG_ACLMGR_MGMT_INSPECTION_START,
    LOG_ACLMGR_MGMT_INSPECTION_STOP,
  #endif
  #ifdef CONFIG_SYS_USER_DEFINED_ACL
    LOG_ACLMGR_USER_ERRDISABLE,
    LOG_ACLMGR_USER_SHUTDOWN,
  #endif
    LOG_ACLMGR_RSV_BLOCK,
    LOG_ACLMGR_RSV_RESTORE,
    LOG_ACLMGR_RSV_ENABLE,
    LOG_ACLMGR_RSV_DISABLE,
    LOG_ACLMGR_RSV_REMOVE,
    LOG_ACLMGR_RSV_RULE_UPDATE,
    LOG_ACLMGR_RSV_ACTION_UPDATE,
    LOG_ACLMGR_TCAM_FULL,
    LOG_ACLMGR_L4PORTRANGE_FULL,
    LOG_ACLMGR_VLANRANGE_FULL,
    LOG_ACLMGR_COUNTER_FULL,
    LOG_ACLMGR_METER_FULL,
    LOG_ACLMGR_RANGE_ENTRY_FULL,
    LOG_ACLMGR_PROTO_REGISTER,
#endif
    LOG_ACLMGR_MAX,
} log_mid_acl_t;

typedef enum log_mid_cfgmgr_e
{
#ifdef __KERNEL__
    
#else
    LOG_CFGMGR_CFG_INVALID,
    LOG_CFGMGR_COMMAND_FAIL,
    LOG_CFGMGR_UPGRADE_SUCCESS,
    LOG_CFGMGR_UPGRADE_FAIL,
    LOG_CFGMGR_BACKUP_SUCCESS,
    LOG_CFGMGR_BACKUP_FAIL,
    LOG_CFGMGR_SAVE_SUCCESS,
    LOG_CFGMGR_SAVE_FAIL,
#endif
    LOG_CFGMGR_MAX,
} log_mid_cfgmgr_t;

#ifdef CONFIG_SYS_PROTO_DAI
typedef enum log_mid_dai_e
{
#ifdef __KERNEL__
    LOG_DAI_RATE_EXCEED,
    LOG_DAI_ERRDISABLE,
    LOG_DAI_SMAC_DROP,
    LOG_DAI_DMAC_DROP,
    LOG_DAI_SIP_DROP,
    LOG_DAI_DIP_DROP,
    LOG_DAI_TARGET_IPMAC_BIND_DROP,
    LOG_DAI_SENDER_IPMAC_BIND_DROP,
    LOG_DAI_GLOBAL_DROP,
    LOG_DAI_VLAN_DROP,
    LOG_DAI_STP_DROP,
#endif
    LOG_DAI_MAX,
} log_mid_dia_t;
#endif

#ifdef CONFIG_SYS_PROTO_DHCPSNOOPING
typedef enum log_mid_dhcp_snooping_e
{
#ifdef __KERNEL__
    LOG_DHCP_SNOOPING_ALLOCATE_FAIL,
    LOG_DHCP_SNOOPING_RATE_EXCEED,
    LOG_DHCP_SNOOPING_ERRDISABLE,
    LOG_DHCP_SNOOPING_TRANSACTION_FULL,
    LOG_DHCP_SNOOPING_TRANSACTION_FAIL,
    LOG_DHCP_SNOOPING_RELEASE_INVALID,
    LOG_DHCP_SNOOPING_UNTRUSTED_DROP,
    LOG_DHCP_SNOOPING_CHADDR_DROP,
    LOG_DHCP_SNOOPING_OPTION_INVALID,
    LOG_DHCP_SNOOPING_OPTION82_DROP,
    LOG_DHCP_SNOOPING_GLOBAL_DROP,
    LOG_DHCP_SNOOPING_VLAN_FORWARD,
    LOG_DHCP_SNOOPING_STP_DROP,
#endif
    LOG_DHCP_SNOOPING_MAX,
} log_mid_dhcp_snooping_t;
#endif

typedef enum log_mid_imagemgr_e
{
#ifdef __KERNEL__
    
#else
    LOG_IMAGEMGR_FLASH_IMG_BROKEN,
    LOG_IMAGEMGR_MEMORY_LACK,
    LOG_IMAGEMGR_IMG_INVALID,
    LOG_IMAGEMGR_IMG_CHKSUM,
    LOG_IMAGEMGR_IMG_LOCKED,
    LOG_IMAGEMGR_UPGRADE_SUCCESS,
    LOG_IMAGEMGR_UPGRADE_FAIL,
    LOG_IMAGEMGR_BACKUP_SUCCESS,
    LOG_IMAGEMGR_BACKUP_FAIL,
    LOG_IMAGEMGR_IMG_ACTIVE,
#endif
    LOG_IMAGEMGR_MAX,
} log_mid_imagemgr_t;

#ifdef CONFIG_SYS_PROTO_ISG
typedef enum log_mid_ipsg_e
{
#ifdef __KERNEL__
    LOG_IPSG_BINDING_COLLISION,
    LOG_IPSG_DB_FULL,
    LOG_IPSG_ENTRY_FULL,
#else
    LOG_IPSG_DB_DOWNLOAD_FAIL,
    LOG_IPSG_DB_DOWNLOAD_SUCCESS,
    LOG_IPSG_DB_UPLOAD_FAIL,
    LOG_IPSG_DB_UPLOAD_SUCCESS,
    LOG_IPSG_DB_READ_FAIL,
    LOG_IPSG_DB_WRITE_FAIL,
    LOG_IPSG_DB_RESTORE_SUCCESS,
    LOG_IPSG_DB_INTF_NOTEXIST,
#endif
    LOG_IPSG_MAX,
} log_mid_ipsg_t;
#endif

typedef enum log_mid_l2_e
{
#ifdef __KERNEL__
    LOG_L2_TABLE_FULL,
    LOG_L2_STATIC_TIMEOUT,
#endif
    LOG_L2_MAX,
} log_mid_l2_t;

#ifdef CONFIG_SYS_L3_ROUTE
typedef enum log_mid_l3_e
{
#ifdef __KERNEL__
#else
    LOG_L3_IP_SUBNET_OVERLAP,
    LOG_L3_IP_SUBNET_DUPLICATE,
    LOG_L3_IPV6_INTFIP_DUPLICATE,
#endif
    LOG_L3_MAX,
} log_mid_l3_t;
#endif

#ifdef CONFIG_SYS_PROTO_LLDP
typedef enum log_mid_lldp_e
{
#ifdef __KERNEL__
    LOG_LLDP_ETHERTYPE_INVALID,
    LOG_LLDP_LEN_INVALID,
    LOG_LLDP_NEIGHBOR_LIMIT,
    LOG_LLDP_FRAME_DROP,
    LOG_LLDP_TLV_UNRECOGNIZE,
    LOG_LLDP_DISABLE,
    LOG_LLDP_NEIGHBOR_DISCOVER,
    LOG_LLDP_NEIGHBOR_DEL,
    LOG_LLDP_NEIGHBOR_TIMEOUT,
    LOG_LLDP_FRAME_ERROR,
    LOG_LLDP_TLV_DROP,
#else
    LOG_LLDP_TXOVERLOAD,
#endif

    LOG_LLDP_MAX,
} log_mid_lldp_t;
#endif

#ifdef CONFIG_SYS_PROTO_IGMP_SNOOPING
typedef enum log_mid_mcast_e
{
#ifdef __KERNEL__
    LOG_MCAST_DB_UPDATE_FAIL,
    LOG_MCAST_ASIC_DMAC_UPDATE_FAIL,
    LOG_MCAST_ASIC_DIP_UPDATE_FAIL,
    LOG_MCAST_DB_ADD_FAIL,
    LOG_MCAST_ASIC_DMAC_ADD_FAIL,
    LOG_MCAST_ASIC_DIP_ADD_FAIL,
    LOG_MCAST_DB_DEL_FAIL,
    LOG_MCAST_ASIC_DMAC_DEL_FAIL,
    LOG_MCAST_ASIC_DIP_DEL_FAIL,
    LOG_MCAST_DB_FULL,
    LOG_MCAST_DMAC_COLLISION,
    LOG_MCAST_DIP_COLLISION,
    #ifdef CONFIG_SYS_PROTO_IGMP_THROTTLING
    LOG_MCAST_LIMIT_EXCEED,
    #endif
    LOG_MCAST_PKT_CHKSUM_DROP,
    LOG_MCAST_VLAN_DISABLE,
    LOG_MCAST_RTPORT_PIM_ADD,
    LOG_MCAST_RTPORT_ADD,
    LOG_MCAST_VLAN_DISABLE_FLOOD,
    LOG_MCAST_RTPORT_TIMEOUT,
    LOG_MCAST_GROUP_RANGE_INVALID,
    LOG_MCAST_STP_DROP,
    LOG_MCAST_VLAN_DROP,
    LOG_MCAST_VER_FLOOD,
    LOG_MCAST_GROUP_NOTEXSIT_DROP,
    #ifdef CONFIG_SYS_PROTO_MVR
    LOG_MCAST_MVR_VLAN_FLOOD,
    LOG_MCAST_MVR_TYPE_DROP,
    LOG_MCAST_MVR_RECEIVER_DROP,
    LOG_MCAST_MVR_NOTSRC_DROP,
    #endif
#else
    
#endif
    LOG_MCAST_MAX,
} log_mid_mcast_t;
#endif

typedef enum log_mid_logging_e
{
#ifdef __KERNEL__
    
#else
    LOG_LOGGING_BUF_START,
    LOG_LOGGING_BUF_STOP,
    LOG_LOGGING_CONSOLE_START,
    LOG_LOGGING_CONSOLE_STOP,
    LOG_LOGGING_FILE_START,
    LOG_LOGGING_FILE_STOP,
    LOG_LOGGING_START,
    LOG_LOGGING_STOP,
    LOG_LOGGING_AGG_AGETIME,
    LOG_LOGGING_AGG_START,
    LOG_LOGGING_AGG_STOP,
    LOG_LOGGING_HOST_ADD,
    LOG_LOGGING_HOST_DEL,
#endif
    LOG_LOGGING_MAX,
} log_mid_logging_t;

#ifdef CONFIG_SYS_MIRROR
typedef enum log_mid_mirror_e
{
#ifdef __KERNEL__
    LOG_MIRROR_MONITOR_ON,
    LOG_MIRROR_MONITOR_OFF,
#endif

    LOG_MIRROR_MAX,
} log_mid_mirror_t;
#endif

typedef enum log_mid_platform_e
{
#ifdef __KERNEL__
    LOG_PLATFORM_OPTICAL_INSERT,
    LOG_PLATFORM_OPTICAL_REMOVE,
#else
    LOG_PLATFORM_OPTICAL_AUTOSPEED,
#endif
    LOG_PLATFORM_MAX,
} log_mid_platform_t;

typedef enum log_mid_port_e
{
#ifdef __KERNEL__
    LOG_PORT_LINK_DOWN,
    LOG_PORT_LINK_UP,
    LOG_PORT_MEDIA_CHANGE,
    LOG_PORT_SPEED_DUPLEX,
#ifdef CONFIG_SYS_PORT_ERR_DISABLED
    LOG_PORT_ERR_DISABLE,
    LOG_PORT_ERR_RECOVERY,
#endif
#endif
    LOG_PORT_MAX,
} log_mid_port_t;

#ifdef CONFIG_SYS_PORT_SECURITY
typedef enum log_mid_psecure_e
{
#ifdef __KERNEL__
    LOG_PSECURE_VIOLATION,
#else
    LOG_PSECURE_COUNT_LIMIT,
#endif
    LOG_PSECURE_MAX,
} log_mid_psecure_t;
#endif

typedef enum log_mid_qosmgr_e
{
#ifdef __KERNEL__
    
#else
    LOG_QOSMGR_STRICT_PRI_QUEUE,
    LOG_QOSMGR_QUEUE_WEIGHT,
#endif
    LOG_QOSMGR_MAX,
} log_mid_qosmgr_t;

#ifdef CONFIG_SYS_MIB_RMON_MGMT_UI
typedef enum log_mid_rmon_e
{
#ifdef __KERNEL__
    
#else
    LOG_RMON_ALARM_RISING,
    LOG_RMON_ALARM_FALLING,
#endif
    LOG_RMON_MAX,
} log_mid_rmon_t;
#endif

#ifdef CONFIG_SYS_UI_SNMP
typedef enum log_mid_snmp_e
{
#ifdef __KERNEL__
 
#else
    LOG_SNMP_AUTH_FAIL,
    LOG_SNMP_TRAP_CONN_FAIL,
    LOG_SNMP_TRAP_DROP,
    #ifdef CONFIG_SYS_SNMPV3
    LOG_SNMP_USER_REJECT,
    #endif
#endif
    LOG_SNMP_MAX,
} log_mid_snmp_t;
#endif

typedef enum log_mid_storm_control_e
{
#ifdef __KERNEL__
    LOG_STORM_CONTROL_DROP,
    LOG_STORM_CONTROL_SHUTDOWN,
#endif
    LOG_STORM_CONTROL_MAX,
} log_mid_storm_control_t;

#ifdef CONFIG_SYS_PROTO_STP
typedef enum log_mid_stp_e
{
#ifdef __KERNEL__
  #ifdef CONFIG_SYS_STP_BPDU_GUARD
    LOG_STP_BPDUGUARD,
  #endif
    LOG_STP_SELFLOOP,
  #ifdef CONFIG_SYS_STP_BPDU_FILTER
    LOG_STP_BPDUFILTER,
  #endif
    LOG_STP_EDGEPORT,
    LOG_STP_MSTI_PORT_STATE,
    LOG_STP_PORT_STATE,
#else
    LOG_STP_DISABLE,
    LOG_STP_ENABLE,
    LOG_STP_MIGRATION,
    LOG_STP_PORT_DISABLE,
    LOG_STP_PORT_ENABLE,
    LOG_STP_RSTP,
    LOG_STP_STP,
  #ifdef CONFIG_SYS_PROTO_STP_MSTP
    LOG_STP_MSTI_VLAN_ADD,
    LOG_STP_MSTI_VLAN_DEL,
    LOG_STP_MSTP,
  #endif
#endif
    LOG_STP_MAX,
} log_mid_stp_t;
#endif
typedef enum log_mid_time_e
{
#ifdef __KERNEL__
    
#else
  #ifdef CONFIG_SYS_APP_MSNTP
    LOG_TIME_CONN_FAIL,
    LOG_TIME_PKT_ERR,
    LOG_TIME_START,
    LOG_TIME_STOP,
    LOG_TIME_TIME_SYNC,
    LOG_TIME_CONN_SUCCESS,
  #endif
#endif
    LOG_TIME_MAX,
} log_mid_time_t;

#ifdef CONFIG_SYS_PROTO_LOOPBACK
typedef enum log_mid_loopback_e
{
    LOG_SYSTEM_LOOPBACK_PORT_CHANGE,
    LOG_SYSTEM_LOOPBACK_MAX,
} log_mid_loopback_t;
#endif

typedef enum log_mid_system_e
{
#ifdef __KERNEL__
    
#else
    LOG_SYSTEM_REBOOT,
    LOG_SYSTEM_RESTORE,
    LOG_SYSTEM_FACTORY_RESTORE,
    LOG_SYSTEM_INTF_RESTORE,
    LOG_SYSTEM_WARMSTART,
    LOG_SYSTEM_COLDSTART,
    LOG_SYSTEM_NAME,
    LOG_SYSTEM_LOCATION,
    LOG_SYSTEM_CONTACT,
#ifdef CONFIG_SYS_APP_TELNETD
    LOG_SYSTEM_TELNET_START,
    LOG_SYSTEM_TELNET_STOP,
    LOG_SYSTEM_TELNETD_START_FAIL,
#endif
#ifdef CONFIG_USER_SSH_SSHD
    LOG_SYSTEM_SSH_START,
    LOG_SYSTEM_SSH_STOP,
    LOG_SYSTEM_SSHD_START_FAIL,
#endif
    LOG_SYSTEM_HTTP_START,
    LOG_SYSTEM_HTTP_STOP,
    LOG_SYSTEM_HTTPS_START,
    LOG_SYSTEM_HTTPS_STOP,
    LOG_SYSTEM_HTTPD_START_FAIL,
    LOG_SYSTEM_CLI_SESSION_FULL,
    LOG_SYSTEM_CLI_TIMEOUT,
    LOG_SYSTEM_WEB_TIMEOUT,
    LOG_SYSTEM_TFTP_ERROR,
    LOG_SYSTEM_FLASH_OPERATE_ERROR,
    LOG_SYSTEM_SYSINFO_CHKSUM_ERROR,
    LOG_SYSTEM_SYSINFO_CFG,
    LOG_SYSTEM_BDINFO_CHKSUM_ERROR,
    LOG_SYSTEM_BDINFO_CFG,
    LOG_SYSTEM_DHCPC_START,
    LOG_SYSTEM_DHCPC_STOP,
    LOG_SYSTEM_DHCP6C_START,
    LOG_SYSTEM_DHCP6C_STOP,
    LOG_SYSTEM_IP,
    LOG_SYSTEM_GW,
    LOG_SYSTEM_IPV6,
    LOG_SYSTEM_IPV6_GW,
    LOG_SYSTEM_IPV6_AUTOCONFIG_START,
    LOG_SYSTEM_IPV6_AUTOCONFIG_STOP,
    LOG_SYSTEM_DNS_IPV4,
    LOG_SYSTEM_DNS_IPV6,
    LOG_SYSTEM_DNS_DHCPC,
    LOG_SYSTEM_DNS_DHCP6C,
  #ifdef CONFIG_SYS_UI_SNMP
    LOG_SYSTEM_SNMP_START,
    LOG_SYSTEM_SNMP_STOP,
  #endif
#endif
    LOG_SYSTEM_MAX,
} log_mid_system_t;

typedef enum log_mid_lag_e
{
#ifdef __KERNEL__
#ifdef CONFIG_SYS_PROTO_LACP
    LOG_LAG_LACP_MBR_TIMEOUT,
    LOG_LAG_LACP_MBR_EXCEED,
#endif
#else
#ifdef CONFIG_SYS_PROTO_LACP
    LOG_LAG_LACP_ACTIVE,
    LOG_LAG_LACP_PASSIVE,
#endif
#endif
    LOG_LAG_MAX,
} log_mid_lag_t;

#ifdef CONFIG_SYS_PROTO_UDLD
typedef enum log_mid_udld_e
{
#ifdef __KERNEL__
    LOG_UDLD_ALLOCATE_FAIL,
    LOG_UDLD_AGGRESSIVE_FAIL,
    LOG_UDLD_LOOP_DETECT,
    LOG_UDLD_NEIGHBOR_MISMATCH_DETECT,
    LOG_UDLD_UNIDIRECTIONAL_DETECT,
    LOG_UDLD_PKT_CHKSUM_DROP,
    LOG_UDLD_PKT_INVALID_DROP,
    LOG_UDLD_PKT_PORT_DROP,
    LOG_UDLD_RESET,
#endif
    LOG_UDLD_MAX,
} log_mid_udld_t;
#endif

typedef enum log_mid_vlan_e
{
#ifdef __KERNEL__
    LOG_VLAN_TYPE,
  #ifdef CONFIG_SYS_PROTO_GVRP
    LOG_VLAN_GVRP_CREATE,
    LOG_VLAN_GVRP_DESTROY,
    LOG_VLAN_GVRP_MBR_ADD,
    LOG_VLAN_GVRP_MBR_DEL,
    LOG_VLAN_GVRP_PROTO_ID_INVALID,
    LOG_VLAN_GVRP_ATTR_TYPE_INVALID,
    LOG_VLAN_GVRP_ATTR_LEN_INVALID,
    LOG_VLAN_GVRP_ATTR_VALUE_INVALID,
    LOG_VLAN_GVRP_ATTR_EVENT_INVALID,
    LOG_VLAN_GVRP_DB_FULL,
    LOG_VLAN_GVRP_DROP,
  #endif
  #ifdef CONFIG_SYS_MACVLAN
    LOG_VLAN_MAC_RESOURCE_LACK,
    LOG_VLAN_MAC_BIND_FAIL,
    LOG_VLAN_MAC_UNBIND_FAIL,
    LOG_VLAN_MAC_UPDATE_FAIL,
  #endif
  #ifdef CONFIG_SYS_PROTOCOL_VLAN
    LOG_VLAN_PROTO_RESOURCE_LACK,
    LOG_VLAN_PROTO_BIND_FAIL,
    LOG_VLAN_PROTO_UNBIND_FAIL,
    LOG_VLAN_PROTO_UPDATE_FAIL,
  #endif
  #ifdef CONFIG_SYS_VOICEVLAN
    LOG_VLAN_VOICE_RESOURCE_LACK,
    LOG_VLAN_VOICE_CONFIG_FAIL,
    LOG_VLAN_VOICE_GLOBAL_DROP,
    LOG_VLAN_VOICE_INTF_DROP,
    LOG_VLAN_VOICE_OUI_DROP,
    LOG_VLAN_VOICE_MBR_ADD,
    LOG_VLAN_VOICE_MBR_DEL,
    LOG_VLAN_VOICE_MBR_LLDP_ADD,
    LOG_VLAN_VOICE_MBR_LLDP_DEL,
  #endif
  #ifdef CONFIG_SYS_SURVEILLANCEVLAN
    LOG_VLAN_SURVEILLANCE_RESOURCE_LACK,
    LOG_VLAN_SURVEILLANCE_CONFIG_FAIL,
    LOG_VLAN_SURVEILLANCE_GLOBAL_DROP,
    LOG_VLAN_SURVEILLANCE_INTF_DROP,
    LOG_VLAN_SURVEILLANCE_OUI_DROP,
    LOG_VLAN_SURVEILLANCE_MBR_ADD,
    LOG_VLAN_SURVEILLANCE_MBR_DEL,
  #endif
#else
    LOG_VLAN_CREATE_FAIL,
    LOG_VLAN_DESTROY_FAIL,
    LOG_VLAN_DEFAULT_VLAN,
    LOG_VLAN_CREATE,
    LOG_VLAN_DESTROY,
#endif
    LOG_VLAN_MAX,
} log_mid_vlan_t;
typedef struct log_msg_s
{
    uint32 sev;
    char   mnem[SYS_BUF64_LEN];
    char   *msg;
} log_msg_t;

typedef struct sys_log_desc_s
{
    const char      text[SYS_BUF64_LEN];    
    const uint32    msgnum;     
    const log_msg_t *msgtbl;    
} sys_log_desc_t;
#endif

