option refreshtime 86400;
option refreshtime-min 600;
interface eth0 {
 send ia-na 1;
 request domain-name-servers,domain-name,refreshtime,bootfile-url,bootfile-param;
 script "/etc/dhcp6c-script";
};

id-assoc na 1 {
};
