/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_IN_UBOOT 1

/*
 * SDK Options
 */

/*
 * Chip Support
 */

/*
 * Select your target MAC chip(s)
 */
#define CONFIG_SDK_RTL8380 1
#undef  CONFIG_SDK_RTL8390
#undef  CONFIG_SDK_RTL9300
#undef  CONFIG_SDK_RTL9310

/*
 * Select your target PHYs chip
 */
#undef  CONFIG_SDK_RTL8208D
#undef  CONFIG_SDK_RTL8208G
#undef  CONFIG_SDK_RTL8208L
#undef  CONFIG_SDK_RTL8212B
#undef  CONFIG_SDK_RTL8214B
#undef  CONFIG_SDK_RTL8214FB
#define CONFIG_SDK_RTL8214FC 1
#undef  CONFIG_SDK_RTL8214C
#undef  CONFIG_SDK_RTL8214QF
#define CONFIG_SDK_RTL8218B 1
#define CONFIG_SDK_RTL8218D 1
#define CONFIG_SDK_RTL8218E 1
#undef  CONFIG_SDK_RTL8218FB
#undef  CONFIG_SDK_RTL8224QF
#undef  CONFIG_SDK_RTL8226
#undef  CONFIG_SDK_RTL8295R
#undef  CONFIG_SDK_RTL826X
#undef  CONFIG_SDK_RTL826XI
#undef  CONFIG_SDK_RTL825X
#undef  CONFIG_SDK_RTL825XI
#undef  CONFIG_SDK_RTL825XL
#undef  CONFIG_SDK_RTL8224
#undef  CONFIG_SDK_RTL826XB

/*
 * Select your target Peripheral chip
 */
#define CONFIG_SDK_RTL8231 1

/*
 * Select customer defined PHYs chip
 */
#undef  CONFIG_SDK_PHY_CUST1
#undef  CONFIG_SDK_PHY_CUST2
#undef  CONFIG_SDK_PHY_CUST3
#undef  CONFIG_SDK_PHY_CUST4
#undef  CONFIG_SDK_PHY_CUST5
#define CONFIG_SDK_EXPERIMENTAL_RTL8211FS 1

/*
 * CPU
 */
#undef  CONFIG_SDK_EXTERNAL_CPU
#undef  CONFIG_SDK_ENDIAN_LITTLE
#define CONFIG_UBOOT_SDK_SUPPORT 1

/*
 * SDK Driver
 */

/*
 * Rtcore Driver support
 */
#define CONFIG_SDK_DRIVER_RTCORE 1
#undef  CONFIG_SDK_DRIVER_RTCORE_IN_LINUX_KERNEL
#define CONFIG_SDK_DRIVER_NIC 1
#undef  CONFIG_SDK_DRIVER_EXTC_NIC
#undef  CONFIG_SDK_DRIVER_EXTC_PCI
#define CONFIG_SDK_DRIVER_GPIO 1
#define CONFIG_SDK_DRIVER_SPI 1
#define CONFIG_SDK_DRIVER_I2C 1
#undef  CONFIG_SDK_TC_DRV
#undef  CONFIG_SDK_DRIVER_WATCHDOG
#undef  CONFIG_SDK_UART1
#undef  CONFIG_SYS_DRIVER_JTAG_INTF_GPIO
#undef  CONFIG_SDK_DRIVER_NIC_R9310
#undef  CONFIG_SDK_DRIVER_NIC_R9300
#undef  CONFIG_SDK_DRIVER_NIC_R8390
#define CONFIG_SDK_DRIVER_NIC_R8380 1
#undef  CONFIG_SDK_DRIVER_I2C_R9310
#undef  CONFIG_SDK_DRIVER_I2C_R9300
#undef  CONFIG_SDK_DRIVER_I2C_R8390
#define CONFIG_SDK_DRIVER_I2C_R8380 1

/*
 * BSP Option
 */
#define CONFIG_SDK_BSP_FLASH 1
#define CONFIG_FLASH_LAYOUT_TYPE5 1
#define CONFIG_PSWITCH_SYSINFO 1
#define CONFIG_DUAL_IMAGE 1
#define CONFIG_SDK_SPI_DEV_NONE 1
#undef  CONFIG_SDK_SPI_DEV_1
#undef  CONFIG_SDK_SPI_DEV_2
#undef  CONFIG_SDK_SPI_DEV_3
#undef  CONFIG_SDK_SPI_DEV_4
#undef  CONFIG_SDK_SPI_DEV_5
#define CONFIG_SDK_BSP_SPI_NOR_BOOT 1
#undef  CONFIG_SDK_BSP_SPI_NAND_BOOT

/*
 * Misc Option
 */
#undef  CONFIG_SDK_EXPERIMENTAL
#undef  CONFIG_SDK_FPGA_PLATFORM
#undef  CONFIG_SDK_HW_PROFILE_PROBE_GPIO
#define CONFIG_SDK_HW_PROFILE_PROBE_UBOOT_ENV 1
#define CONFIG_SDK_OS_VERSION "Linux 3.18.24"
#define CONFIG_SDK_COMPILER_VERSION "GCC 4.8.5"
#define CONFIG_SDK_LIBC_VERSION ""
#define CONFIG_MISC_INIT_R 1

/*
 * Board
 */
#define CONFIG_UART0 1
#undef  CONFIG_UART1
#undef  CONFIG_INTERRUPT_SUPPORT
#define CONFIG_BOOT_SPI_NOR 1
#undef  CONFIG_BOOT_SPI_NAND

/*
 * Supported Commands
 */
#define CONFIG_CMDLINE_EDITING 1
#define CONFIG_CMD_FLASH 1
#define CONFIG_CMD_MEMORY 1
#define CONFIG_CMD_IMI 1
#undef  CONFIG_CMD_ENV
#undef  CONFIG_CMD_DUMPREGS
#define CONFIG_CMD_LOADB 1
#define CONFIG_CMD_LOADS 1
#define CONFIG_CMD_SAVEENV 1

/*
 * Menu Boot Options
 */
#define CONFIG_RTK_BOOT 1
#define CONFIG_TFTP_DOWNLOAD 1
#undef  CONFIG_SERIAL_DOWNLOAD
#undef  CONFIG_ICE_DOWNLOAD
#undef  CONFIG_STANDALONE_APP
#define CONFIG_CMD_NET 1
#define CONFIG_NET_MULTI 1
#define CONFIG_AUTOBOOT_PROMPT ""
#define CONFIG_CMD_RTK 1
#define CONFIG_CMD_RUN 1

/*
 * Networking
 */
#define CONFIG_ETHADDR 00:E0:4C:00:00:00
#define CONFIG_SN "0123456789"
#define CONFIG_MODNAME "RTL8382"
#define CONFIG_CMD_NET 1
#define CONFIG_CMD_PING 1
#define CONFIG_NET_MULTI 1
#define CONFIG_IPADDR 192.168.1.1
#define CONFIG_SERVERIP 192.168.1.254

/*
 * Miscellaneous
 */
#define CONFIG_SYS_TEXT_BASE 0x83F00000
#undef  BOARD_DEBUG_INFO
#define CONFIG_BOOTDELAY 1
#define CONFIG_BOOTMSG ""
#define CONFIG_BOOTCOMMAND "boota"
#define CONFIG_BOARDVERSION ""
#define CONFIG_BOARDMODEL "RTL8382M_INTPHY_8218B_8214FC_YFD"
#define CONFIG_BOOTARGS ""
#define CONFIG_POSTWORD ""
#undef  CONFIG_WARM_RESTART_CLOSE_PORT_8382
#define CONFIG_BAUDRATE 115200
#define CONFIG_LZMA 1

/*
 * System
 */

/*
 * System Configuration
 */
#undef  CONFIG_RTOS_TOOLCHAIN_USED
#define CONFIG_ENABLE_IH_MAGIC_NUMBER_CHK 1
#define CONFIG_IH_MAGIC_NUMBER 0x83800000
#define CONFIG_ENV_CRC_ERROR_SAVE_DEFAULT_ENV 1
#define CONFIG_CONS_INDEX 1
#undef  CONFIG_SERIAL_SOFTWARE_FIFO
#define CONFIG_SYS_SDRAM_BASE 0x80000000
#define CONFIG_MTD_PARTITIONS "n"
#define CONFIG_RTL8380 1
#define CONFIG_ENV_OVERWRITE 1
#define CONFIG_EXCEPTION_BASE 0xbf000000

/*
 * 838x Diagnosis Tools
 */
#define CONFIG_CMD_DRAM_TEST 1
#undef  CONFIG_CMD_FLASH_TEST
#undef  CONFIG_EEE
