#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
CFLAG += -D__GVRP__

#GVRPDIR should defined in caller Makefile which is relative path of caller.
GVRP_OBJ := \
	$(GVRPDIR)/proto_gvrp_sys.o \
	$(GVRPDIR)/proto_gvrp_gip.o \
	$(GVRPDIR)/proto_gvrp_gid.o \
	$(GVRPDIR)/proto_gvrp_gidtt.o \
	$(GVRPDIR)/proto_gvrp_gvd.o \
	$(GVRPDIR)/proto_gvrp_gvf.o \
	$(GVRPDIR)/proto_gvrp_vfdb.o \
	$(GVRPDIR)/proto_gvrp_gvr.o \
	$(GVRPDIR)/proto_gvrp.o

