#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
PSWITCH_DIR = $(CURDIR)/../..

# target
LIBNAME = libcmd.so
OBJS_y  = $(TARGET)/cmd_parser.o $(TARGET)/cmd_init.o $(TARGET)/cmd_conf.o

# Put after OBJS
include ../Makefile.lib
