#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#LACPDIR should defined in caller Makefile which is relative path of caller.
LACP_OBJ := $(LACPDIR)/proto_lacp.o
