/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef IEEE8021PAEMIB_H
#define IEEE8021PAEMIB_H

/* function declarations */
void init_ieee8021paeMIB(void);
FindVarMethod var_ieee8021paeMIB;
FindVarMethod var_dot1xPaePortTable;
FindVarMethod var_dot1xAuthConfigTable;
FindVarMethod var_dot1xAuthStatsTable;
FindVarMethod var_dot1xAuthDiagTable;
FindVarMethod var_dot1xAuthSessionStatsTable;
FindVarMethod var_dot1xSuppConfigTable;
FindVarMethod var_dot1xSuppStatsTable;
    WriteMethod write_dot1xPaeSystemAuthControl;
    WriteMethod write_dot1xPaePortInitialize;
    WriteMethod write_dot1xPaePortReauthenticate;
    WriteMethod write_dot1xAuthAdminControlledDirections;
    WriteMethod write_dot1xAuthAuthControlledPortControl;
    WriteMethod write_dot1xAuthQuietPeriod;
    WriteMethod write_dot1xAuthTxPeriod;
    WriteMethod write_dot1xAuthSuppTimeout;
    WriteMethod write_dot1xAuthServerTimeout;
    WriteMethod write_dot1xAuthMaxReq;
    WriteMethod write_dot1xAuthReAuthPeriod;
    WriteMethod write_dot1xAuthReAuthEnabled;
    WriteMethod write_dot1xAuthKeyTxEnabled;
    WriteMethod write_dot1xSuppHeldPeriod;
    WriteMethod write_dot1xSuppAuthPeriod;
    WriteMethod write_dot1xSuppStartPeriod;
    WriteMethod write_dot1xSuppMaxStart;
    WriteMethod write_dot1xSuppAccessCtrlWithAuth;

#endif /* IEEE8021PAEMIB_H */
