/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ieee8021paeMIB.h"
#include "mib_util.h"

#include <libsal/sal_authmgr.h>

/*
 * ieee8021paeMIB_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

#ifdef CONFIG_SYS_PROTO_AUTHMGR

oid ieee8021paeMIB_variables_oid[] = { 1,0,8802,1,1,1 };
static long long_ret;


#define DOT1XPAESYSTEMAUTHCONTROL       1
#define DOT1XPAEPORTNUMBER      2
#define DOT1XPAEPORTPROTOCOLVERSION     3
#define DOT1XPAEPORTCAPABILITIES        4
#define DOT1XPAEPORTINITIALIZE      5
#define DOT1XPAEPORTREAUTHENTICATE      6
#define DOT1XAUTHPAESTATE       7
#define DOT1XAUTHBACKENDAUTHSTATE       8
#define DOT1XAUTHADMINCONTROLLEDDIRECTIONS      9
#define DOT1XAUTHOPERCONTROLLEDDIRECTIONS       10
#define DOT1XAUTHAUTHCONTROLLEDPORTSTATUS       11
#define DOT1XAUTHAUTHCONTROLLEDPORTCONTROL      12
#define DOT1XAUTHQUIETPERIOD        13
#define DOT1XAUTHTXPERIOD       14
#define DOT1XAUTHSUPPTIMEOUT        15
#define DOT1XAUTHSERVERTIMEOUT      16
#define DOT1XAUTHMAXREQ     17
#define DOT1XAUTHREAUTHPERIOD       18
#define DOT1XAUTHREAUTHENABLED      19
#define DOT1XAUTHKEYTXENABLED       20
#define DOT1XAUTHEAPOLFRAMESRX      21
#define DOT1XAUTHEAPOLFRAMESTX      22
#define DOT1XAUTHEAPOLSTARTFRAMESRX     23
#define DOT1XAUTHEAPOLLOGOFFFRAMESRX        24
#define DOT1XAUTHEAPOLRESPIDFRAMESRX        25
#define DOT1XAUTHEAPOLRESPFRAMESRX      26
#define DOT1XAUTHEAPOLREQIDFRAMESTX     27
#define DOT1XAUTHEAPOLREQFRAMESTX       28
#define DOT1XAUTHINVALIDEAPOLFRAMESRX       29
#define DOT1XAUTHEAPLENGTHERRORFRAMESRX     30
#define DOT1XAUTHLASTEAPOLFRAMEVERSION      31
#define DOT1XAUTHLASTEAPOLFRAMESOURCE       32
#define DOT1XAUTHENTERSCONNECTING       33
#define DOT1XAUTHEAPLOGOFFSWHILECONNECTING      34
#define DOT1XAUTHENTERSAUTHENTICATING       35
#define DOT1XAUTHAUTHSUCCESSWHILEAUTHENTICATING     36
#define DOT1XAUTHAUTHTIMEOUTSWHILEAUTHENTICATING        37
#define DOT1XAUTHAUTHFAILWHILEAUTHENTICATING        38
#define DOT1XAUTHAUTHREAUTHSWHILEAUTHENTICATING     39
#define DOT1XAUTHAUTHEAPSTARTSWHILEAUTHENTICATING       40
#define DOT1XAUTHAUTHEAPLOGOFFWHILEAUTHENTICATING       41
#define DOT1XAUTHAUTHREAUTHSWHILEAUTHENTICATED      42
#define DOT1XAUTHAUTHEAPSTARTSWHILEAUTHENTICATED        43
#define DOT1XAUTHAUTHEAPLOGOFFWHILEAUTHENTICATED        44
#define DOT1XAUTHBACKENDRESPONSES       45
#define DOT1XAUTHBACKENDACCESSCHALLENGES        46
#define DOT1XAUTHBACKENDOTHERREQUESTSTOSUPPLICANT       47
#define DOT1XAUTHBACKENDNONNAKRESPONSESFROMSUPPLICANT       48
#define DOT1XAUTHBACKENDAUTHSUCCESSES       49
#define DOT1XAUTHBACKENDAUTHFAILS       50
#define DOT1XAUTHSESSIONOCTETSRX        51
#define DOT1XAUTHSESSIONOCTETSTX        52
#define DOT1XAUTHSESSIONFRAMESRX        53
#define DOT1XAUTHSESSIONFRAMESTX        54
#define DOT1XAUTHSESSIONID      55
#define DOT1XAUTHSESSIONAUTHENTICMETHOD     56
#define DOT1XAUTHSESSIONTIME        57
#define DOT1XAUTHSESSIONTERMINATECAUSE      58
#define DOT1XAUTHSESSIONUSERNAME        59
#define DOT1XSUPPPAESTATE       60
#define DOT1XSUPPHELDPERIOD     61
#define DOT1XSUPPAUTHPERIOD     62
#define DOT1XSUPPSTARTPERIOD        63
#define DOT1XSUPPMAXSTART       64
#define DOT1XSUPPCONTROLLEDPORTSTATUS       65
#define DOT1XSUPPACCESSCTRLWITHAUTH     66
#define DOT1XSUPPEAPOLFRAMESRX      67
#define DOT1XSUPPEAPOLFRAMESTX      68
#define DOT1XSUPPEAPOLSTARTFRAMESTX     69
#define DOT1XSUPPEAPOLLOGOFFFRAMESTX        70
#define DOT1XSUPPEAPOLRESPIDFRAMESTX        71
#define DOT1XSUPPEAPOLRESPFRAMESTX      72
#define DOT1XSUPPEAPOLREQIDFRAMESRX     73
#define DOT1XSUPPEAPOLREQFRAMESRX       74
#define DOT1XSUPPINVALIDEAPOLFRAMESRX       75
#define DOT1XSUPPEAPLENGTHERRORFRAMESRX     76
#define DOT1XSUPPLASTEAPOLFRAMEVERSION      77
#define DOT1XSUPPLASTEAPOLFRAMESOURCE       78


/*
 * variable4 ieee8021paeMIB_variables:
 *   this variable defines function callbacks and type return information
 *   for the ieee8021paeMIB mib section
 */

struct variable7 ieee8021paeMIB_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

{DOT1XPAESYSTEMAUTHCONTROL,  ASN_INTEGER,  RWRITE,  var_ieee8021paeMIB, 3,  { 1,1,1 }},


{DOT1XPAEPORTNUMBER,  ASN_INTEGER,  RONLY,   var_dot1xPaePortTable, 5,  { 1,1,2, 1, 1 }},

{DOT1XPAEPORTPROTOCOLVERSION,  ASN_UNSIGNED,  RONLY,   var_dot1xPaePortTable, 5,  { 1,1,2, 1, 2 }},

{DOT1XPAEPORTCAPABILITIES,  ASN_OCTET_STR,  RONLY,   var_dot1xPaePortTable, 5,  { 1,1,2, 1, 3 }},

{DOT1XPAEPORTINITIALIZE,  ASN_INTEGER,  RWRITE,  var_dot1xPaePortTable, 5,  { 1,1,2, 1, 4 }},

{DOT1XPAEPORTREAUTHENTICATE,  ASN_INTEGER,  RWRITE,  var_dot1xPaePortTable, 5,  { 1,1,2, 1, 5 }},

{DOT1XAUTHPAESTATE,  ASN_INTEGER,  RONLY,   var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 1 }},

{DOT1XAUTHBACKENDAUTHSTATE,  ASN_INTEGER,  RONLY,   var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 2 }},

{DOT1XAUTHADMINCONTROLLEDDIRECTIONS,  ASN_INTEGER,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 3 }},

{DOT1XAUTHOPERCONTROLLEDDIRECTIONS,  ASN_INTEGER,  RONLY,   var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 4 }},

{DOT1XAUTHAUTHCONTROLLEDPORTSTATUS,  ASN_INTEGER,  RONLY,   var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 5 }},

{DOT1XAUTHAUTHCONTROLLEDPORTCONTROL,  ASN_INTEGER,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 6 }},

{DOT1XAUTHQUIETPERIOD,  ASN_UNSIGNED,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 7 }},

{DOT1XAUTHTXPERIOD,  ASN_UNSIGNED,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 8 }},

{DOT1XAUTHSUPPTIMEOUT,  ASN_UNSIGNED,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 9 }},

{DOT1XAUTHSERVERTIMEOUT,  ASN_UNSIGNED,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 10 }},

{DOT1XAUTHMAXREQ,  ASN_UNSIGNED,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 11 }},

{DOT1XAUTHREAUTHPERIOD,  ASN_UNSIGNED,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 12 }},

{DOT1XAUTHREAUTHENABLED,  ASN_INTEGER,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 13 }},

{DOT1XAUTHKEYTXENABLED,  ASN_INTEGER,  RWRITE,  var_dot1xAuthConfigTable, 5,  { 1,2,1, 1, 14 }},

{DOT1XAUTHEAPOLFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 1 }},

{DOT1XAUTHEAPOLFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 2 }},

{DOT1XAUTHEAPOLSTARTFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 3 }},

{DOT1XAUTHEAPOLLOGOFFFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 4 }},

{DOT1XAUTHEAPOLRESPIDFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 5 }},

{DOT1XAUTHEAPOLRESPFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 6 }},

{DOT1XAUTHEAPOLREQIDFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 7 }},

{DOT1XAUTHEAPOLREQFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 8 }},

{DOT1XAUTHINVALIDEAPOLFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 9 }},

{DOT1XAUTHEAPLENGTHERRORFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 10 }},

{DOT1XAUTHLASTEAPOLFRAMEVERSION,  ASN_UNSIGNED,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 11 }},

{DOT1XAUTHLASTEAPOLFRAMESOURCE,  ASN_OCTET_STR,  RONLY,   var_dot1xAuthStatsTable, 5,  { 1,2,2, 1, 12 }},

{DOT1XAUTHENTERSCONNECTING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 1 }},

{DOT1XAUTHEAPLOGOFFSWHILECONNECTING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 2 }},

{DOT1XAUTHENTERSAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 3 }},

{DOT1XAUTHAUTHSUCCESSWHILEAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 4 }},

{DOT1XAUTHAUTHTIMEOUTSWHILEAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 5 }},

{DOT1XAUTHAUTHFAILWHILEAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 6 }},

{DOT1XAUTHAUTHREAUTHSWHILEAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 7 }},

{DOT1XAUTHAUTHEAPSTARTSWHILEAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 8 }},

{DOT1XAUTHAUTHEAPLOGOFFWHILEAUTHENTICATING,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 9 }},

{DOT1XAUTHAUTHREAUTHSWHILEAUTHENTICATED,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 10 }},

{DOT1XAUTHAUTHEAPSTARTSWHILEAUTHENTICATED,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 11 }},

{DOT1XAUTHAUTHEAPLOGOFFWHILEAUTHENTICATED,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 12 }},

{DOT1XAUTHBACKENDRESPONSES,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 13 }},

{DOT1XAUTHBACKENDACCESSCHALLENGES,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 14 }},

{DOT1XAUTHBACKENDOTHERREQUESTSTOSUPPLICANT,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 15 }},

{DOT1XAUTHBACKENDNONNAKRESPONSESFROMSUPPLICANT,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 16 }},

{DOT1XAUTHBACKENDAUTHSUCCESSES,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 17 }},

{DOT1XAUTHBACKENDAUTHFAILS,  ASN_COUNTER,  RONLY,   var_dot1xAuthDiagTable, 5,  { 1,2,3, 1, 18 }},

{DOT1XAUTHSESSIONOCTETSRX,  ASN_COUNTER64,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 1 }},

{DOT1XAUTHSESSIONOCTETSTX,  ASN_COUNTER64,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 2 }},

{DOT1XAUTHSESSIONFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 3 }},

{DOT1XAUTHSESSIONFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 4 }},

{DOT1XAUTHSESSIONID,  ASN_OCTET_STR,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 5 }},

{DOT1XAUTHSESSIONAUTHENTICMETHOD,  ASN_INTEGER,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 6 }},

{DOT1XAUTHSESSIONTIME,  ASN_TIMETICKS,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 7 }},

{DOT1XAUTHSESSIONTERMINATECAUSE,  ASN_INTEGER,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 8 }},

{DOT1XAUTHSESSIONUSERNAME,  ASN_OCTET_STR,  RONLY,   var_dot1xAuthSessionStatsTable, 5,  { 1,2,4, 1, 9 }},

{DOT1XSUPPPAESTATE,  ASN_INTEGER,  RONLY,   var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 1 }},

{DOT1XSUPPHELDPERIOD,  ASN_UNSIGNED,  RWRITE,  var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 2 }},

{DOT1XSUPPAUTHPERIOD,  ASN_UNSIGNED,  RWRITE,  var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 3 }},

{DOT1XSUPPSTARTPERIOD,  ASN_UNSIGNED,  RWRITE,  var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 4 }},

{DOT1XSUPPMAXSTART,  ASN_UNSIGNED,  RWRITE,  var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 5 }},

{DOT1XSUPPCONTROLLEDPORTSTATUS,  ASN_INTEGER,  RONLY,   var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 6 }},

{DOT1XSUPPACCESSCTRLWITHAUTH,  ASN_INTEGER,  RWRITE,  var_dot1xSuppConfigTable, 5,  { 1,3,1, 1, 7 }},

{DOT1XSUPPEAPOLFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 1 }},

{DOT1XSUPPEAPOLFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 2 }},

{DOT1XSUPPEAPOLSTARTFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 3 }},

{DOT1XSUPPEAPOLLOGOFFFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 4 }},

{DOT1XSUPPEAPOLRESPIDFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 5 }},

{DOT1XSUPPEAPOLRESPFRAMESTX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 6 }},

{DOT1XSUPPEAPOLREQIDFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 7 }},

{DOT1XSUPPEAPOLREQFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 8 }},

{DOT1XSUPPINVALIDEAPOLFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 9 }},

{DOT1XSUPPEAPLENGTHERRORFRAMESRX,  ASN_COUNTER,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 10 }},

{DOT1XSUPPLASTEAPOLFRAMEVERSION,  ASN_UNSIGNED,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 11 }},

{DOT1XSUPPLASTEAPOLFRAMESOURCE,  ASN_OCTET_STR,  RONLY,   var_dot1xSuppStatsTable, 5,  { 1,3,2, 1, 12 }},
};
/*    (L = length of the oidsuffix) */


/** Initializes the ieee8021paeMIB module */
void
init_ieee8021paeMIB(void)
{

    DEBUGMSGTL(("ieee8021paeMIB", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("ieee8021paeMIB", ieee8021paeMIB_variables, variable7,
               ieee8021paeMIB_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_ieee8021paeMIB():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_ieee8021paeMIB(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */
    sys_enable_t enable = DISABLED;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1XPAESYSTEMAUTHCONTROL:
        *write_method = write_dot1xPaeSystemAuthControl;
        sal_dot1x_enable_get(&enable);
        if (ENABLED == enable)
            long_ret = 1;
        else
            long_ret = 2;

        return (u_char*) &long_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_dot1xPaePortTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xPaePortTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
     long   index;
    uint32 status;
    static unsigned char u8_ret;


    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length != 12 )
            return NULL;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp,name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long_ret);

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {

    case DOT1XPAEPORTNUMBER:
        long_ret = LP2UP(index);
        return (u_char*) &long_ret;
    case DOT1XPAEPORTPROTOCOLVERSION:
        long_ret = 1;  /*dot1x support version 1*/
        return (u_char*) &long_ret;
    case DOT1XPAEPORTCAPABILITIES:
        *var_len = sizeof(char);
        u8_ret = 0x80;
        return (u_char*) &u8_ret;
    case DOT1XPAEPORTINITIALIZE:
        *write_method = write_dot1xPaePortInitialize;
        sal_dot1x_authPortCurState_get(index, &status);
        if (AUTH_INITIALIZE == status)
            long_ret = 1;
        else
            long_ret = 2;

        return (u_char*) &long_ret;
    case DOT1XPAEPORTREAUTHENTICATE:
        *write_method = write_dot1xPaePortReauthenticate;
        long_ret  = 2;    /* when read alway false */
        return (u_char*) &long_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1xAuthConfigTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xAuthConfigTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    unsigned long   index;
    uint32 status;
    sys_enable_t enable = DISABLED;
    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

     index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length != 12 )
            return NULL;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }


    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long_ret);

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1XAUTHPAESTATE:
        sal_dot1x_authPortCurState_get(index, &status);
        if (status < AUTH_RESTART)
            long_ret = status + 1;
        else if (status ==  AUTH_RESTART)
            long_ret = 0;
        else
            long_ret = status;
        return (u_char*) &long_ret;
    case DOT1XAUTHBACKENDAUTHSTATE:
        long_ret = 1; /*now not support get*/
        return (u_char*) &long_ret;

    case DOT1XAUTHADMINCONTROLLEDDIRECTIONS:
        *write_method = write_dot1xAuthAdminControlledDirections;
        //return (u_char*) &VAR;
        return NULL;
    case DOT1XAUTHOPERCONTROLLEDDIRECTIONS:
        //return (u_char*) &VAR;
        return NULL;

    case DOT1XAUTHAUTHCONTROLLEDPORTSTATUS:
        //return (u_char*) &VAR;
        return NULL;
    case DOT1XAUTHAUTHCONTROLLEDPORTCONTROL:
        *write_method = write_dot1xAuthAuthControlledPortControl;
        sal_dot1x_portMode_get(index , &status);
        long_ret = status;
        return (u_char*) &long_ret;
    case DOT1XAUTHQUIETPERIOD:
        *write_method = write_dot1xAuthQuietPeriod;
        return NULL;
        //return (u_char*) &VAR;
    case DOT1XAUTHTXPERIOD:
        *write_method = write_dot1xAuthTxPeriod;
        //VAR = VALUE;    /* XXX */
        //return (u_char*) &VAR;
        return NULL;
    case DOT1XAUTHSUPPTIMEOUT:
        *write_method = write_dot1xAuthSuppTimeout;
        //VAR = VALUE;    /* XXX */
        //return (u_char*) &VAR;
        return NULL;
    case DOT1XAUTHSERVERTIMEOUT:
        *write_method = write_dot1xAuthServerTimeout;
        //VAR = VALUE;    /* XXX */
        //return (u_char*) &VAR;
        return NULL;
    case DOT1XAUTHMAXREQ:
        *write_method = write_dot1xAuthMaxReq;
        //VAR = VALUE;    /* XXX */
        //return (u_char*) &VAR;
        return NULL;
    case DOT1XAUTHREAUTHPERIOD:
        *write_method = write_dot1xAuthReAuthPeriod;
        sal_dot1x_portReauthPeriod_get(index , &long_ret);
        return (u_char*) &long_ret;
    case DOT1XAUTHREAUTHENABLED:
        *write_method = write_dot1xAuthReAuthEnabled;
        sal_dot1x_portReauthEbl_get(index , &enable);
        if (ENABLED == enable)
            long_ret = 1;
        else
            long_ret = 2;

        return (u_char*) &long_ret;
    case DOT1XAUTHKEYTXENABLED:
        *write_method = write_dot1xAuthKeyTxEnabled;
        //return (u_char*) &VAR;
        return NULL;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1xAuthStatsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xAuthStatsTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1XAUTHEAPOLFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLSTARTFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLLOGOFFFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLRESPIDFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLRESPFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLREQIDFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPOLREQFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHINVALIDEAPOLFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPLENGTHERRORFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHLASTEAPOLFRAMEVERSION:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHLASTEAPOLFRAMESOURCE:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1xAuthDiagTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xAuthDiagTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1XAUTHENTERSCONNECTING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHEAPLOGOFFSWHILECONNECTING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHENTERSAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHSUCCESSWHILEAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHTIMEOUTSWHILEAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHFAILWHILEAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHREAUTHSWHILEAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHEAPSTARTSWHILEAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHEAPLOGOFFWHILEAUTHENTICATING:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHREAUTHSWHILEAUTHENTICATED:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHEAPSTARTSWHILEAUTHENTICATED:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHAUTHEAPLOGOFFWHILEAUTHENTICATED:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHBACKENDRESPONSES:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHBACKENDACCESSCHALLENGES:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHBACKENDOTHERREQUESTSTOSUPPLICANT:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHBACKENDNONNAKRESPONSESFROMSUPPLICANT:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHBACKENDAUTHSUCCESSES:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHBACKENDAUTHFAILS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1xAuthSessionStatsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xAuthSessionStatsTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1XAUTHSESSIONOCTETSRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONOCTETSTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONID:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONAUTHENTICMETHOD:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONTIME:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONTERMINATECAUSE:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XAUTHSESSIONUSERNAME:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1xSuppConfigTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xSuppConfigTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1XSUPPPAESTATE:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPHELDPERIOD:
        *write_method = write_dot1xSuppHeldPeriod;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPAUTHPERIOD:
        *write_method = write_dot1xSuppAuthPeriod;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPSTARTPERIOD:
        *write_method = write_dot1xSuppStartPeriod;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPMAXSTART:
        *write_method = write_dot1xSuppMaxStart;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPCONTROLLEDPORTSTATUS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPACCESSCTRLWITHAUTH:
        *write_method = write_dot1xSuppAccessCtrlWithAuth;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1xSuppStatsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_ieee8021paeMIB above.
 */
unsigned char *
var_dot1xSuppStatsTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1XSUPPEAPOLFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLSTARTFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLLOGOFFFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLRESPIDFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLRESPFRAMESTX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLREQIDFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPOLREQFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPINVALIDEAPOLFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPEAPLENGTHERRORFRAMESRX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPLASTEAPOLFRAMEVERSION:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1XSUPPLASTEAPOLFRAMESOURCE:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}



int
write_dot1xPaeSystemAuthControl(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    sys_enable_t enable = DISABLED;
    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          if (value < 1 || value > 2)
            return SNMP_ERR_WRONGVALUE;
          break;

        case RESERVE2:
          size  = var_val_len;
          if (value == 1)
            enable = ENABLED;
          if (SYS_ERR_OK != sal_dot1x_enable_set(enable))
            return SNMP_ERR_RESOURCEUNAVAILABLE;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_dot1xPaePortInitialize(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xPaePortReauthenticate(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthAdminControlledDirections(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthAuthControlledPortControl(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthQuietPeriod(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthTxPeriod(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthSuppTimeout(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthServerTimeout(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthMaxReq(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthReAuthPeriod(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthReAuthEnabled(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xAuthKeyTxEnabled(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xSuppHeldPeriod(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xSuppAuthPeriod(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xSuppStartPeriod(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xSuppMaxStart(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_UNSIGNED) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_UNSIGNED\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1xSuppAccessCtrlWithAuth(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to ieee8021paeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to ieee8021paeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

#endif

