/* This file is automatically generated by configure.  Do not modify by hand. */
#ifdef CONFIG_SYS_MIB_RMON
  if (should_init("rows")) init_rows();
  if (should_init("agutil")) init_agutil();
  if (should_init("statistics")) init_statistics();
  if (should_init("alarmTable")) init_alarm();
  if (should_init("history")) init_history();
  if (should_init("event")) init_event();
#endif


  #ifdef CONFIG_SYS_MIB_COMMUNITY
    #ifdef CONFIG_SYS_SNMPV3
      if (should_init("snmpCommunityMIB"))  init_snmpCommunityMIB();
    #endif
  #endif


  //if (should_init("dot3StatsTable")) init_dot3StatsTable();

  #ifdef CONFIG_SYS_MIB_SNMPV3_CONF
  if (should_init("snmpMPDStats_5_5")) init_snmpMPDStats_5_5();
  if (should_init("usmStats_5_5")) init_usmStats_5_5();
  if (should_init("snmpEngine")) init_snmpEngine();
  if (should_init("usmUser")) init_usmUser();
  if (should_init("snmpNotifyTable")) init_snmpNotifyTable();
  if (should_init("snmpNotifyFilterProfileTable")) init_snmpNotifyFilterProfileTable();
  if (should_init("snmpTargetAddrEntry")) init_snmpTargetAddrEntry();
  if (should_init("snmpTargetParamsEntry")) init_snmpTargetParamsEntry();
  if (should_init("snmpNotifyFilterTable")) init_snmpNotifyFilterTable();

  if (should_init("vacm_vars")) init_vacm_vars();
  if (should_init("vacm_context")) init_vacm_context();
	if (should_init("setSerialNo")) init_setSerialNo();
  #endif

 //  if (should_init("notification_log")) init_notification_log();
// (should_init("target_counters_5_5")) init_target_counters_5_5();

  if (should_init("interface")) init_interface();
  if (should_init("ifTable")) init_ifTable();
  if (should_init("ifXTable")) init_ifXTable();

  #ifdef CONFIG_SYS_MIBII
//  if (should_init("snmp_mib_5_5")) init_snmp_mib_5_5();
  if (should_init("system_mib")) init_system_mib();
  if (should_init("sysORTable")) init_sysORTable();
  if (should_init("at")) init_at();
  if (should_init("ip")) init_ip();
  if (should_init("tcp")) init_tcp();
  if (should_init("snmp_mib")) init_snmp_mib();
  if (should_init("icmp")) init_icmp();
  if (should_init("udp")) init_udp();
  if (should_init("ipv6")) init_ipv6();
  // (should_init("ip_scalars")) init_ip_scalars();
#endif


  //if (should_init("nsTransactionTable")) init_nsTransactionTable();
  //if (should_init("nsModuleTable")) init_nsModuleTable();
  //if (should_init("nsCache")) init_nsCache();
  //if (should_init("nsLogging")) init_nsLogging();
//if (should_init("nsVacmAccessTable")) init_nsVacmAccessTable();
  //if (should_init("override")) init_override();
 // if (should_init("var_route")) init_var_route();

  //if (should_init("tcpTable")) init_tcpTable();
  //if (should_init("udpTable")) init_udpTable();


  //if (should_init("ipAddressTable")) init_ipAddressTable();
  //if (should_init("ipAddressPrefixTable")) init_ipAddressPrefixTable();
//  if (should_init("ipDefaultRouterTable")) init_ipDefaultRouterTable();
 // if (should_init("inetNetToMediaTable")) init_inetNetToMediaTable();
//  if (should_init("ipSystemStatsTable")) init_ipSystemStatsTable();
 // if (should_init("ipv6ScopeZoneIndexTable")) init_ipv6ScopeZoneIndexTable();
  //should_init("ipIfStatsTable")) init_ipIfStatsTable();
 // if (should_init("ipCidrRouteTable")) init_ipCidrRouteTable();
  //if (should_init("inetCidrRouteTable")) init_inetCidrRouteTable();
  //if (should_init("tcpConnectionTable")) init_tcpConnectionTable();
  //if (should_init("tcpListenerTable")) init_tcpListenerTable();
  //if (should_init("udpEndpointTable")) init_udpEndpointTable();


  #ifdef CONFIG_SYS_MIB_ETHERLIKE
  if (should_init("dot3_mib")) init_dot3();
#endif

#ifdef CONFIG_SYS_MIB_BRIDGE
  if (should_init("dot1dBridge")) init_dot1dBridge();
  #ifdef CONFIG_SYS_MIB_EXT_BRIDGE
  if (should_init("pBridgeMIB")) init_pBridgeMIB();
  if (should_init("qBridgeMIB")) init_qBridgeMIB();
#endif
#endif

#ifdef CONFIG_SYS_MIB_ENTITY
  if (should_init("entityMIB")) init_entityMIB();
#endif
 // if(should_init("syspswitch")) init_syspswitch();

#ifdef CONFIG_SYS_PROTO_AUTHMGR
#ifdef CONFIG_SYS_MIB_DOT1X
if(should_init("ieee8021paeMIB")) init_ieee8021paeMIB();
#endif
#endif
#ifdef CONFIG_SYS_MIB_SNMP_LLDP_CONF
    if (should_init("lldpLocPortTable")) init_lldpLocPortTable();
    if (should_init("initlldpRemTable")) init_lldpRemTable();
    if (should_init("lldpLocalSystemData")) init_lldpLocalSystemData();
    if (should_init("lldpConfiguration")) init_lldpConfiguration();
    if (should_init("lldpPortConfigTable")) init_lldpPortConfigTable();
    if (should_init("lldpStatistics")) init_lldpStatistics();
    if (should_init("lldpStatsRxPortTable")) init_lldpStatsRxPortTable();
    if (should_init("lldpStatsTxPortTable")) init_lldpStatsTxPortTable();
#endif

