/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "dot3.h"
#include "mib_util.h"

#include <sys/time.h>
#include <unistd.h>
//#include "util_funcs.h"

/*
  * Implementation headers
  */
//#include "agutil_api.h"
//#include "row_api.h"

/*
 * RTK private header
 */
#include <common/sys_error.h>
#include <common/sys_def.h>
#include <common/sys_portmask.h>
#include <common/sys_util.h>


#include <libsal/sal_trunk.h>
#include <libsal/sal_util.h>
#include <libsal/sal_mib.h>
#include <libsal/sal_port.h>


#define DOT3_TABLE_SIZE     SYS_LOGIC_PORT_NUM

#define DOT3STATSINDEX      1
#define DOT3STATSALIGNMENTERRORS        2
#define DOT3STATSFCSERRORS      3
#define DOT3STATSSINGLECOLLISIONFRAMES      4
#define DOT3STATSMULTIPLECOLLISIONFRAMES        5
#define DOT3STATSSQETESTERRORS      6
#define DOT3STATSDEFERREDTRANSMISSIONS      7
#define DOT3STATSLATECOLLISIONS     8
#define DOT3STATSEXCESSIVECOLLISIONS        9
#define DOT3STATSINTERNALMACTRANSMITERRORS      10
#define DOT3STATSCARRIERSENSEERRORS     11
#define DOT3STATSFRAMETOOLONGS      12
#define DOT3STATSINTERNALMACRECEIVEERRORS       13
#define DOT3STATSETHERCHIPSET       14
#define DOT3STATSSYMBOLERRORS       15
#define DOT3STATSDUPLEXSTATUS       16
#define DOT3STATSRATECONTROLABILITY     17
#define DOT3STATSRATECONTROLSTATUS      18
#define DOT3COLLCOUNT       19
#define DOT3COLLFREQUENCIES     20
#define DOT3CONTROLFUNCTIONSSUPPORTED       21
#define DOT3CONTROLINUNKNOWNOPCODES     22
#define DOT3HCCONTROLINUNKNOWNOPCODES       23
#define DOT3PAUSEADMINMODE      24
#define DOT3PAUSEOPERMODE       25
#define DOT3INPAUSEFRAMES       26
#define DOT3OUTPAUSEFRAMES      27
#define DOT3HCINPAUSEFRAMES     28
#define DOT3HCOUTPAUSEFRAMES        29
#define DOT3HCSTATSALIGNMENTERRORS      30
#define DOT3HCSTATSFCSERRORS        31
#define DOT3HCSTATSINTERNALMACTRANSMITERRORS        32
#define DOT3HCSTATSFRAMETOOLONGS        33
#define DOT3HCSTATSINTERNALMACRECEIVEERRORS     34
#define DOT3HCSTATSSYMBOLERRORS     35


#define DOT3STATSINDEX_MIN                      1
#define DOT3STATSINDEX_MAX                      17
#define DOT3STATSOIDLEN_MAX                     12

/*
 * dot3_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid dot3_variables_oid[] = { 1,3,6,1,2,1,10,7 };

/*
 * variable4 dot3_variables:
 *   this variable defines function callbacks and type return information
 *   for the dot3 mib section
 */

struct variable4 dot3_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

{DOT3STATSINDEX,  ASN_INTEGER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 1 }},

{DOT3STATSALIGNMENTERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 2 }},

{DOT3STATSFCSERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 3 }},

{DOT3STATSSINGLECOLLISIONFRAMES,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 4 }},

{DOT3STATSMULTIPLECOLLISIONFRAMES,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 5 }},

{DOT3STATSSQETESTERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 6 }},

{DOT3STATSDEFERREDTRANSMISSIONS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 7 }},

{DOT3STATSLATECOLLISIONS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 8 }},

{DOT3STATSEXCESSIVECOLLISIONS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 9 }},

{DOT3STATSINTERNALMACTRANSMITERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 10 }},

{DOT3STATSCARRIERSENSEERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 11 }},

{DOT3STATSFRAMETOOLONGS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 13 }},

{DOT3STATSINTERNALMACRECEIVEERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 16 }},

{DOT3STATSETHERCHIPSET,  ASN_OBJECT_ID,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 17 }},

{DOT3STATSSYMBOLERRORS,  ASN_COUNTER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 18 }},

{DOT3STATSDUPLEXSTATUS,  ASN_INTEGER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 19 }},

{DOT3STATSRATECONTROLABILITY,  ASN_INTEGER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 20 }},

{DOT3STATSRATECONTROLSTATUS,  ASN_INTEGER,  RONLY,   var_dot3StatsTable, 3,  { 2, 1, 21 }},

{DOT3COLLCOUNT,  ASN_INTEGER,  RONLY,   var_dot3CollTable, 3,  { 5, 1, 2 }},

{DOT3COLLFREQUENCIES,  ASN_COUNTER,  RONLY,   var_dot3CollTable, 3,  { 5, 1, 3 }},

{DOT3CONTROLFUNCTIONSSUPPORTED,  ASN_OCTET_STR,  RONLY,   var_dot3ControlTable, 3,  { 9, 1, 1 }},

{DOT3CONTROLINUNKNOWNOPCODES,  ASN_COUNTER,  RONLY,   var_dot3ControlTable, 3,  { 9, 1, 2 }},

{DOT3HCCONTROLINUNKNOWNOPCODES,  ASN_COUNTER64,  RONLY,   var_dot3ControlTable, 3,  { 9, 1, 3 }},

{DOT3PAUSEADMINMODE,  ASN_INTEGER,  RWRITE,  var_dot3PauseTable, 3,  { 10, 1, 1 }},

{DOT3PAUSEOPERMODE,  ASN_INTEGER,  RONLY,   var_dot3PauseTable, 3,  { 10, 1, 2 }},

{DOT3INPAUSEFRAMES,  ASN_COUNTER,  RONLY,   var_dot3PauseTable, 3,  { 10, 1, 3 }},

{DOT3OUTPAUSEFRAMES,  ASN_COUNTER,  RONLY,   var_dot3PauseTable, 3,  { 10, 1, 4 }},

{DOT3HCINPAUSEFRAMES,  ASN_COUNTER64,  RONLY,   var_dot3PauseTable, 3,  { 10, 1, 5 }},

{DOT3HCOUTPAUSEFRAMES,  ASN_COUNTER64,  RONLY,   var_dot3PauseTable, 3,  { 10, 1, 6 }},

{DOT3HCSTATSALIGNMENTERRORS,  ASN_COUNTER64,  RONLY,   var_dot3HCStatsTable, 3,  { 11, 1, 1 }},

{DOT3HCSTATSFCSERRORS,  ASN_COUNTER64,  RONLY,   var_dot3HCStatsTable, 3,  { 11, 1, 2 }},

{DOT3HCSTATSINTERNALMACTRANSMITERRORS,  ASN_COUNTER64,  RONLY,   var_dot3HCStatsTable, 3,  { 11, 1, 3 }},

{DOT3HCSTATSFRAMETOOLONGS,  ASN_COUNTER64,  RONLY,   var_dot3HCStatsTable, 3,  { 11, 1, 4 }},

{DOT3HCSTATSINTERNALMACRECEIVEERRORS,  ASN_COUNTER64,  RONLY,   var_dot3HCStatsTable, 3,  { 11, 1, 5 }},

{DOT3HCSTATSSYMBOLERRORS,  ASN_COUNTER64,  RONLY,   var_dot3HCStatsTable, 3,  { 11, 1, 6 }},
};
/*    (L = length of the oidsuffix) */


/** Initializes the dot3 module */
void
init_dot3(void)
{

    DEBUGMSGTL(("dot3_mib", "Initializing\n"));

/*    snmp_log(LOG_INFO,"run init_dot3 begin !\n"); */

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("dot3_mib", dot3_variables, variable4,
               dot3_variables_oid);
    /* place any other initialization junk you need here */
}

/*
 * var_dot3():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_dot3(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_dot3StatsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot3 above.
 */
unsigned char *
var_dot3StatsTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static unsigned long     long_return;
    long   index = 0;
    uint64 cntr64 = 0;
    sys_port_speedDuplex_t speedDuplex;
    sys_port_linkStatus_t linkStatus;

    *write_method = NULL;
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
        return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length != 12 )
            return NULL;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));


    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
   /*
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT3_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;
    */
    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT3STATSINDEX:
        long_return = LP2UP(index);
        return (u_char *) & long_return;
    case DOT3STATSALIGNMENTERRORS:
        sal_mib_dot3_statsAlignmentErrors_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSFCSERRORS:
        sal_mib_dot3StatsFCSErrors_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSSINGLECOLLISIONFRAMES:
        sal_mib_dot3StatsSingleCollisionFrames_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSMULTIPLECOLLISIONFRAMES:
        sal_mib_dot3StatsMultipleCollisionFrames_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSSQETESTERRORS:
        long_return = 0;
        return (u_char *) & long_return;
    case DOT3STATSDEFERREDTRANSMISSIONS:
        sal_mib_dot3StatsDeferredTransmissions_get(index , &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSLATECOLLISIONS:
        sal_mib_dot3StatsLateCollisions_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSEXCESSIVECOLLISIONS:
        sal_mib_dot3StatsExcessiveCollisions_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSINTERNALMACTRANSMITERRORS:
        sal_mib_ifOutDiscards_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSCARRIERSENSEERRORS:
       /* sal_mib_ifOutDiscards_get(index - 1, &cntr64);*/
        long_return = 0;  /*un-support*/
        return (u_char *) & long_return;
    case DOT3STATSFRAMETOOLONGS:
        sal_mib_dot3StatsFrameTooLongs_get(index, &cntr64);
        //sal_mib_dot1d_tpHCPortInDiscards_get(index - 1, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSINTERNALMACRECEIVEERRORS:
        sal_mib_dot3StatsInternalMacReceiveErrors_get(index , &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
/*
    case DOT3STATSETHERCHIPSET:
        return (u_char*) &VAR;
*/
    case DOT3STATSSYMBOLERRORS:
        sal_mib_dot3StatsSymbolErrors_get(index, &cntr64);
        long_return = (unsigned long) cntr64;
        return (u_char *) & long_return;
    case DOT3STATSDUPLEXSTATUS:
        sal_port_linkStatus_get(index, &linkStatus);
        if (PORT_LINKDOWN ==  linkStatus)
            long_return =  1;
        else
        {
            sal_port_speedDuplex_get(index , &speedDuplex);
            if(PORT_HALF_DUPLEX == speedDuplex.duplex)
                long_return =  2 ;  /*snmp half duplex*/
            else if(PORT_FULL_DUPLEX == speedDuplex.duplex)
                long_return =  3 ;  /*snmp Full duplex*/
            else
                long_return =  1 ; /*unknow duplex*/
        }

        return (u_char*) &long_return;
/*
    case DOT3STATSRATECONTROLABILITY:
        VAR = VALUE;
        return (u_char*) &VAR;
    case DOT3STATSRATECONTROLSTATUS:
        VAR = VALUE;
        return (u_char*) &VAR;
*/

    default:
      ERROR_MSG("");
    }

    return NULL;
}
/*
 * var_dot3CollTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot3 above.
 */
unsigned char *
var_dot3CollTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
#if 0
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT3_TABLE_SIZE)
                                                == MATCH_FAILED )
#endif
    if (AGUTIL_advance_index_name(vp, name, length, exact) != 0)
        return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT3COLLCOUNT:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT3COLLFREQUENCIES:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot3ControlTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot3 above.
 */
unsigned char *
var_dot3ControlTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static uint64 llong_ret;
    static unsigned char  uchar_ret;
    long   index = 0;
    uint64 cntr64 = 0;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    *write_method = NULL;
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
        return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length !=  DOT3STATSOIDLEN_MAX)
            return NULL;

    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));


    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {

    case DOT3CONTROLFUNCTIONSSUPPORTED:
        uchar_ret = 128;     /*0x80*/
        *var_len = 1;
        return (u_char*) &uchar_ret;
    case DOT3CONTROLINUNKNOWNOPCODES:
        sal_mib_dot3ControlInUnknownOpcodes_get(index, &cntr64);
        long_ret = (unsigned long) cntr64;
        return (u_char*) &long_ret;
    case DOT3HCCONTROLINUNKNOWNOPCODES:
        *var_len = sizeof(cntr64);
        sal_mib_dot3ControlInUnknownOpcodes_get(index, &cntr64);
        llong_ret = cntr64;
        return (u_char*) &llong_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot3PauseTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot3 above.
 */
unsigned char *
var_dot3PauseTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static u_long ulong_ret;
    unsigned long   index;
    sys_enable_t adminEnable, operEnable, operTxEnable, operRxEnable;
    uint64 cntr64 = 0;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    *write_method = NULL;
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
        return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length !=  DOT3STATSOIDLEN_MAX)
            return NULL;


    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));


    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT3PAUSEADMINMODE:
        *write_method = write_dot3PauseAdminMode;
        sal_port_flowCtrl_get(index, &adminEnable, &operEnable);
        if (ENABLED == adminEnable)
            ulong_ret = 2;
        else
            ulong_ret = 1;
        return (u_char*) &ulong_ret;
    case DOT3PAUSEOPERMODE:
        sal_port_flowCtrlStatus_get(index, &operTxEnable, &operRxEnable);
        if (ENABLED == operTxEnable && ENABLED == operRxEnable )
            ulong_ret = 4;
        else if (DISABLED == operTxEnable && ENABLED == operRxEnable )
            ulong_ret = 3;
        else if (ENABLED == operTxEnable && DISABLED == operRxEnable )
            ulong_ret = 2;
        else
            ulong_ret = 1;
        return (u_char*) &ulong_ret;
    case DOT3INPAUSEFRAMES:
        *var_len = sizeof(long);
        sal_mib_dot3InPauseFrames_get(index, &cntr64);
        ulong_ret = (u_long)cntr64;
        return (u_char*) &ulong_ret;
    case DOT3OUTPAUSEFRAMES:
        *var_len = sizeof(long);
        sal_mib_dot3OutPauseFrames_get(index, &cntr64);
        ulong_ret = (u_long)cntr64;
        return (u_char*) &ulong_ret;
    case DOT3HCINPAUSEFRAMES:
        *var_len = sizeof(uint64);
        sal_mib_dot3InPauseFrames_get(index, &cntr64);
        ulong_ret = (u_long)cntr64;
        return (u_char*) &ulong_ret;
    case DOT3HCOUTPAUSEFRAMES:
        *var_len = sizeof(uint64);
        sal_mib_dot3OutPauseFrames_get(index, &cntr64);
        ulong_ret = (u_long)cntr64;
        return (u_char*) &ulong_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot3HCStatsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot3 above.
 */
unsigned char *
var_dot3HCStatsTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;


    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT3_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT3HCSTATSALIGNMENTERRORS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT3HCSTATSFCSERRORS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT3HCSTATSINTERNALMACTRANSMITERRORS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT3HCSTATSFRAMETOOLONGS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT3HCSTATSINTERNALMACRECEIVEERRORS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT3HCSTATSSYMBOLERRORS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}


int
write_dot3PauseAdminMode(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    long index;
    sys_enable_t enable = ENABLED;

    value = * (long *) var_val;
    index = UP2LP(name[name_len-1]);

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot3 not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot3: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

        if (value < 1  || value > 2)
            return SNMP_ERR_WRONGVALUE;

        if (IS_LOGIC_PORT_INVALID(index))
            return SNMP_ERR_NOSUCHNAME;

          break;

        case RESERVE2:
            if (value == 1)
                enable = DISABLED;
            SYS_SNMP_ERR_CHK(sal_port_flowCtrl_set(index, enable), SNMP_ERR_RESOURCEUNAVAILABLE);

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:

             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

