/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef DOT3_H
#define DOT3_H

/* function declarations */
void init_dot3(void);
FindVarMethod var_dot3;
FindVarMethod var_dot3StatsTable;
FindVarMethod var_dot3CollTable;
FindVarMethod var_dot3ControlTable;
FindVarMethod var_dot3PauseTable;
FindVarMethod var_dot3HCStatsTable;
    WriteMethod write_dot3PauseAdminMode;

#endif /* DOT3_H */
