#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#STPDIR should defined in caller Makefile which is relative path of caller.
STP_OBJ := \
	$(STPDIR)/proto_stp.o \
	$(STPDIR)/proto_stp_mstp_digest.o \
	$(STPDIR)/proto_stp_mstp.o
