#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#VOICEVLANDIR should defined in caller Makefile which is relative path of caller.
VOICEVLAN_OBJ := $(VOICEVLANDIR)/proto_voice_vlan.o
