#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#MACVLANDIR should defined in caller Makefile which is relative path of caller.
MACVLAN_OBJ := $(MACVLANDIR)/proto_macvlan.o
