/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef ENTITY_H
#define ENTITY_H

#include <libsal/sal_sys.h>

#include <libfds/fds_export.h>

#define ENTITY_DESCR_LEN 64
#define ENTITY_PHY_DESCR_PORT_NUM 5
#define ENTITY_START_INDEX  68424769
#define ENTITY_PHY_CLASS      10
#define ENTITY_PHY_DESCR_INDEX  67108992  /*second*/
#define ENTITY_PHY_FRU        2                        /*false*/

#define PHY_DESCR  "24-port 10/100 Managed Switch"
#define PHY_NAME   "MS200X-24"
#define PHY_STACK_NAME   "Stack"
#define PHY_SLOT_NAME   "Slot"
#define PHY_SERIAL_NUM   "GT_98DX1005"

/*define the reversion */
#define ENTITY_MFG_NAME   DFLT_SYS_MANUFACTURER
#define ENTITY_PHY_CHIP_DESC  "switch processor"


/* function declarations */
typedef struct physicall_entry_s{
    uint32  index;
    char     descr[ENTITY_DESCR_LEN];
    uint32  containedIn;
    uint32  phyclass;
    int32    parentRelPos;
    char     physicalName[ENTITY_DESCR_LEN];

    struct physicall_entry_s *next;
}physicall_entry_t;


/*entPhysicalTable*/
extern int32 entity_physical_creatEntry(physicall_entry_t *pEntry);
extern void entity_physical_scanAccessInit(void);
extern physicall_entry_t *entity_physical_scanFirst(void);
extern physicall_entry_t *entity_physical_scanAccessNext(void);
extern physicall_entry_t *entity_getPhysicalEntry(uint32 index);
extern void entity_physical_data_init(void);

/*entAliasMappingTable*/

extern void entity_aliasMap_scanAccessInit(void);
extern physicall_entry_t *entity_aliasMap_scanFirst(void);
extern physicall_entry_t *entity_aliasMap_scanAccessNext(void);


/*entPhysicalContainsTable*/
extern void entity_contains_scanAccessInit(void);
extern physicall_entry_t *entity_contains_scanFirst(void);
extern physicall_entry_t *entity_contains_scanAccessNext(void);


#endif /* ENTITY_H */

