/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "entityMIB.h"
#include "entity.h"

/*
 * entityMIB_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid entityMIB_variables_oid[] = { 1,3,6,1,2,1,47 };
u_long entLastChgTime = 0;

static u_long long_ret;

#define ENTITY_TABLE_SIZE  1024

#define ENTLASTCHANGETIME       1
#define ENTPHYSICALINDEX        2
#define ENTPHYSICALDESCR        3
#define ENTPHYSICALVENDORTYPE       4
#define ENTPHYSICALCONTAINEDIN      5
#define ENTPHYSICALCLASS        6
#define ENTPHYSICALPARENTRELPOS     7
#define ENTPHYSICALNAME     8
#define ENTPHYSICALHARDWAREREV      9
#define ENTPHYSICALFIRMWAREREV      10
#define ENTPHYSICALSOFTWAREREV      11
#define ENTPHYSICALSERIALNUM        12
#define ENTPHYSICALMFGNAME      13
#define ENTPHYSICALMODELNAME        14
#define ENTPHYSICALALIAS        15
#define ENTPHYSICALASSETID      16
#define ENTPHYSICALISFRU        17
#define ENTLOGICALINDEX     18
#define ENTLOGICALDESCR     19
#define ENTLOGICALTYPE      20
#define ENTLOGICALCOMMUNITY     21
#define ENTLOGICALTADDRESS      22
#define ENTLOGICALTDOMAIN       23
#define ENTLOGICALCONTEXTENGINEID       24
#define ENTLOGICALCONTEXTNAME       25
#define ENTLPPHYSICALINDEX      26
#define ENTALIASLOGICALINDEXORZERO      27
#define ENTALIASMAPPINGIDENTIFIER       28
#define ENTPHYSICALCHILDINDEX       29

/*
 * variable4 entityMIB_variables:
 *   this variable defines function callbacks and type return information
 *   for the entityMIB mib section
 */

struct variable7 entityMIB_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */
{ENTLASTCHANGETIME,  ASN_TIMETICKS,  RONLY ,  var_entityMIB, 3,  { 1,4,1 }},

{ENTPHYSICALINDEX,  ASN_INTEGER,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 1 }},

{ENTPHYSICALDESCR,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 2 }},

{ENTPHYSICALVENDORTYPE,  ASN_OBJECT_ID,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 3 }},

{ENTPHYSICALCONTAINEDIN,  ASN_INTEGER,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 4 }},

{ENTPHYSICALCLASS,  ASN_INTEGER,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 5 }},

{ENTPHYSICALPARENTRELPOS,  ASN_INTEGER,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 6 }},

{ENTPHYSICALNAME,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 7 }},

{ENTPHYSICALHARDWAREREV,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 8 }},

{ENTPHYSICALFIRMWAREREV,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 9 }},

{ENTPHYSICALSOFTWAREREV,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 10 }},

{ENTPHYSICALSERIALNUM,  ASN_OCTET_STR,  RWRITE,  var_entPhysicalTable, 5,  { 1,1,1, 1, 11 }},

{ENTPHYSICALMFGNAME,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 12 }},

{ENTPHYSICALMODELNAME,  ASN_OCTET_STR,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 13 }},

{ENTPHYSICALALIAS,  ASN_OCTET_STR,  RWRITE,  var_entPhysicalTable, 5,  { 1,1,1, 1, 14 }},

{ENTPHYSICALASSETID,  ASN_OCTET_STR,  RWRITE,  var_entPhysicalTable, 5,  { 1,1,1, 1, 15 }},

{ENTPHYSICALISFRU,  ASN_INTEGER,  RONLY,   var_entPhysicalTable, 5,  { 1,1,1, 1, 16 }},

{ENTLOGICALINDEX,  ASN_INTEGER,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 1 }},

{ENTLOGICALDESCR,  ASN_OCTET_STR,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 2 }},

{ENTLOGICALTYPE,  ASN_OBJECT_ID,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 3 }},

{ENTLOGICALCOMMUNITY,  ASN_OCTET_STR,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 4 }},

{ENTLOGICALTADDRESS,  ASN_OCTET_STR,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 5 }},

{ENTLOGICALTDOMAIN,  ASN_OBJECT_ID,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 6 }},

{ENTLOGICALCONTEXTENGINEID,  ASN_OCTET_STR,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 7 }},

{ENTLOGICALCONTEXTNAME,  ASN_OCTET_STR,  RONLY,   var_entLogicalTable, 5,  { 1,2,1, 1, 8 }},

{ENTLPPHYSICALINDEX,  ASN_INTEGER,  RONLY,   var_entLPMappingTable, 5,  { 1,3,1, 1, 1 }},

{ENTALIASLOGICALINDEXORZERO,  ASN_INTEGER,  RONLY,   var_entAliasMappingTable, 5,  { 1,3,2, 1, 1 }},

{ENTALIASMAPPINGIDENTIFIER,  ASN_OBJECT_ID,  RONLY,   var_entAliasMappingTable, 5,  { 1,3,2, 1, 2 }},

{ENTPHYSICALCHILDINDEX,  ASN_INTEGER,  RONLY,   var_entPhysicalContainsTable, 5,  { 1,3,3, 1, 1 }},
};
/*    (L = length of the oidsuffix) */


/** Initializes the entityMIB module */
void
init_entityMIB(void)
{

    DEBUGMSGTL(("entityMIB", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("entityMIB", entityMIB_variables, variable7,
               entityMIB_variables_oid);

    entity_physical_data_init();
    entLastChgTime = netsnmp_get_agent_uptime();

    /* place any other initialization junk you need here */
}

/*
 * var_entityMIB():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_entityMIB(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */


    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */

    *var_len = sizeof(u_long);

    switch(vp->magic) {

    case ENTLASTCHANGETIME:
        return (u_char*)&entLastChgTime;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_entPhysicalTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_entityMIB above.
 */
unsigned char *
var_entPhysicalTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    physicall_entry_t *pPhyEntry;
    uint32 index;
    char sysModel[CAPA_SYS_NAME_LEN + 1];
    char loaderVer[SYS_BUF16_LEN];
    char loaderDate[SYS_BUF32_LEN];

    static char entityStr[SYS_BUF128_LEN];

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */

    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
       return NULL;
    }

    if (exact) {
        if (*length != 13)
            return NULL;

        index = name[12];

        pPhyEntry = entity_getPhysicalEntry(index);
    } else{

        if (12 == *length)
        {
            pPhyEntry  = entity_physical_scanFirst();
        }
        else
        {
          index = name[12];
          entity_physical_scanAccessInit();
          while((pPhyEntry = entity_physical_scanAccessNext()) != NULL){
            if (index == pPhyEntry->index)
             {
                 pPhyEntry = entity_physical_scanAccessNext();
                 break;
             }
           }

         }

        if (pPhyEntry) {
            name[12] = pPhyEntry->index;
            *length = 13;
        }
    }

    if (pPhyEntry == NULL) {
        return NULL;
    }

    *var_len = sizeof(long_ret);
    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {

    case ENTPHYSICALINDEX:
        #if 0
        long_ret = pPhyEntry->index;
        return (u_char*) &long_ret;
        #endif
        return NULL;
    case ENTPHYSICALDESCR:
        *var_len = osal_strlen(pPhyEntry->descr);
        return (u_char*)pPhyEntry->descr;
    case ENTPHYSICALVENDORTYPE:
        *var_len = 0;
        long_ret = 0;
        return (u_char*) &long_ret;
    case ENTPHYSICALCONTAINEDIN:
        long_ret = pPhyEntry->containedIn;
        return (u_char*) &long_ret;
    case ENTPHYSICALCLASS:
        long_ret = pPhyEntry->phyclass;
        return (u_char*) &long_ret;
    case ENTPHYSICALPARENTRELPOS:
        long_ret = pPhyEntry->parentRelPos;
        return (u_char*) &long_ret;
    case ENTPHYSICALNAME:
        *var_len = osal_strlen(pPhyEntry->physicalName);
        return (u_char*)pPhyEntry->physicalName;
    case ENTPHYSICALHARDWAREREV:
        osal_memset(&entityStr,0,sizeof(entityStr));
        if (ENTITY_PHY_DESCR_INDEX == pPhyEntry->index)
        {
            sal_sys_sysinfoVar_get(DFLT_SYS_HWVER_VAR, entityStr);
        }
        *var_len = osal_strlen(entityStr);
        return (u_char*)entityStr;
    case ENTPHYSICALFIRMWAREREV:
       osal_memset(&entityStr,0,sizeof(entityStr));
        if (ENTITY_PHY_DESCR_INDEX == pPhyEntry->index)
        {
            osal_memset(loaderVer,0,sizeof(loaderVer));
            sal_sys_loaderInfo_get(loaderVer, loaderDate);
            osal_strcpy(entityStr, loaderVer);
        }
        *var_len = osal_strlen(entityStr);
        return (u_char*)entityStr;
    case ENTPHYSICALSOFTWAREREV:
        osal_memset(&entityStr,0,sizeof(entityStr));
        if (ENTITY_PHY_DESCR_INDEX == pPhyEntry->index)
        {
            osal_strcpy(entityStr, DFLT_SYS_VER);
        }
        *var_len = osal_strlen(entityStr);
        return (u_char*)entityStr;
    case ENTPHYSICALSERIALNUM:
        *write_method = write_entPhysicalSerialNum;
        osal_memset(&entityStr,0,sizeof(entityStr));
        if (ENTITY_PHY_DESCR_INDEX == pPhyEntry->index)
        {
            sal_sys_sysinfoVar_get(DFLT_SYS_SN_VAR, entityStr);
        }
        *var_len = osal_strlen(entityStr);
        return (u_char*)entityStr;
    case ENTPHYSICALMFGNAME:
        osal_memset(&entityStr,0,sizeof(entityStr));
        if (ENTITY_PHY_DESCR_INDEX == pPhyEntry->index)
        {
            osal_strcpy(entityStr, ENTITY_MFG_NAME);
        }
        *var_len = osal_strlen(entityStr);
        return (u_char*)entityStr;
    case ENTPHYSICALMODELNAME:
        osal_memset(&entityStr,0,sizeof(entityStr));
        if (ENTITY_PHY_DESCR_INDEX == pPhyEntry->index)
        {
            sal_sys_bdinfoVar_get("modelname", sysModel);
            osal_memcpy(entityStr,sysModel, osal_strlen(sysModel));
        }
        *var_len = osal_strlen(entityStr);
        return (u_char*)entityStr;
    case ENTPHYSICALALIAS:
        osal_memset(&entityStr,0,sizeof(entityStr));
        *var_len = 0;
        return (u_char*)entityStr;
    case ENTPHYSICALASSETID:
        *write_method = write_entPhysicalAssetID;
        osal_memset(&entityStr,0,sizeof(entityStr));
        *var_len = 0;
        return (u_char*)entityStr;
    case ENTPHYSICALISFRU:
        long_ret = ENTITY_PHY_FRU;
        return (u_char*) &long_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_entLogicalTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_entityMIB above.
 */
unsigned char *
var_entLogicalTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, ENTITY_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case ENTLOGICALINDEX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALDESCR:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALTYPE:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALCOMMUNITY:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALTADDRESS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALTDOMAIN:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALCONTEXTENGINEID:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case ENTLOGICALCONTEXTNAME:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_entLPMappingTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_entityMIB above.
 */
unsigned char *
var_entLPMappingTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, ENTITY_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case ENTLPPHYSICALINDEX:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_entAliasMappingTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_entityMIB above.
 */
unsigned char *
var_entAliasMappingTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    physicall_entry_t *pPhyEntry;
    uint32 index;
    static oid aliasOid[11] = { 1,3,6,1,2,1,2,2,1,1,0};

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */

    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
       return NULL;
    }

    if (exact) {
        if (*length != 14)
            return NULL;

        index = name[12];
        pPhyEntry = entity_getPhysicalEntry(index);
    } else{

        if (12 == *length)
        {
            pPhyEntry  = entity_aliasMap_scanFirst();
        }
        else
        {
          index = name[12];
          entity_aliasMap_scanAccessInit();
          while((pPhyEntry = entity_aliasMap_scanAccessNext()) != NULL){
            if (index == pPhyEntry->index)
             {
                 pPhyEntry = entity_aliasMap_scanAccessNext();
                 break;
             }
           }

         }

        if (pPhyEntry) {
            name[12] = pPhyEntry->index;
            *length = 13;
            name[13] = 0;
            *length = 14;
        }
    }

    if (pPhyEntry == NULL) {
        return NULL;
    }

    *var_len = sizeof(long_ret);
    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case ENTALIASLOGICALINDEXORZERO:
        long_ret = 0;
        return (u_char*) &long_ret;
    case ENTALIASMAPPINGIDENTIFIER:
        aliasOid[10] = LP2UP(pPhyEntry->parentRelPos -1 );
        *var_len = sizeof(aliasOid);
        return (u_char*)aliasOid;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_entPhysicalContainsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_entityMIB above.
 */
unsigned char *
var_entPhysicalContainsTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    physicall_entry_t *pPhyEntry;
    uint32 index;
    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */

    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
       return NULL;
    }

    if (exact) {
        if (*length != 14)
            return NULL;

        index = name[13];
        pPhyEntry = entity_getPhysicalEntry(index);
    } else{

        if (12 == *length)
        {
            pPhyEntry  = entity_contains_scanFirst();
        }
        else
        {
          index = name[13];
          entity_contains_scanAccessInit();
          while((pPhyEntry = entity_contains_scanAccessNext()) != NULL){
            if (index == pPhyEntry->index)
             {
                 pPhyEntry = entity_contains_scanAccessNext();
                 break;
             }
           }

         }

        if (pPhyEntry) {
            name[12] = pPhyEntry->containedIn;
            *length = 13;
            name[13] = pPhyEntry->index;
            *length = 14;
        }
    }

    if (pPhyEntry == NULL) {
        return NULL;
    }

    *var_len = sizeof(long_ret);

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case ENTPHYSICALCHILDINDEX:
        long_ret = pPhyEntry->index;
        return (u_char*) &long_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


int
write_entPhysicalSerialNum(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to entityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to entityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_entPhysicalAlias(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to entityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to entityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_entPhysicalAssetID(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to entityMIB not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to entityMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
