/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef ENTITYMIB_H
#define ENTITYMIB_H

/* function declarations */
void init_entityMIB(void);
FindVarMethod var_entityMIB;
FindVarMethod var_entPhysicalTable;
FindVarMethod var_entLogicalTable;
FindVarMethod var_entLPMappingTable;
FindVarMethod var_entAliasMappingTable;
FindVarMethod var_entPhysicalContainsTable;
    WriteMethod write_entPhysicalSerialNum;
    WriteMethod write_entPhysicalAlias;
    WriteMethod write_entPhysicalAssetID;

#endif /* ENTITYMIB_H */
