#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#ERPSDIR should defined in caller Makefile which is relative path of caller.
ERPS_OBJ := $(ERPSDIR)/proto_erps.o
