#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#IGMPDIR should defined in caller Makefile which is relative path of caller.
IGMP_OBJ := \
	$(IGMPDIR)/proto_igmp.o \
	$(IGMPDIR)/proto_igmp_group_db.o \
	$(IGMPDIR)/proto_igmp_querier.o \
	$(IGMPDIR)/proto_igmp_tx.o \
	$(IGMPDIR)/proto_igmp_util.o \
	$(IGMPDIR)/proto_igmp_rx.o

