/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "dot1dBridge_api.h"
#include "qBridge.h"
#include "mib_util.h"

#include <time.h>
#include <libsal/sal_sys.h>
#include <common/sys_def.h>
#include <osal/time.h>
#ifdef CONFIG_SYS_PROTO_STP
#include <stp/proto_stp.h>
#endif
#include <rsd/rsd_l2.h>
#include <rtk/stat.h>
#include <rtk/switch.h>
#include <libsal/sal_util.h>


/*
 * dot1dBridge_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

#define SYS_HUNDREDTHS_SECOND 100

/*bridge type */
#define  UNKNOWN_BRIDGE      1
#define  TRANSPARENT_BRIDGE  2     /* Only this value is used */
#define  SOURCE_ROUTE        3
#define  SRT_BRIDGE             4

/**/
#define UNKNOWN_PROTO                  1
#define DECLB100_PROTO                   2
#define IEEE8021d_PROTO                 3

#define BRIDGE_TABLE_SIZE 32
#define BRIDGE_FDB_TABLE_SIZE       4096
oid dot1dBridge_variables_oid[] = { 1,3,6,1,2,1,17 };


#define DOT1DBASEBRIDGEADDRESS      1
#define DOT1DBASENUMPORTS       2
#define DOT1DBASETYPE       3
#define DOT1DSTPPROTOCOLSPECIFICATION       4
#define DOT1DSTPPRIORITY        5
#define DOT1DSTPTIMESINCETOPOLOGYCHANGE     6
#define DOT1DSTPTOPCHANGES      7
#define DOT1DSTPDESIGNATEDROOT      8
#define DOT1DSTPROOTCOST        9
#define DOT1DSTPROOTPORT        10
#define DOT1DSTPMAXAGE      11
#define DOT1DSTPHELLOTIME       12
#define DOT1DSTPHOLDTIME        13
#define DOT1DSTPFORWARDDELAY        14
#define DOT1DSTPBRIDGEMAXAGE        15
#define DOT1DSTPBRIDGEHELLOTIME     16
#define DOT1DSTPBRIDGEFORWARDDELAY      17
#define DOT1DTPLEARNEDENTRYDISCARDS     18
#define DOT1DTPAGINGTIME        19
#define DOT1DBASEPORT       20
#define DOT1DBASEPORTIFINDEX        21
#define DOT1DBASEPORTCIRCUIT        22
#define DOT1DBASEPORTDELAYEXCEEDEDDISCARDS      23
#define DOT1DBASEPORTMTUEXCEEDEDDISCARDS        24
#define DOT1DSTPPORT        25
#define DOT1DSTPPORTPRIORITY        26
#define DOT1DSTPPORTSTATE       27
#define DOT1DSTPPORTENABLE      28
#define DOT1DSTPPORTPATHCOST        29
#define DOT1DSTPPORTDESIGNATEDROOT      30
#define DOT1DSTPPORTDESIGNATEDCOST      31
#define DOT1DSTPPORTDESIGNATEDBRIDGE        32
#define DOT1DSTPPORTDESIGNATEDPORT      33
#define DOT1DSTPPORTFORWARDTRANSITIONS      34
#define DOT1DTPFDBADDRESS       35
#define DOT1DTPFDBPORT      36
#define DOT1DTPFDBSTATUS        37
#define DOT1DTPPORT     38
#define DOT1DTPPORTMAXINFO      39
#define DOT1DTPPORTINFRAMES     40
#define DOT1DTPPORTOUTFRAMES        41
#define DOT1DTPPORTINDISCARDS       42
#define DOT1DSTATICADDRESS      43
#define DOT1DSTATICRECEIVEPORT      44
#define DOT1DSTATICALLOWEDTOGOTO        45
#define DOT1DSTATICSTATUS       46


#define DOT1D_OIDLEN_MAX                    12
#define DOT1D_FDB_OIDLEN_MAX            17

/*dot1dBasePortTable*/
#define DOT1D_BASEPORT_INDEX_MIN    1
#define DOT1D_BASEPORT_INDEX_MAX    5

/*dot1dTpFdbTable*/
#define DOT1D_FDB_INDEX_MIN    1
#define DOT1D_FDB_INDEX_MAX    3

/*dot1dTpPortTable*/
#define DOT1D_PORT_INDEX_MIN    1
#define DOT1D_PORT_INDEX_MAX    5

/*dot1dStaticTable*/
#define DOT1D_STATIC_INDEX_MIN    1
#define DOT1D_STATIC_INDEX_MAX    4



/*
 * variable4 dot1dBridge_variables:
 *   this variable defines function callbacks and type return information
 *   for the dot1dBridge mib section
 */


static long long_ret;

struct variable4 dot1dBridge_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

{DOT1DBASEBRIDGEADDRESS,  ASN_OCTET_STR,  RONLY ,  var_dot1dBridge, 2,  { 1,1 }},

{DOT1DBASENUMPORTS,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 1,2 }},

{DOT1DBASETYPE,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 1,3 }},

{DOT1DSTPPROTOCOLSPECIFICATION,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,1 }},

{DOT1DSTPPRIORITY,  ASN_INTEGER,  RWRITE,  var_dot1dBridge, 2,  { 2,2 }},

{DOT1DSTPTIMESINCETOPOLOGYCHANGE,  ASN_TIMETICKS,  RONLY ,  var_dot1dBridge, 2,  { 2,3 }},

{DOT1DSTPTOPCHANGES,  ASN_COUNTER,  RONLY ,  var_dot1dBridge, 2,  { 2,4 }},

{DOT1DSTPDESIGNATEDROOT,  ASN_OCTET_STR,  RONLY ,  var_dot1dBridge, 2,  { 2,5 }},

{DOT1DSTPROOTCOST,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,6 }},

{DOT1DSTPROOTPORT,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,7 }},

{DOT1DSTPMAXAGE,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,8 }},

{DOT1DSTPHELLOTIME,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,9 }},

{DOT1DSTPHOLDTIME,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,10 }},

{DOT1DSTPFORWARDDELAY,  ASN_INTEGER,  RONLY ,  var_dot1dBridge, 2,  { 2,11 }},

{DOT1DSTPBRIDGEMAXAGE,  ASN_INTEGER,  RWRITE,  var_dot1dBridge, 2,  { 2,12 }},

{DOT1DSTPBRIDGEHELLOTIME,  ASN_INTEGER,  RWRITE,  var_dot1dBridge, 2,  { 2,13 }},

{DOT1DSTPBRIDGEFORWARDDELAY,  ASN_INTEGER,  RWRITE,  var_dot1dBridge, 2,  { 2,14 }},

{DOT1DTPLEARNEDENTRYDISCARDS,  ASN_COUNTER,  RONLY ,  var_dot1dBridge, 2,  { 4,1 }},

{DOT1DTPAGINGTIME,  ASN_INTEGER,  RWRITE,  var_dot1dBridge, 2,  { 4,2 }},

{DOT1DBASEPORT,  ASN_INTEGER,  RONLY,   var_dot1dBasePortTable, 4,  { 1,4, 1, 1 }},

{DOT1DBASEPORTIFINDEX,  ASN_INTEGER,  RONLY,   var_dot1dBasePortTable, 4,  { 1,4, 1, 2 }},

{DOT1DBASEPORTCIRCUIT,  ASN_OBJECT_ID,  RONLY,   var_dot1dBasePortTable, 4,  { 1,4, 1, 3 }},

{DOT1DBASEPORTDELAYEXCEEDEDDISCARDS,  ASN_COUNTER,  RONLY,   var_dot1dBasePortTable, 4,  { 1,4, 1, 4 }},

{DOT1DBASEPORTMTUEXCEEDEDDISCARDS,  ASN_COUNTER,  RONLY,   var_dot1dBasePortTable, 4,  { 1,4, 1, 5 }},

#ifdef CONFIG_SYS_PROTO_STP
{DOT1DSTPPORT,  ASN_INTEGER,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 1 }},

{DOT1DSTPPORTPRIORITY,  ASN_INTEGER,  RWRITE,  var_dot1dStpPortTable, 4,  { 2,15, 1, 2 }},

{DOT1DSTPPORTSTATE,  ASN_INTEGER,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 3 }},

{DOT1DSTPPORTENABLE,  ASN_INTEGER,  RWRITE,  var_dot1dStpPortTable, 4,  { 2,15, 1, 4 }},

{DOT1DSTPPORTPATHCOST,  ASN_INTEGER,  RWRITE,  var_dot1dStpPortTable, 4,  { 2,15, 1, 5 }},

{DOT1DSTPPORTDESIGNATEDROOT,  ASN_OCTET_STR,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 6 }},

{DOT1DSTPPORTDESIGNATEDCOST,  ASN_INTEGER,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 7 }},

{DOT1DSTPPORTDESIGNATEDBRIDGE,  ASN_OCTET_STR,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 8 }},

{DOT1DSTPPORTDESIGNATEDPORT,  ASN_OCTET_STR,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 9 }},

{DOT1DSTPPORTFORWARDTRANSITIONS,  ASN_COUNTER,  RONLY,   var_dot1dStpPortTable, 4,  { 2,15, 1, 10 }},
#endif

#if 1
{DOT1DTPFDBADDRESS,  ASN_OCTET_STR,  RONLY,   var_dot1dTpFdbTable, 4,  { 4,3, 1, 1 }},

{DOT1DTPFDBPORT,  ASN_INTEGER,  RONLY,   var_dot1dTpFdbTable, 4,  { 4,3, 1, 2 }},

{DOT1DTPFDBSTATUS,  ASN_INTEGER,  RONLY,   var_dot1dTpFdbTable, 4,  { 4,3, 1, 3 }},
#endif

{DOT1DTPPORT,  ASN_INTEGER,  RONLY,   var_dot1dTpPortTable, 4,  { 4,4, 1, 1 }},

{DOT1DTPPORTMAXINFO,  ASN_INTEGER,  RONLY,   var_dot1dTpPortTable, 4,  { 4,4, 1, 2 }},

{DOT1DTPPORTINFRAMES,  ASN_COUNTER,  RONLY,   var_dot1dTpPortTable, 4,  { 4,4, 1, 3 }},

{DOT1DTPPORTOUTFRAMES,  ASN_COUNTER,  RONLY,   var_dot1dTpPortTable, 4,  { 4,4, 1, 4 }},

{DOT1DTPPORTINDISCARDS,  ASN_COUNTER,  RONLY,   var_dot1dTpPortTable, 4,  { 4,4, 1, 5 }},
#if 1
{DOT1DSTATICADDRESS,  ASN_OCTET_STR,  RWRITE,  var_dot1dStaticTable, 4,  { 5,1, 1, 1 }},

{DOT1DSTATICRECEIVEPORT,  ASN_INTEGER,  RWRITE,  var_dot1dStaticTable, 4,  { 5,1, 1, 2 }},

{DOT1DSTATICALLOWEDTOGOTO,  ASN_OCTET_STR,  RWRITE,  var_dot1dStaticTable, 4,  { 5,1, 1, 3 }},

{DOT1DSTATICSTATUS,  ASN_INTEGER,  RWRITE,  var_dot1dStaticTable, 4,  { 5,1, 1, 4 }},
#endif
};

/*    (L = length of the oidsuffix) */

/** Initializes the dot1dBridge module */
void
init_dot1dBridge(void)
{

    DEBUGMSGTL(("dot1dBridge", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */

    REGISTER_MIB("dot1dBridge", dot1dBridge_variables, variable4,
               dot1dBridge_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_dot1dBridge():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_dot1dBridge(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char strMac[CAPA_MAC_BYTE_NUM];
    static unsigned char string[256];
    uint32 holdCnt;
//    static unsigned char string[SPRINT_MAX_LEN];

    u_long tmp;
    struct timeval tv;
#ifdef CONFIG_SYS_PROTO_STP
    sys_stp_mst_info_t mstInfo;
    sys_stp_info_t stpInfo;
#endif

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

#ifdef CONFIG_SYS_PROTO_STP
    SYS_MEM_CLEAR(mstInfo);
    SYS_MEM_CLEAR(stpInfo);
    sal_stp_mstInfo_get(0,&mstInfo);
    sal_stp_info_get(&stpInfo);
#endif

  /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1DBASEBRIDGEADDRESS:
       {
        sys_mac_t mac;
        sal_sys_macAddr_get(&mac);
        memcpy(strMac, mac.octet, CAPA_MAC_BYTE_NUM);
        *var_len = CAPA_MAC_BYTE_NUM;
        return (u_char*) strMac;
       }

    case DOT1DBASENUMPORTS:
      //  sal_physic_port_num_get(0, &ulong_ret);
        ulong_ret = SYS_USER_PORT_NUM(SYS_DEV_ID_DEFAULT);
        return (u_char*) &ulong_ret;

    case DOT1DBASETYPE:
        long_ret = TRANSPARENT_BRIDGE ;   /*only support*/
        return (u_char*) &long_ret;

    case DOT1DSTPPROTOCOLSPECIFICATION:
        long_ret = IEEE8021d_PROTO;     /*only support*/
        return (u_char*) &long_ret;

#ifdef CONFIG_SYS_PROTO_STP
    case DOT1DSTPTIMESINCETOPOLOGYCHANGE:
        ulong_ret = mstInfo.tcTimer * 100;
        return (u_char*) &ulong_ret;

    case DOT1DSTPTOPCHANGES:
        ulong_ret = mstInfo.tcTimes;
        return (u_char*) &ulong_ret;

    case DOT1DSTPDESIGNATEDROOT:
        sprintf(string,"%d/%.2X:%.2X:%.2X:%.2X:%.2X:%.2X",mstInfo.rootPriority.designatedBridgeId.priority, \
                                                                                      mstInfo.rootPriority.designatedBridgeId.addr[0],
                                                                                      mstInfo.rootPriority.designatedBridgeId.addr[1],
                                                                                      mstInfo.rootPriority.designatedBridgeId.addr[2],
                                                                                      mstInfo.rootPriority.designatedBridgeId.addr[3],
                                                                                      mstInfo.rootPriority.designatedBridgeId.addr[4],
                                                                                      mstInfo.rootPriority.designatedBridgeId.addr[5]);
        *var_len = strlen(string); /*this when some byte is equal to 0,may generate bug.*/
        return (u_char*) &string;

    case DOT1DSTPROOTCOST:
        ulong_ret = mstInfo.rootPriority.internalRootPathCost;
        return (u_char*) &ulong_ret;

    case DOT1DSTPROOTPORT:
        ulong_ret = LP2UP(mstInfo.rootPortId.number - 1);
        return (u_char*) &ulong_ret;

    case DOT1DSTPMAXAGE:
        ulong_ret = stpInfo.maximumAge * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;

    case DOT1DSTPHELLOTIME:
        ulong_ret = stpInfo.helloTime * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;

    case DOT1DSTPHOLDTIME:
        #ifdef CONFIG_SYS_PROTO_STP
        sal_stp_txHoldCount_get(&holdCnt);
        #endif
         ulong_ret = 10/holdCnt * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;

    case DOT1DSTPFORWARDDELAY:
        ulong_ret = stpInfo.forwardDelay * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;

    case DOT1DSTPPRIORITY:
        *write_method = write_dot1dStpPriority;
        /*mstp id = 0*/
        sal_stp_priority_get(&ulong_ret);
        return (u_char*) &ulong_ret;

    case DOT1DSTPBRIDGEMAXAGE:
        *write_method = write_dot1dStpBridgeMaxAge;
        sal_stp_maximumAge_get(&ulong_ret);
        ulong_ret = ulong_ret * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;

    case DOT1DSTPBRIDGEHELLOTIME:
        *write_method = write_dot1dStpBridgeHelloTime;
        sal_stp_helloTime_get(&ulong_ret);
        ulong_ret = ulong_ret * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;

    case DOT1DSTPBRIDGEFORWARDDELAY:
        *write_method = write_dot1dStpBridgeForwardDelay;
        sal_stp_forwardDelay_get(&ulong_ret);
        ulong_ret = ulong_ret * SYS_HUNDREDTHS_SECOND;
        return (u_char*) &ulong_ret;
#endif

        /*dot1dTpLearnedEntryDiscards*/
    case DOT1DTPLEARNEDENTRYDISCARDS:
        sal_mib_dot1dTpLearnedEntryDiscards_get(&ulong_ret);
        return (u_char*) &ulong_ret;

    case DOT1DTPAGINGTIME:
        *write_method = write_dot1dTpAgingTime;
        sal_l2_aging_get(&ulong_ret);
        return (u_char*) &ulong_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_dot1dBasePortTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot1dBridge above.
 */

unsigned char *
var_dot1dBasePortTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
   // static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];

    unsigned long   index;
    rtk_stat_port_cntr_t portcntr;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    *write_method = NULL;
    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
        return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length != 12 )
            return NULL;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));



    /*
   * this is where we do the value assignments for the mib results.
   */

    switch(vp->magic) {
    case DOT1DBASEPORT:
        ulong_ret = LP2UP(index);
        return (u_char*) &ulong_ret;

    case DOT1DBASEPORTIFINDEX:
        ulong_ret = LP2UP(index);
        return (u_char*) &ulong_ret;

    case DOT1DBASEPORTCIRCUIT:
      /*
     * Currently only Ethernet interfaces are supported and hence returning
     * the OID {0, 0}.
     */
      objid[0] = 0;
      objid[1] = 0;
      *var_len = 2*sizeof(objid[0]);
       return (u_char*) &objid;

    case DOT1DBASEPORTDELAYEXCEEDEDDISCARDS:
       //sal_mib_dot1d_delayexceededdiscards_get(index, &ulong_ret);
       ulong_ret = 0;
       return (u_char*) &ulong_ret;

    case DOT1DBASEPORTMTUEXCEEDEDDISCARDS:
        sal_mib_dot3StatsFrameTooLongs_get(index, &ulong_ret);
       // sal_mib_etherStatsOverSizePkts_get(index, &ulong_ret);
        return (u_char*) &ulong_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dTpFdbTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot1dBridge above.
 */
unsigned char *
var_dot1dTpFdbTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    tpfdb_entry_t *tpfdb;
    uint32 vlanId;
    char *pMac;
    int     macLen, i;
    char   macAddr[CAPA_MAC_BYTE_NUM];

    static uint32 macNum = 0;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
       return NULL;
    }

    if (exact) {

        if (*length != 17)
            return NULL;

        macAddr[0] = (char)name[11];
        macAddr[1] = (char)name[12];
        macAddr[2] = (char)name[13];
        macAddr[3] = (char)name[14];
        macAddr[4] = (char)name[15];
        macAddr[5] = (char)name[16];

        tpfdb = qbridge_getTpfdbEntry_byMac(macAddr);
    } else {

        if (11 == *length)
        {
            qbridge_tpfdb_entry_get(&macNum, TRUE);
            if(macNum == 0)
                return NULL;

            osal_memset(macAddr, 0 , CAPA_MAC_BYTE_NUM);
            tpfdb = qbridge_tpfdb_scanFirst();
        }
        else
        {
            macAddr[0] = (char)name[11];
            macAddr[1] = (char)name[12];
            macAddr[2] = (char)name[13];
            macAddr[3] = (char)name[14];
            macAddr[4] = (char)name[15];
            macAddr[5] = (char)name[16];

          qbridge_tpfdb_scanAccessInit();
          while((tpfdb = qbridge_tpfdb_scanAccessNext()) != NULL){
            if (0 == osal_memcmp(macAddr , tpfdb->mac, CAPA_MAC_BYTE_NUM))
             {
                 tpfdb = qbridge_tpfdb_scanAccessNext();
                 break;
             }
           }

         }

        if (tpfdb) {
            *length = 11;
            for(i = 0; i < CAPA_MAC_BYTE_NUM; i++)
            {
                name[(*length)++] = tpfdb->mac[i];
            }
        }
    }

    if (tpfdb == NULL) {
        return NULL;
    }

    *var_len = sizeof(long_ret);
    /*
   * this is where we do the value assignments for the mib results.
   */

    switch(vp->magic) {
    case DOT1DTPFDBADDRESS:
        *var_len = 6 ;
        return (u_char*) tpfdb->mac;

    case DOT1DTPFDBPORT:
        long_ret = tpfdb->port;
        return (u_char *)&long_ret;
    case DOT1DTPFDBSTATUS:
        long_ret = tpfdb->status;
        return (u_char*) &long_ret;

    default:
      ERROR_MSG("");
    }

    return NULL;
}
/*
 * var_dot1dTpPortTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot1dBridge above.
 */
unsigned char *
var_dot1dTpPortTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static uint64 cntr64 = 0;
    //static unsigned char string[SPRINT_MAX_LEN];

    unsigned long index;
    uint32 maxPktlen;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    *write_method = NULL;
    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
       return NULL;
    }

    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
        return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length != 12 )
            return NULL;

    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index,vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));


    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1DTPPORT:
       ulong_ret = LP2UP(index);
       return (u_char*) &ulong_ret;

    case DOT1DTPPORTMAXINFO:
#ifdef CONFIG_SYS_JUMBO_FRAME
        sal_switch_maxFrameSize_get(&ulong_ret);
        if (0 == ulong_ret)
            ulong_ret = DFLT_PORT_MAX_FRAME_SIZE;
#else
        ulong_ret = DFLT_PORT_MAX_FRAME_SIZE;
#endif
        return (u_char*) &ulong_ret;

    case DOT1DTPPORTINFRAMES:
       //sal_mib_dot1d_tpHCPortInDiscards_get(index -1, &cntr64);
       ulong_ret = 0;
       sal_mib_ifInUcastPkts_get(index,&cntr64);
       ulong_ret += (u_long)cntr64;
       sal_mib_ifInNUcastPkts_get(index, &cntr64);
       ulong_ret += (u_long)cntr64;
       return (u_char*) &ulong_ret;

    case DOT1DTPPORTOUTFRAMES:
       ulong_ret = 0;
       sal_mib_ifOutUcastPkts_get(index , &cntr64);
       ulong_ret += (u_long)cntr64;
       sal_mib_ifOutNUcastPkts_get(index, &cntr64);
       ulong_ret += (u_long)cntr64;
       return (u_char*) &ulong_ret;

    case DOT1DTPPORTINDISCARDS:
       sal_mib_dot1dTpPortInDiscards_get(index, &cntr64);
       ulong_ret = (u_long)cntr64;
       return (u_char*) &ulong_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dStaticTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot1dBridge above.
 */
unsigned char *
var_dot1dStaticTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
      tpfdb_entry_t *tpfdb;
    uint32 vlanId;
    char *pMac;
    int     macLen, i;
    char   macAddr[CAPA_MAC_BYTE_NUM];

    static uint32 macNum = 0;

    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
        return NULL;
    }

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    switch(vp->magic) {
    case DOT1DSTATICADDRESS:
        *write_method = write_dot1dStaticAddress;
        break;

    case DOT1DSTATICRECEIVEPORT:
        *write_method = write_dot1dStaticReceivePort;
        break;

    case DOT1DSTATICSTATUS:
        *write_method = write_dot1dStaticStatus;
        break;

    default:
       *write_method = NULL;
    }

    if (exact) {

        if ( *length < 17 || *length > 18)
            return NULL;

        macAddr[0] = (char)name[11];
        macAddr[1] = (char)name[12];
        macAddr[2] = (char)name[13];
        macAddr[3] = (char)name[14];
        macAddr[4] = (char)name[15];
        macAddr[5] = (char)name[16];

        tpfdb = qbridge_getStaticUcastEntry_byMac(macAddr);
    } else {
        if (11 == *length)
        {
            qbridge_staticUnicast_entry_get(&macNum);
            if(macNum == 0)
                return NULL;

            osal_memset(macAddr, 0 , CAPA_MAC_BYTE_NUM);
            tpfdb = qbridge_staticUcast_scanFirst();
        }
        else
        {
            macAddr[0] = (char)name[11];
            macAddr[1] = (char)name[12];
            macAddr[2] = (char)name[13];
            macAddr[3] = (char)name[14];
            macAddr[4] = (char)name[15];
            macAddr[5] = (char)name[16];

          qbridge_staticUcast_scanAccessInit();
          while((tpfdb = qbridge_staticUcast_scanAccessNext()) != NULL){
            if (0 == osal_memcmp(macAddr , tpfdb->mac, CAPA_MAC_BYTE_NUM))
             {
                 tpfdb = qbridge_staticUcast_scanAccessNext();
                 break;
             }
           }
         }

        if (tpfdb) {
            *length = 11;
            for(i = 0; i < CAPA_MAC_BYTE_NUM; i++)
            {
                name[(*length)++] = tpfdb->mac[i];
            }
            name[(*length)++] = tpfdb->port;
        }
    }

    if (tpfdb == NULL) {
        return NULL;
    }

    *var_len = sizeof(long_ret);
    /*
   * this is where we do the value assignments for the mib results.
   */

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1DSTATICADDRESS:
        *var_len = CAPA_MAC_BYTE_NUM;
        return (u_char*)tpfdb->mac;

    case DOT1DSTATICRECEIVEPORT:
        long_ret = tpfdb->port;
        return (u_char*) &long_ret;


    case DOT1DSTATICALLOWEDTOGOTO:
        long_ret = 0;
        return (u_char*) &long_ret;


    case DOT1DSTATICSTATUS:
        long_ret = tpfdb->status;
        return (u_char*) &long_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


#ifdef CONFIG_SYS_PROTO_STP
/*
 * var_dot1dStpPortTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_dot1dBridge above.
 */
unsigned char *
var_dot1dStpPortTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
//    static unsigned char string[SPRINT_MAX_LEN];


    unsigned long   index;
    sys_stp_mst_port_info_t mstPortInfo;
    sys_enable_t  enable;
    static unsigned char string[256];
    sys_stp_port_info_t portInfo;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    *write_method = NULL;

    if (0 != AGUTIL_advance_index_name(vp, name, length, exact)) {
        return NULL;
    }

    if (header_simple_table(vp,name,length,exact,var_len,write_method, LP2UP(LOGIC_PORT_END) + 1)
                                                == MATCH_FAILED )
        return NULL;

    index = vp->namelen >= *length ?  0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
        if (*length != 12 )
            return NULL;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index,vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));
    /*
   * this is where we do the value assignments for the mib results.
   */

    sal_stp_mstPortInfo_get(0, index, &mstPortInfo);

    switch(vp->magic) {
    case DOT1DSTPPORT:
        ulong_ret = LP2UP(index) ;
        return (u_char*) &ulong_ret;

    case DOT1DSTPPORTPRIORITY:
        *write_method = write_dot1dStpPortPriority;
        sal_stp_portPriority_get(index, (uint32 *)&ulong_ret);
        return (u_char*) &ulong_ret;

    case DOT1DSTPPORTSTATE:
        if (!IS_LP_TRKMBR(index))
        {
            if(mstPortInfo.portState == STP_PORT_STATE_DISABLED)
                ulong_ret = 1; /*disable*/
            else if(mstPortInfo.portState == STP_PORT_STATE_DISCARDING)
                ulong_ret = 2; /*blocking*/
            else if(mstPortInfo.portState == STP_PORT_STATE_LEARNING)
                ulong_ret = 4; /*learning*/
            else if(mstPortInfo.portState == STP_PORT_STATE_FORWARDING)
                ulong_ret = 5; /*forwarding*/
            else
                ulong_ret = 6;
        }
        else
            ulong_ret = 1; /*disable*/
        return (u_char*) &ulong_ret;

    case DOT1DSTPPORTENABLE:
        *write_method = write_dot1dStpPortEnable;
        sal_stp_portAdminEnable_get(index, &enable);
        if(enable == DISABLED)
            ulong_ret = 2; /*disable for mib value*/
        else
            ulong_ret = 1; /*enable for mib value*/
        return (u_char*) &ulong_ret;

        /*the port to the root port cost*/
    case DOT1DSTPPORTPATHCOST:
        *write_method = write_dot1dStpPortPathCost;
        sal_stp_portInfo_get(index,&portInfo);
        ulong_ret = portInfo.operExtPathCost;
        //sal_stp_portPathCost_get(index , &ulong_ret);
        return (u_char*) &ulong_ret;

    case DOT1DSTPPORTDESIGNATEDROOT:
        osal_memset(string,0,sizeof(string));
        osal_sprintf(string, "%d-%.2X.%.2X.%.2X.%.2X.%.2X.%.2X", mstPortInfo.portPriority.rootBridgeId.priority,
                                              mstPortInfo.portPriority.rootBridgeId.addr[0],
                                              mstPortInfo.portPriority.rootBridgeId.addr[1],
                                              mstPortInfo.portPriority.rootBridgeId.addr[2],
                                              mstPortInfo.portPriority.rootBridgeId.addr[3],
                                              mstPortInfo.portPriority.rootBridgeId.addr[4],
                                              mstPortInfo.portPriority.rootBridgeId.addr[5]);

        *var_len = strlen(string);
        return (u_char*) &string;

        /*this port to designated port cost*/
    case DOT1DSTPPORTDESIGNATEDCOST:
        ulong_ret = mstPortInfo.portPriority.internalRootPathCost;
        return (u_char*) &ulong_ret;

    case DOT1DSTPPORTDESIGNATEDBRIDGE:
        osal_memset(string,0,sizeof(string));
        osal_sprintf(string, "%d-%.2X.%.2X.%.2X.%.2X.%.2X.%.2X", mstPortInfo.portPriority.designatedBridgeId.priority,
                                              mstPortInfo.portPriority.designatedBridgeId.addr[0],
                                              mstPortInfo.portPriority.designatedBridgeId.addr[1],
                                              mstPortInfo.portPriority.designatedBridgeId.addr[2],
                                              mstPortInfo.portPriority.designatedBridgeId.addr[3],
                                              mstPortInfo.portPriority.designatedBridgeId.addr[4],
                                              mstPortInfo.portPriority.designatedBridgeId.addr[5]);

        *var_len = strlen(string);
        return (u_char*) &string;

    case DOT1DSTPPORTDESIGNATEDPORT:
        osal_memset(string,0,sizeof(string));
        sal_stp_portPriority_get(index , (uint32 *)&ulong_ret);
        osal_sprintf(string, "%d-%d",ulong_ret, LP2UP(index));
        *var_len = strlen(string);
        return (u_char*) &string;

    case DOT1DSTPPORTFORWARDTRANSITIONS:
        ulong_ret = 0;  /*not support*/
        return (u_char*) &ulong_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}

int
write_dot1dStpPriority(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if ( (value < 0)  || (value > 61440) || (value % 4096 != 0))
          {
                return SNMP_ERR_WRONGVALUE;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          SYS_SNMP_ERR_CHK(sal_stp_priority_set(value), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_dot1dStpBridgeMaxAge(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    uint32 helloTime;
    uint32 forwardDelay;


    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if ( (value < 6*SYS_HUNDREDTHS_SECOND)  || (value > 40*SYS_HUNDREDTHS_SECOND))
          {
                return SNMP_ERR_WRONGVALUE;
          }

         if (0 != value %SYS_HUNDREDTHS_SECOND)
            return SNMP_ERR_WRONGVALUE;

          stp_helloTime_get(&helloTime);
          stp_forwardDelay_get(&forwardDelay);

           if (value/100 < (2 * (helloTime + 1)))
             return SNMP_ERR_WRONGVALUE;

            if (value/100 > (2 * (forwardDelay - 1)))
                return SNMP_ERR_WRONGVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = value/SYS_HUNDREDTHS_SECOND;
          SYS_SNMP_ERR_CHK(sal_stp_maximumAge_set(value), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_dot1dStpBridgeHelloTime(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    value = * (long *) var_val;
    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if ( (value < 1*SYS_HUNDREDTHS_SECOND)  || (value > 10*SYS_HUNDREDTHS_SECOND))
          {
                return SNMP_ERR_WRONGVALUE;
          }

          if (0 != value %100)
            return SNMP_ERR_WRONGVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = value/SYS_HUNDREDTHS_SECOND;
          SYS_SNMP_ERR_CHK(sal_stp_helloTime_set(value), SNMP_ERR_RESOURCEUNAVAILABLE);

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_dot1dStpBridgeForwardDelay(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if ( (value < 4*SYS_HUNDREDTHS_SECOND)  || (value > 30*SYS_HUNDREDTHS_SECOND))
          {
                return SNMP_ERR_WRONGVALUE;
          }

          if (0 != value%SYS_HUNDREDTHS_SECOND)
                return SNMP_ERR_WRONGVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = value/SYS_HUNDREDTHS_SECOND;
          SYS_SNMP_ERR_CHK(sal_stp_forwardDelay_set(value), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_dot1dStpPortPriority(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    ulong index;

    index = UP2LP(name[name_len-1]);

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

         if ( (value < 0)  || (value > 240) || (value % 16 != 0))
         {
            return SNMP_ERR_WRONGVALUE;
         }

         if(IS_LOGIC_PORT_INVALID(index))
            return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          SYS_SNMP_ERR_CHK(sal_stp_portPriority_set(index,value), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dStpPortEnable(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    sys_enable_t enable;
    uint32 index;

    value = * (long *) var_val;
    index = UP2LP(name[name_len-1]);

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if(value < 1 || value > 2)
          {
                return SNMP_ERR_WRONGVALUE;
          }

         if(IS_LOGIC_PORT_INVALID(index))
            return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;
            /*not support per port*/
             if(value == 2)
                enable = DISABLED;
             else if(value == 1)
                enable = ENABLED;

             SYS_SNMP_ERR_CHK(sal_stp_portAdminEnable_set(index, enable), SNMP_ERR_RESOURCEUNAVAILABLE);

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dStpPortPathCost(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    long index;
    uint32 method;

    index = UP2LP(name[name_len-1]);
    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

         sal_stp_pathcostMethod_get(&method);
         if ( ((STP_PATHCOST_METHOD_LONG == method) && (value > 200000000)) ||
               ((STP_PATHCOST_METHOD_SHORT == method) && (value > 65535)))
         {
                return SNMP_ERR_WRONGVALUE;
         }

         if(IS_LOGIC_PORT_INVALID(index))
            return SNMP_ERR_NOTWRITABLE;

          break;

        case RESERVE2:
          size  = var_val_len;
          SYS_SNMP_ERR_CHK(sal_stp_portPathCost_set(index,value), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
#endif


int
write_dot1dTpAgingTime(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if (value < 10 || value > 630)
            return SNMP_ERR_WRONGVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          SYS_SNMP_ERR_CHK(sal_l2_aging_set(value), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_dot1dStaticAddress(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;
    int32 index, i;
    uint8 isStatic, isZero = TRUE;
    static char mac[6] = {0,0,0,0,0,0};
    uint32 mode;
    sys_logic_port_t port;
    sys_l2_entry_t macEntry;
    sys_l2_entry_t *pPrev = NULL;
    sys_l2_entry_t *pCurr = NULL;

    SYS_MEM_CLEAR(macEntry);

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to dot1dBridge not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len !=  CAPA_MAC_BYTE_NUM) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

       for (i = 0; i < CAPA_MAC_BYTE_NUM; i++)
       {
            if (0 != var_val[i])
            {
                 isZero = FALSE;
                 break;
            }
       }

        if ((0x01 & var_val[0]) || isZero)
            return SNMP_ERR_WRONGVALUE;

        for (i = 0; i < 6; i++)
        {
            if (name[name_len-1-6+i] > 255)
                return SNMP_ERR_INCONSISTENTVALUE;

            mac[i] = name[name_len-1-6+i];
        }

        i = 0;
        while (NULL != (pCurr = sal_l2_staticMacNext_ret(pPrev)))
        {
            if (0 == osal_memcmp(mac, &pCurr->mac,CAPA_MAC_BYTE_NUM))
            {
                osal_memcpy(&macEntry, pCurr, sizeof(sys_l2_entry_t));
                break;
            }

            pPrev = pCurr;

            i++;
        }

          if (i == CAPA_L2_STATIC_MAC_NUM)
            return SNMP_ERR_INCONSISTENTVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          SYS_SNMP_ERR_CHK(sal_l2_staticMac_del(&macEntry), SNMP_ERR_RESOURCEUNAVAILABLE);
          osal_memcpy(&macEntry.mac, var_val, CAPA_MAC_BYTE_NUM);
          SYS_SNMP_ERR_CHK(sal_l2_staticMac_add(&macEntry), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dStaticReceivePort(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    int32 index, i;
    uint8 isStatic;
    char mac[6] = {0,0,0,0,0,0};
    uint32 mode;
    sys_logic_port_t port;
    sys_l2_entry_t macEntry;
    sys_l2_entry_t *pPrev = NULL;
    sys_l2_entry_t *pCurr = NULL;

    size  = var_val_len;
    value = * (long *) var_val;
    index =  name[name_len -1];

    SYS_MEM_CLEAR(macEntry);

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

        if (IS_LOGIC_PORT_INVALID(UP2LP(value)))
            return SNMP_ERR_WRONGVALUE;

        if (IS_LP_TRKMBR(index))
            return SNMP_ERR_WRONGVALUE;

        for (i = 0; i < 6; i++)
        {
            if (name[name_len-1-6+i] > 255)
                return SNMP_ERR_INCONSISTENTVALUE;
            mac[i] = name[name_len-1-6+i];
        }

        i = 0;
        while (NULL != (pCurr = sal_l2_staticMacNext_ret(pPrev)))
        {
            if (0 == osal_memcmp(mac, &pCurr->mac,CAPA_MAC_BYTE_NUM))
            {
                osal_memcpy(&macEntry, pCurr, sizeof(sys_l2_entry_t));
                break;
            }

            pPrev = pCurr;

            i++;
        }

          if (i == CAPA_L2_STATIC_MAC_NUM)
            return SNMP_ERR_INCONSISTENTVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

            if (value == LP2UP(macEntry.port))
                return SNMP_ERR_NOERROR;

            SYS_SNMP_ERR_CHK(sal_l2_staticMac_del(&macEntry), SNMP_ERR_RESOURCEUNAVAILABLE);

            macEntry.port = UP2LP(value);

            SYS_SNMP_ERR_CHK(sal_l2_staticMac_add(&macEntry),SNMP_ERR_RESOURCEUNAVAILABLE);

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dStaticAllowedToGoTo(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to dot1dBridge not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(char)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          return SNMP_ERR_NOTWRITABLE;
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dStaticStatus(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    int32 index, i;
    uint8 isStatic;
    char mac[6] = {0,0,0,0,0,0};
    static uint32 mode;
    sys_l2_entry_t macEntry;
    sys_l2_entry_t *pPrev = NULL;
    sys_l2_entry_t *pCurr = NULL;

    size  = var_val_len;
    value = * (long *) var_val;
    index =  name[name_len -1];

    SYS_MEM_CLEAR(macEntry);

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to dot1dBridge not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to dot1dBridge: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

        for (i = 0; i < 6; i++)
        {
            if (name[name_len-1-6+i] > 255)
                return SNMP_ERR_INCONSISTENTVALUE;
            mac[i] = name[name_len-1-6+i];
        }

        mode = 0;

        i = 0;
        while (NULL != (pCurr = sal_l2_staticMacNext_ret(pPrev)))
        {
            if (0 == osal_memcmp(mac, &pCurr->mac, CAPA_MAC_BYTE_NUM))
            {
                mode = 3;

              #if 0
                if (pCurr->staticMode == SYS_L2_STATIC_MODE_PERMANENT)
                    mode = 3;
                else if (RSD_L2_UCAST_MODE_REBOOT & macEntry.mode)
                {
                    mode =  4;
                }
                else if (RSD_L2_UCAST_MODE_TIMEOUT & macEntry.mode)
                {
                    mode =  5;
                }
                else if (RSD_L2_UCAST_MODE_SECURE & macEntry.mode)
                {
                    mode =  1;
                }
              #endif
                osal_memcpy(&macEntry, pCurr, sizeof(sys_l2_entry_t));
                break;



            }

            i++;
        }

          if (i == CAPA_L2_STATIC_MAC_NUM)
            return SNMP_ERR_INCONSISTENTVALUE;

          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

            if (mode == value)
                return SNMP_ERR_NOERROR;
            if (value == 2)
            {
                SYS_SNMP_ERR_CHK(sal_l2_staticMac_del(&macEntry), SNMP_ERR_RESOURCEUNAVAILABLE);
            }
          #if 0
            else if (value == 3)
            {
                mode = SYS_L2_STATIC_MODE_PERMANENT;
            }
            else if (value == 4)
            {
                mode = RSD_L2_UCAST_MODE_REBOOT;
            }
            else if (value == 5)
            {
                mode = RSD_L2_UCAST_MODE_TIMEOUT;
            }
            else if (value == 1)
                mode = RSD_L2_UCAST_MODE_SECURE;
          #endif
            else
                return SNMP_ERR_WRONGVALUE;

            if (value != 2)
            {
                SYS_SNMP_ERR_CHK(sal_l2_staticMac_del(&macEntry), SNMP_ERR_RESOURCEUNAVAILABLE);
                //macEntry.staticMode = mode;
                SYS_SNMP_ERR_CHK(sal_l2_staticMac_add(&macEntry),SNMP_ERR_RESOURCEUNAVAILABLE);
            }

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

