/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef DOT1DBRIDGE_H
#define DOT1DBRIDGE_H

/* function declarations */
void init_dot1dBridge(void);
FindVarMethod var_dot1dBridge;
FindVarMethod var_dot1dBasePortTable;
FindVarMethod var_dot1dStpPortTable;
FindVarMethod var_dot1dTpFdbTable;
FindVarMethod var_dot1dTpPortTable;
FindVarMethod var_dot1dStaticTable;
    WriteMethod write_dot1dStpPriority;
    WriteMethod write_dot1dStpBridgeMaxAge;
    WriteMethod write_dot1dStpBridgeHelloTime;
    WriteMethod write_dot1dStpBridgeForwardDelay;
    WriteMethod write_dot1dTpAgingTime;
    WriteMethod write_dot1dStpPortPriority;
    WriteMethod write_dot1dStpPortEnable;
    WriteMethod write_dot1dStpPortPathCost;
    WriteMethod write_dot1dStaticAddress;
    WriteMethod write_dot1dStaticReceivePort;
    WriteMethod write_dot1dStaticAllowedToGoTo;
    WriteMethod write_dot1dStaticStatus;

#endif /* DOT1DBRIDGE_H */
