/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef PBRIDGEMIB_H
#define PBRIDGEMIB_H

/* function declarations */
void init_pBridgeMIB(void);
FindVarMethod var_pBridgeMIB;
FindVarMethod var_dot1dPortCapabilitiesTable;
FindVarMethod var_dot1dPortPriorityTable;
FindVarMethod var_dot1dUserPriorityRegenTable;
FindVarMethod var_dot1dTrafficClassTable;
FindVarMethod var_dot1dPortOutboundAccessPriorityTable;
FindVarMethod var_dot1dPortGarpTable;
FindVarMethod var_dot1dPortGmrpTable;
    WriteMethod write_dot1dTrafficClassesEnabled;
    WriteMethod write_dot1dGmrpStatus;
    WriteMethod write_dot1dPortDefaultUserPriority;
    WriteMethod write_dot1dPortNumTrafficClasses;
    WriteMethod write_dot1dRegenUserPriority;
    WriteMethod write_dot1dTrafficClass;
    WriteMethod write_dot1dPortGarpJoinTime;
    WriteMethod write_dot1dPortGarpLeaveTime;
    WriteMethod write_dot1dPortGarpLeaveAllTime;
    WriteMethod write_dot1dPortGmrpStatus;

#endif /* PBRIDGEMIB_H */
