/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "pBridgeMIB.h"
#include "qBridge.h"


/*
 * pBridgeMIB_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid pBridgeMIB_variables_oid[] = { 1,3,6,1,2,1,17,6 };

/*
 * variable4 pBridgeMIB_variables:
 *   this variable defines function callbacks and type return information
 *   for the pBridgeMIB mib section
 */

#define DOT1D_P_BRIDGE_TABLE_SIZE  (LP2UP(LOGIC_PORT_END) + 1)

#define DOT1DDEVICECAPABILITIES     1
#define DOT1DTRAFFICCLASSESENABLED      2
#define DOT1DGMRPSTATUS     3
#define DOT1DPORTCAPABILITIES       4
#define DOT1DPORTDEFAULTUSERPRIORITY        5
#define DOT1DPORTNUMTRAFFICCLASSES      6
#define DOT1DUSERPRIORITY       7
#define DOT1DREGENUSERPRIORITY      8
#define DOT1DTRAFFICCLASSPRIORITY       9
#define DOT1DTRAFFICCLASS       10
#define DOT1DPORTOUTBOUNDACCESSPRIORITY     11
#define DOT1DPORTGARPJOINTIME       12
#define DOT1DPORTGARPLEAVETIME      13
#define DOT1DPORTGARPLEAVEALLTIME       14
#define DOT1DPORTGMRPSTATUS     15
#define DOT1DPORTGMRPFAILEDREGISTRATIONS        16
#define DOT1DPORTGMRPLASTPDUORIGIN      17

struct variable7 pBridgeMIB_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */

{DOT1DDEVICECAPABILITIES,  ASN_OCTET_STR,  RONLY ,  var_pBridgeMIB, 3,  { 1,1,1 }},

{DOT1DTRAFFICCLASSESENABLED,  ASN_INTEGER,  RWRITE,  var_pBridgeMIB, 3,  { 1,1,2 }},

{DOT1DGMRPSTATUS,  ASN_INTEGER,  RWRITE,  var_pBridgeMIB, 3,  { 1,1,3 }},


{DOT1DPORTCAPABILITIES,  ASN_OCTET_STR,  RONLY,   var_dot1dPortCapabilitiesTable, 5,  { 1,1,4, 1, 1 }},

{DOT1DPORTDEFAULTUSERPRIORITY,  ASN_INTEGER,  RWRITE,  var_dot1dPortPriorityTable, 5,  { 1,2,1, 1, 1 }},

{DOT1DPORTNUMTRAFFICCLASSES,  ASN_INTEGER,  RWRITE,  var_dot1dPortPriorityTable, 5,  { 1,2,1, 1, 2 }},

{DOT1DUSERPRIORITY,  ASN_INTEGER,  RONLY,   var_dot1dUserPriorityRegenTable, 5,  { 1,2,2, 1, 1 }},

{DOT1DREGENUSERPRIORITY,  ASN_INTEGER,  RWRITE,  var_dot1dUserPriorityRegenTable, 5,  { 1,2,2, 1, 2 }},

{DOT1DTRAFFICCLASSPRIORITY,  ASN_INTEGER,  RONLY,   var_dot1dTrafficClassTable, 5,  { 1,2,3, 1, 1 }},

{DOT1DTRAFFICCLASS,  ASN_INTEGER,  RWRITE,  var_dot1dTrafficClassTable, 5,  { 1,2,3, 1, 2 }},

{DOT1DPORTOUTBOUNDACCESSPRIORITY,  ASN_INTEGER,  RONLY,   var_dot1dPortOutboundAccessPriorityTable, 5,  { 1,2,4, 1, 1 }},

{DOT1DPORTGARPJOINTIME,  ASN_INTEGER,  RWRITE,  var_dot1dPortGarpTable, 5,  { 1,3,1, 1, 1 }},

{DOT1DPORTGARPLEAVETIME,  ASN_INTEGER,  RWRITE,  var_dot1dPortGarpTable, 5,  { 1,3,1, 1, 2 }},

{DOT1DPORTGARPLEAVEALLTIME,  ASN_INTEGER,  RWRITE,  var_dot1dPortGarpTable, 5,  { 1,3,1, 1, 3 }},

{DOT1DPORTGMRPSTATUS,  ASN_INTEGER,  RWRITE,  var_dot1dPortGmrpTable, 5,  { 1,4,1, 1, 1 }},

{DOT1DPORTGMRPFAILEDREGISTRATIONS,  ASN_COUNTER,  RONLY,   var_dot1dPortGmrpTable, 5,  { 1,4,1, 1, 2 }},

{DOT1DPORTGMRPLASTPDUORIGIN,  ASN_OCTET_STR,  RONLY,   var_dot1dPortGmrpTable, 5,  { 1,4,1, 1, 3 }},
};
/*    (L = length of the oidsuffix) */


/** Initializes the pBridgeMIB module */
void
init_pBridgeMIB(void)
{

    DEBUGMSGTL(("pBridgeMIB", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("pBridgeMIB", pBridgeMIB_variables, variable7,
               pBridgeMIB_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_pBridgeMIB():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_pBridgeMIB(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char char_ret;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    *var_len = sizeof(u_long);
    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1DDEVICECAPABILITIES:
        char_ret = 0x7E;
        *var_len = sizeof(char);
        return (u_char*) &char_ret;
#if 0   //not support
    case DOT1DTRAFFICCLASSESENABLED:
        *write_method = write_dot1dTrafficClassesEnabled;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    case DOT1DGMRPSTATUS:
        *write_method = write_dot1dGmrpStatus;
        ulong_ret = DISABLED;    /*Not support gmrp */
        return (u_char*) &ulong_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_dot1dPortCapabilitiesTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dPortCapabilitiesTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    //not support;
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1DPORTCAPABILITIES:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dPortPriorityTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dPortPriorityTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    int32 index;
    sys_qos_cos_t cos;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
            ;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }

    if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    DEBUGMSGTL(("[RTK]", "index = %d\n", index));

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1DPORTDEFAULTUSERPRIORITY:
        *write_method = write_dot1dPortDefaultUserPriority;
        ulong_ret = 0;  /*Not support*/
        return (u_char*) &ulong_ret;
    case DOT1DPORTNUMTRAFFICCLASSES:
        *write_method = write_dot1dPortNumTrafficClasses;
        /*port have how mang queue number*/
        ulong_ret = 8;
        return (u_char*) &ulong_ret;

    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dUserPriorityRegenTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dUserPriorityRegenTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;


    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0     /*Remark priority table*/
    case DOT1DUSERPRIORITY:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1DREGENUSERPRIORITY:
        *write_method = write_dot1dRegenUserPriority;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dTrafficClassTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dTrafficClassTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;


    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;


    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1DTRAFFICCLASSPRIORITY:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1DTRAFFICCLASS:
        *write_method = write_dot1dTrafficClass;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
#endif
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dPortOutboundAccessPriorityTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dPortOutboundAccessPriorityTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
#if 0
    case DOT1DPORTOUTBOUNDACCESSPRIORITY:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    default:
#endif
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dPortGarpTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dPortGarpTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static u_long ulong_ret;
    int32 index;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    index = vp->namelen >= *length ? 0 : UP2LP(name[vp->namelen]);

    if (exact) /* GET packet for one instance */
    {
         if (14 != *length)
            return NULL;
    }
    else /* Get-Next packet */
    {
        if (-1 == header_logicPort(&index, vp, name, length))
            return NULL;
    }

     if (IS_LOGIC_PORT_INVALID(index))
        return NULL;

    *var_len = sizeof(long);
    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case DOT1DPORTGARPJOINTIME:
        *write_method = write_dot1dPortGarpJoinTime;
        ulong_ret = 0;
        #ifdef CONFIG_SYS_PROTO_GVRP
        sal_gvrp_timer_get(GVRP_TIMER_JOIN, &ulong_ret);
        #endif
        return (u_char*) &ulong_ret;
    case DOT1DPORTGARPLEAVETIME:
        *write_method = write_dot1dPortGarpLeaveTime;
        ulong_ret = 0;
        #ifdef CONFIG_SYS_PROTO_GVRP
        sal_gvrp_timer_get(GVRP_TIMER_LEAVE, &ulong_ret);
        #endif
        return (u_char*) &ulong_ret;
    case DOT1DPORTGARPLEAVEALLTIME:
        *write_method = write_dot1dPortGarpLeaveAllTime;
        ulong_ret = 0;
        #ifdef CONFIG_SYS_PROTO_GVRP
        sal_gvrp_timer_get(GVRP_TIMER_LEAVEALL, &ulong_ret);
        #endif
        return (u_char*) &ulong_ret;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_dot1dPortGmrpTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_pBridgeMIB above.
 */
unsigned char *
var_dot1dPortGmrpTable(struct variable *vp,
            oid     *name,
            size_t  *length,
            int     exact,
            size_t  *var_len,
            WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;

    /*
   * This assumes that the table is a 'simple' table.
   *    See the implementation documentation for the meaning of this.
   *    You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *    you will need to provide the replacement code yourself.
   *    Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, DOT1D_P_BRIDGE_TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
#if 0
    switch(vp->magic) {
    case DOT1DPORTGMRPSTATUS:
        *write_method = write_dot1dPortGmrpStatus;
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1DPORTGMRPFAILEDREGISTRATIONS:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    case DOT1DPORTGMRPLASTPDUORIGIN:
        VAR = VALUE;    /* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
#endif
    return NULL;
}



int
write_dot1dTrafficClassesEnabled(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_dot1dGmrpStatus(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_dot1dPortDefaultUserPriority(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dPortNumTrafficClasses(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dRegenUserPriority(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dTrafficClass(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dPortGarpJoinTime(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    uint32 holdtime,leavetime;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          if(value % 5 != 0)
            return SNMP_ERR_BADVALUE;

          if(value < 20 || value > 16375 )
            return SNMP_ERR_BADVALUE;
#ifdef CONFIG_SYS_PROTO_GVRP
         sal_gvrp_timer_get(GVRP_TIMER_HOLD, &holdtime);
         sal_gvrp_timer_get(GVRP_TIMER_LEAVE, &leavetime);

         if(value >= leavetime/2 || value < holdtime * 2)
            return SNMP_ERR_BADVALUE;
#endif

          break;

        case RESERVE2:
          size  = var_val_len;
          #ifdef CONFIG_SYS_PROTO_GVRP
            if (SYS_ERR_OK != sal_gvrp_timer_set(GVRP_TIMER_JOIN, value))
                return SNMP_ERR_NOACCESS;
         #endif

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:

             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dPortGarpLeaveTime(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    uint32 jointime,leavealltime;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          if(value % 5 != 0)
            return SNMP_ERR_BADVALUE;

          if(value < 45 || value > 32760 )
            return SNMP_ERR_BADVALUE;
#ifdef CONFIG_SYS_PROTO_GVRP
         sal_gvrp_timer_get(GVRP_TIMER_JOIN, &jointime);
         sal_gvrp_timer_get(GVRP_TIMER_LEAVEALL, &leavealltime);

         if(value >= leavealltime || value < jointime * 2)
            return SNMP_ERR_BADVALUE;
#endif
          break;

        case RESERVE2:
          size  = var_val_len;
#ifdef CONFIG_SYS_PROTO_GVRP
          if (SYS_ERR_OK != sal_gvrp_timer_set(GVRP_TIMER_LEAVE, value))
                return SNMP_ERR_NOACCESS;
#endif

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dPortGarpLeaveAllTime(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;
    uint32 leavetime;

    value = * (long *) var_val;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

         if(value % 5 != 0)
            return SNMP_ERR_BADVALUE;

         if(value < 65 || value > 32765 )
            return SNMP_ERR_BADVALUE;
#ifdef CONFIG_SYS_PROTO_GVRP
         sal_gvrp_timer_get(GVRP_TIMER_LEAVE, &leavetime);
         if(value < leavetime)
            return SNMP_ERR_BADVALUE;
#endif
          break;

        case RESERVE2:
          size  = var_val_len;
#ifdef CONFIG_SYS_PROTO_GVRP
          if (SYS_ERR_OK != sal_gvrp_timer_set(GVRP_TIMER_LEAVEALL, value))
                return SNMP_ERR_NOACCESS;
#endif

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_dot1dPortGmrpStatus(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to pBridgeMIB not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to pBridgeMIB: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
