/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.check_values.conf 9254 2004-01-12 00:43:46Z rstory $
 */

/********************************************************************
 *                       NOTE   NOTE   NOTE
 *   This file is auto-generated and SHOULD NOT BE EDITED by hand.
 *   Modify the qBridgeMIB_checkfns_local.[ch] files insead so that you
 *   can regenerate this one as mib2c improvements are made.
 ********************************************************************/

/* standard headers */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include "qBridgeMIB_checkfns.h"
#include "qBridgeMIB_enums.h"
#include "qBridge.h"

/** Decides if an incoming value for the dot1qForwardAllStaticPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qForwardAllStaticPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qForwardAllForbiddenPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qForwardAllForbiddenPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;


      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qForwardUnregisteredStaticPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qForwardUnregisteredStaticPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;



    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qForwardUnregisteredForbiddenPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qForwardUnregisteredForbiddenPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;



    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qStaticUnicastAllowedToGoTo mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qStaticUnicastAllowedToGoTo(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

      return SNMP_ERR_NOTWRITABLE;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qStaticUnicastStatus mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qStaticUnicastStatus(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QSTATICUNICASTSTATUS_OTHER:
          case DOT1QSTATICUNICASTSTATUS_INVALID:
          case DOT1QSTATICUNICASTSTATUS_PERMANENT:
          case DOT1QSTATICUNICASTSTATUS_DELETEONRESET:
          case DOT1QSTATICUNICASTSTATUS_DELETEONTIMEOUT:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qStaticMulticastStaticEgressPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qStaticMulticastStaticEgressPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qStaticMulticastForbiddenEgressPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qStaticMulticastForbiddenEgressPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qStaticMulticastStatus mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qStaticMulticastStatus(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QSTATICMULTICASTSTATUS_OTHER:
          case DOT1QSTATICMULTICASTSTATUS_INVALID:
          case DOT1QSTATICMULTICASTSTATUS_PERMANENT:
          case DOT1QSTATICMULTICASTSTATUS_DELETEONRESET:
          case DOT1QSTATICMULTICASTSTATUS_DELETEONTIMEOUT:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qVlanStaticName mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qVlanStaticName(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

    /** Check the ranges of the passed value for legality */
        if (!(val_len >= 0 && val_len <= CAPA_NAME_STR_LEN))
         {
            return SNMP_ERR_WRONGVALUE;
          }


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qVlanStaticEgressPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qVlanStaticEgressPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qVlanForbiddenEgressPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qVlanForbiddenEgressPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qVlanStaticUntaggedPorts mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qVlanStaticUntaggedPorts(int type, char *val, size_t val_len,
             char *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_OCTET_STR)
        return SNMP_ERR_WRONGTYPE;

      if (val_len > sizeof(sys_user_portmask_t))
            return SNMP_ERR_WRONGLENGTH;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qVlanStaticRowStatus mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qVlanStaticRowStatus(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QVLANSTATICROWSTATUS_ACTIVE:
          case DOT1QVLANSTATICROWSTATUS_CREATEANDGO:
          case DOT1QVLANSTATICROWSTATUS_CREATEANDWAIT:
           {
                //unknown to write code
               // return SNMP_ERR_INCONSISTENTVALUE;
            }
          break;
          case DOT1QVLANSTATICROWSTATUS_DESTROY:
          case DOT1QVLANSTATICROWSTATUS_NOTINSERVICE:
          case DOT1QVLANSTATICROWSTATUS_NOTREADY:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;

      //if (ret = check_rowstatus_transition((old_val) ? *old_val : RS_NONEXISTENT, *val))
         // return ret;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qPvid mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qPvid(int type, u_long *val, size_t val_len,
             u_long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_UNSIGNED)
        return SNMP_ERR_WRONGTYPE;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qPortAcceptableFrameTypes mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qPortAcceptableFrameTypes(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QPORTACCEPTABLEFRAMETYPES_ADMITALL:
          case DOT1QPORTACCEPTABLEFRAMETYPES_ADMITONLYVLANTAGGED:
          case DOT1QPORTACCEPTABLEFRAMETYPES_ADMITONLYVLANUNTAGGED:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qPortIngressFiltering mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qPortIngressFiltering(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QPORTINGRESSFILTERING_TRUE:
          case DOT1QPORTINGRESSFILTERING_FALSE:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qPortGvrpStatus mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qPortGvrpStatus(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QPORTGVRPSTATUS_ENABLED:
          case DOT1QPORTGVRPSTATUS_DISABLED:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }

/** Decides if an incoming value for the dot1qPortGvrpStatus mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qPortRestrictedVlanRegistration(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QPORTGVRPSTATUS_ENABLED:
          case DOT1QPORTGVRPSTATUS_DISABLED:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }

/** Decides if an incoming value for the dot1qConstraintType mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qConstraintType(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QCONSTRAINTTYPE_INDEPENDENT:
          case DOT1QCONSTRAINTTYPE_SHARED:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;


    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }
/** Decides if an incoming value for the dot1qConstraintStatus mib node is legal.
 *  @param type    The incoming data type.
 *  @param val     The value to be checked.
 *  @param val_len The length of data stored in val (in bytes).
 *  @return 0 if the incoming value is legal, an SNMP error code otherwise.
 */
    int
    check_dot1qConstraintStatus(int type, long *val, size_t val_len,
             long *old_val, size_t old_val_len) {

    int ret;

    /** Check to see that we were called legally */
      if (!val)
        return SNMP_ERR_GENERR;

    /** Check the incoming type for correctness */
      if (type != ASN_INTEGER)
        return SNMP_ERR_WRONGTYPE;

    /** Check the enums.  Legal values will continue, others return error. */
           switch (*val) {
          case DOT1QCONSTRAINTSTATUS_ACTIVE:
          case DOT1QCONSTRAINTSTATUS_NOTINSERVICE:
          case DOT1QCONSTRAINTSTATUS_NOTREADY:
          case DOT1QCONSTRAINTSTATUS_CREATEANDGO:
          case DOT1QCONSTRAINTSTATUS_CREATEANDWAIT:
          case DOT1QCONSTRAINTSTATUS_DESTROY:
            break;

    /** not a legal enum value.  return an error */
          default:
            return SNMP_ERR_INCONSISTENTVALUE;
        }
    ret = SNMP_ERR_NOERROR;

      if (ret = check_rowstatus_transition((old_val) ? *old_val : RS_NONEXISTENT, *val))
          return ret;

    /** looks ok, call the local version of the same function. */
      return SNMP_ERR_NOERROR;
    }

