/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf 7011 2002-05-08 05:42:47Z hardaker $
 */
#ifndef QBRIDGEMIB_COLUMNS_H
#define QBRIDGEMIB_COLUMNS_H

/* column number definitions for table dot1qFdbTable */
       #define COLUMN_DOT1QFDBID        1
       #define COLUMN_DOT1QFDBDYNAMICCOUNT      2

/* column number definitions for table dot1qTpFdbTable */
       #define COLUMN_DOT1QTPFDBADDRESS     1
       #define COLUMN_DOT1QTPFDBPORT        2
       #define COLUMN_DOT1QTPFDBSTATUS      3

/* column number definitions for table dot1qTpGroupTable */
       #define COLUMN_DOT1QTPGROUPADDRESS       1
       #define COLUMN_DOT1QTPGROUPEGRESSPORTS       2
       #define COLUMN_DOT1QTPGROUPLEARNT        3

/* column number definitions for table dot1qForwardAllTable */
       #define COLUMN_DOT1QFORWARDALLPORTS      1
       #define COLUMN_DOT1QFORWARDALLSTATICPORTS        2
       #define COLUMN_DOT1QFORWARDALLFORBIDDENPORTS     3

/* column number definitions for table dot1qForwardUnregisteredTable */
       #define COLUMN_DOT1QFORWARDUNREGISTEREDPORTS     1
       #define COLUMN_DOT1QFORWARDUNREGISTEREDSTATICPORTS       2
       #define COLUMN_DOT1QFORWARDUNREGISTEREDFORBIDDENPORTS        3

/* column number definitions for table dot1qStaticUnicastTable */
       #define COLUMN_DOT1QSTATICUNICASTADDRESS     1
       #define COLUMN_DOT1QSTATICUNICASTRECEIVEPORT     2
       #define COLUMN_DOT1QSTATICUNICASTALLOWEDTOGOTO       3
       #define COLUMN_DOT1QSTATICUNICASTSTATUS      4

/* column number definitions for table dot1qStaticMulticastTable */
       #define COLUMN_DOT1QSTATICMULTICASTADDRESS       1
       #define COLUMN_DOT1QSTATICMULTICASTRECEIVEPORT       2
       #define COLUMN_DOT1QSTATICMULTICASTSTATICEGRESSPORTS     3
       #define COLUMN_DOT1QSTATICMULTICASTFORBIDDENEGRESSPORTS      4
       #define COLUMN_DOT1QSTATICMULTICASTSTATUS        5

/* column number definitions for table dot1qVlanCurrentTable */
       #define COLUMN_DOT1QVLANTIMEMARK     1
       #define COLUMN_DOT1QVLANINDEX        2
       #define COLUMN_DOT1QVLANFDBID        3
       #define COLUMN_DOT1QVLANCURRENTEGRESSPORTS       4
       #define COLUMN_DOT1QVLANCURRENTUNTAGGEDPORTS     5
       #define COLUMN_DOT1QVLANSTATUS       6
       #define COLUMN_DOT1QVLANCREATIONTIME     7

/* column number definitions for table dot1qVlanStaticTable */
       #define COLUMN_DOT1QVLANSTATICNAME       1
       #define COLUMN_DOT1QVLANSTATICEGRESSPORTS        2
       #define COLUMN_DOT1QVLANFORBIDDENEGRESSPORTS     3
       #define COLUMN_DOT1QVLANSTATICUNTAGGEDPORTS      4
       #define COLUMN_DOT1QVLANSTATICROWSTATUS      5

/* column number definitions for table dot1qPortVlanTable */
       #define COLUMN_DOT1QPVID     1
       #define COLUMN_DOT1QPORTACCEPTABLEFRAMETYPES     2
       #define COLUMN_DOT1QPORTINGRESSFILTERING     3
       #define COLUMN_DOT1QPORTGVRPSTATUS       4
       #define COLUMN_DOT1QPORTGVRPFAILEDREGISTRATIONS      5
       #define COLUMN_DOT1QPORTGVRPLASTPDUORIGIN        6
       #define COLUMN_DOT1QPORTRESTRICTEDVLANREGISTRATION        7

/* column number definitions for table dot1qPortVlanStatisticsTable */
       #define COLUMN_DOT1QTPVLANPORTINFRAMES       1
       #define COLUMN_DOT1QTPVLANPORTOUTFRAMES      2
       #define COLUMN_DOT1QTPVLANPORTINDISCARDS     3
       #define COLUMN_DOT1QTPVLANPORTINOVERFLOWFRAMES       4
       #define COLUMN_DOT1QTPVLANPORTOUTOVERFLOWFRAMES      5
       #define COLUMN_DOT1QTPVLANPORTINOVERFLOWDISCARDS     6

/* column number definitions for table dot1qPortVlanHCStatisticsTable */
       #define COLUMN_DOT1QTPVLANPORTHCINFRAMES     1
       #define COLUMN_DOT1QTPVLANPORTHCOUTFRAMES        2
       #define COLUMN_DOT1QTPVLANPORTHCINDISCARDS       3

/* column number definitions for table dot1qLearningConstraintsTable */
       #define COLUMN_DOT1QCONSTRAINTVLAN       1
       #define COLUMN_DOT1QCONSTRAINTSET        2
       #define COLUMN_DOT1QCONSTRAINTTYPE       3
       #define COLUMN_DOT1QCONSTRAINTSTATUS     4
#endif /* QBRIDGEMIB_COLUMNS_H */
