/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf 17483 2009-04-09 08:54:46Z dts12 $
 */
#ifndef QBRIDGEMIB_H
#define QBRIDGEMIB_H

/* function declarations */
void init_qBridgeMIB_scalar(void);
Netsnmp_Node_Handler handle_dot1qVlanVersionNumber;
Netsnmp_Node_Handler handle_dot1qMaxVlanId;
Netsnmp_Node_Handler handle_dot1qMaxSupportedVlans;
Netsnmp_Node_Handler handle_dot1qNumVlans;
Netsnmp_Node_Handler handle_dot1qGvrpStatus;
Netsnmp_Node_Handler handle_dot1qVlanNumDeletes;
Netsnmp_Node_Handler handle_dot1qNextFreeLocalVlanIndex;
Netsnmp_Node_Handler handle_dot1qConstraintSetDefault;
Netsnmp_Node_Handler handle_dot1qConstraintTypeDefault;

/** other required module components */
config_require(qBridgeMIB_access)
config_require(qBridgeMIB_checkfns)

/* function declarations */
void init_qBridgeMIB(void);
void initialize_table_dot1qFdbTable(void);
Netsnmp_Node_Handler dot1qFdbTable_handler;

void initialize_table_dot1qTpFdbTable(void);
Netsnmp_Node_Handler dot1qTpFdbTable_handler;

void initialize_table_dot1qTpGroupTable(void);
Netsnmp_Node_Handler dot1qTpGroupTable_handler;

void initialize_table_dot1qForwardAllTable(void);
Netsnmp_Node_Handler dot1qForwardAllTable_handler;

void initialize_table_dot1qForwardUnregisteredTable(void);
Netsnmp_Node_Handler dot1qForwardUnregisteredTable_handler;

void initialize_table_dot1qStaticUnicastTable(void);
Netsnmp_Node_Handler dot1qStaticUnicastTable_handler;

void initialize_table_dot1qStaticMulticastTable(void);
Netsnmp_Node_Handler dot1qStaticMulticastTable_handler;

void initialize_table_dot1qVlanCurrentTable(void);
Netsnmp_Node_Handler dot1qVlanCurrentTable_handler;

void initialize_table_dot1qVlanStaticTable(void);
Netsnmp_Node_Handler dot1qVlanStaticTable_handler;

void initialize_table_dot1qPortVlanTable(void);
Netsnmp_Node_Handler dot1qPortVlanTable_handler;

void initialize_table_dot1qPortVlanStatisticsTable(void);
Netsnmp_Node_Handler dot1qPortVlanStatisticsTable_handler;

void initialize_table_dot1qPortVlanHCStatisticsTable(void);
Netsnmp_Node_Handler dot1qPortVlanHCStatisticsTable_handler;

void initialize_table_dot1qLearningConstraintsTable(void);
Netsnmp_Node_Handler dot1qLearningConstraintsTable_handler;


/* column number definitions for table dot1qFdbTable */
#include "qBridgeMIB_columns.h"

/* enum definions */
#include "qBridgeMIB_enums.h"


#endif /** QBRIDGEMIB_H */
