/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.6 2003/02/20 00:52:07 hardaker Exp $
 */

/***********************************************************************
 *   This file is auto-generated and SHOULD NOT BE EDITED by hand.
 *   Modify the qBridgeMIB_checkfns_local.[ch] files insead.
 *   (so that you can regenerate this one as mib2c improvements are made)
 ***********************************************************************/
#ifndef QBRIDGEMIB_CHECKFNS_H
#define QBRIDGEMIB_CHECKFNS_H

/** make sure we load the functions that you can modify */
config_require(qBridgeMIB_checkfns_local)

/* these functions are designed to check incoming values for
columns in the dot1qFdbTable table for legality with respect to
datatype and value.
 */

/* these functions are designed to check incoming values for
columns in the dot1qTpFdbTable table for legality with respect to
datatype and value.
 */

/* these functions are designed to check incoming values for
columns in the dot1qTpGroupTable table for legality with respect to
datatype and value.
 */

/* these functions are designed to check incoming values for
columns in the dot1qForwardAllTable table for legality with respect to
datatype and value.
 */

      int check_dot1qForwardAllStaticPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qForwardAllForbiddenPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for
columns in the dot1qForwardUnregisteredTable table for legality with respect to
datatype and value.
 */

      int check_dot1qForwardUnregisteredStaticPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qForwardUnregisteredForbiddenPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for
columns in the dot1qStaticUnicastTable table for legality with respect to
datatype and value.
 */

      int check_dot1qStaticUnicastAllowedToGoTo(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qStaticUnicastStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for
columns in the dot1qStaticMulticastTable table for legality with respect to
datatype and value.
 */

      int check_dot1qStaticMulticastStaticEgressPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qStaticMulticastForbiddenEgressPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qStaticMulticastStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for
columns in the dot1qVlanCurrentTable table for legality with respect to
datatype and value.
 */

/* these functions are designed to check incoming values for
columns in the dot1qVlanStaticTable table for legality with respect to
datatype and value.
 */

      int check_dot1qVlanStaticName(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qVlanStaticEgressPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qVlanForbiddenEgressPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qVlanStaticUntaggedPorts(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_dot1qVlanStaticRowStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for
columns in the dot1qPortVlanTable table for legality with respect to
datatype and value.
 */

      int check_dot1qPvid(int type, u_long *val, size_t val_len, u_long *old_val, size_t old_val_len);
      int check_dot1qPortAcceptableFrameTypes(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_dot1qPortIngressFiltering(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_dot1qPortGvrpStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_dot1qPortRestrictedVlanRegistration(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for
columns in the dot1qPortVlanStatisticsTable table for legality with respect to
datatype and value.
 */

/* these functions are designed to check incoming values for
columns in the dot1qPortVlanHCStatisticsTable table for legality with respect to
datatype and value.
 */

/* these functions are designed to check incoming values for
columns in the dot1qLearningConstraintsTable table for legality with respect to
datatype and value.
 */

      int check_dot1qConstraintType(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_dot1qConstraintStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);

#endif /* QBRIDGEMIB_CHECKFNS_H */

