/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.access_functions.conf 11358 2004-10-14 12:57:34Z dts12 $
 */
#ifndef QBRIDGEMIB_ACCESS_H
#define QBRIDGEMIB_ACCESS_H

/** User-defined data access functions for data in table dot1qFdbTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qFdbTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qFdbTable_get_next_data_point;
int dot1qFdbTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qFdbTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      u_long *get_dot1qFdbId(void *data_context, size_t *ret_len);
      u_long *get_dot1qFdbDynamicCount(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table dot1qTpFdbTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qTpFdbTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qTpFdbTable_get_next_data_point;
int dot1qTpFdbTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qTpFdbTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      char *get_dot1qTpFdbAddress(void *data_context, size_t *ret_len);
      long *get_dot1qTpFdbPort(void *data_context, size_t *ret_len);
      long *get_dot1qTpFdbStatus(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table dot1qTpGroupTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qTpGroupTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qTpGroupTable_get_next_data_point;
int dot1qTpGroupTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qTpGroupTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      char *get_dot1qTpGroupEgressPorts(void *data_context, size_t *ret_len);
      char *get_dot1qTpGroupLearnt(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table dot1qForwardAllTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qForwardAllTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qForwardAllTable_get_next_data_point;
int dot1qForwardAllTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qForwardAllTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      char *get_dot1qForwardAllPorts(void *data_context, size_t *ret_len);
      char *get_dot1qForwardAllStaticPorts(void *data_context, size_t *ret_len);
      int set_dot1qForwardAllStaticPorts(void *data_context, char *val, size_t val_len);
      char *get_dot1qForwardAllForbiddenPorts(void *data_context, size_t *ret_len);
      int set_dot1qForwardAllForbiddenPorts(void *data_context, char *val, size_t val_len);
/** User-defined data access functions for data in table dot1qForwardUnregisteredTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qForwardUnregisteredTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qForwardUnregisteredTable_get_next_data_point;
int dot1qForwardUnregisteredTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qForwardUnregisteredTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      char *get_dot1qForwardUnregisteredPorts(void *data_context, size_t *ret_len);
      char *get_dot1qForwardUnregisteredStaticPorts(void *data_context, size_t *ret_len);
      int set_dot1qForwardUnregisteredStaticPorts(void *data_context, char *val, size_t val_len);
      char *get_dot1qForwardUnregisteredForbiddenPorts(void *data_context, size_t *ret_len);
      int set_dot1qForwardUnregisteredForbiddenPorts(void *data_context, char *val, size_t val_len);
/** User-defined data access functions for data in table dot1qStaticUnicastTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qStaticUnicastTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qStaticUnicastTable_get_next_data_point;
int dot1qStaticUnicastTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qStaticUnicastTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      char *get_dot1qStaticUnicastAllowedToGoTo(void *data_context, size_t *ret_len);
      int set_dot1qStaticUnicastAllowedToGoTo(void *data_context, char *val, size_t val_len);
      long *get_dot1qStaticUnicastStatus(void *data_context, size_t *ret_len);
      int set_dot1qStaticUnicastStatus(void *data_context, long *val, size_t val_len);
/** User-defined data access functions for data in table dot1qStaticMulticastTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qStaticMulticastTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qStaticMulticastTable_get_next_data_point;
int dot1qStaticMulticastTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qStaticMulticastTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      char *get_dot1qStaticMulticastStaticEgressPorts(void *data_context, size_t *ret_len);
      int set_dot1qStaticMulticastStaticEgressPorts(void *data_context, char *val, size_t val_len);
      char *get_dot1qStaticMulticastForbiddenEgressPorts(void *data_context, size_t *ret_len);
      int set_dot1qStaticMulticastForbiddenEgressPorts(void *data_context, char *val, size_t val_len);
      long *get_dot1qStaticMulticastStatus(void *data_context, size_t *ret_len);
      int set_dot1qStaticMulticastStatus(void *data_context, long *val, size_t val_len);
/** User-defined data access functions for data in table dot1qVlanCurrentTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qVlanCurrentTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qVlanCurrentTable_get_next_data_point;
int dot1qVlanCurrentTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qVlanCurrentTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      u_long *get_dot1qVlanFdbId(void *data_context, size_t *ret_len);
      char *get_dot1qVlanCurrentEgressPorts(void *data_context, size_t *ret_len);
      char *get_dot1qVlanCurrentUntaggedPorts(void *data_context, size_t *ret_len);
      long *get_dot1qVlanStatus(void *data_context, size_t *ret_len);
      u_long *get_dot1qVlanCreationTime(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table dot1qVlanStaticTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qVlanStaticTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qVlanStaticTable_get_next_data_point;
int dot1qVlanStaticTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qVlanStaticTable_create_data_context(netsnmp_variable_list *index_data, int column);
void * dot1qVlanStaticTable_context_convert_function(void *loop_context, netsnmp_iterator_info *iinfo);
void * dot1qVlanStaticTable_create_data_context(netsnmp_variable_list *index_data, int column) ;
void   dot1qVlanStaticTable_data_free(void *data, netsnmp_iterator_info *iinfo);
void   dot1qVlanStaticTable_loop_free(void *loopctx, netsnmp_iterator_info *iinfo);

/** column accessors */
      char *get_dot1qVlanStaticName(void *data_context, size_t *ret_len);
      int set_dot1qVlanStaticName(void *data_context, char *val, size_t val_len);
      char *get_dot1qVlanStaticEgressPorts(void *data_context, size_t *ret_len);
      int set_dot1qVlanStaticEgressPorts(void *data_context, char *val, size_t val_len);
      char *get_dot1qVlanForbiddenEgressPorts(void *data_context, size_t *ret_len);
      int set_dot1qVlanForbiddenEgressPorts(void *data_context, char *val, size_t val_len);
      char *get_dot1qVlanStaticUntaggedPorts(void *data_context, size_t *ret_len);
      int set_dot1qVlanStaticUntaggedPorts(void *data_context, char *val, size_t val_len);
      long *get_dot1qVlanStaticRowStatus(void *data_context, size_t *ret_len);
      int set_dot1qVlanStaticRowStatus(void *data_context, long *val, size_t val_len);
/** User-defined data access functions for data in table dot1qPortVlanTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qPortVlanTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qPortVlanTable_get_next_data_point;
int dot1qPortVlanTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qPortVlanTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      u_long *get_dot1qPvid(void *data_context, size_t *ret_len);
      int set_dot1qPvid(void *data_context, u_long *val, size_t val_len);
      long *get_dot1qPortAcceptableFrameTypes(void *data_context, size_t *ret_len);
      int set_dot1qPortAcceptableFrameTypes(void *data_context, long *val, size_t val_len);
      long *get_dot1qPortIngressFiltering(void *data_context, size_t *ret_len);
      int set_dot1qPortIngressFiltering(void *data_context, long *val, size_t val_len);
      long *get_dot1qPortGvrpStatus(void *data_context, size_t *ret_len);
      int set_dot1qPortGvrpStatus(void *data_context, long *val, size_t val_len);
      u_long *get_dot1qPortGvrpFailedRegistrations(void *data_context, size_t *ret_len);
      char *get_dot1qPortGvrpLastPduOrigin(void *data_context, size_t *ret_len);
      long *get_dot1qPortRestrictedVlanRegistration(void *data_context, size_t *ret_len);
      int set_dot1qPortRestrictedVlanRegistration(void *data_context, long *val, size_t val_len) ;

/** User-defined data access functions for data in table dot1qPortVlanStatisticsTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qPortVlanStatisticsTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qPortVlanStatisticsTable_get_next_data_point;
int dot1qPortVlanStatisticsTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qPortVlanStatisticsTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      u_long *get_dot1qTpVlanPortInFrames(void *data_context, size_t *ret_len);
      u_long *get_dot1qTpVlanPortOutFrames(void *data_context, size_t *ret_len);
      u_long *get_dot1qTpVlanPortInDiscards(void *data_context, size_t *ret_len);
      u_long *get_dot1qTpVlanPortInOverflowFrames(void *data_context, size_t *ret_len);
      u_long *get_dot1qTpVlanPortOutOverflowFrames(void *data_context, size_t *ret_len);
      u_long *get_dot1qTpVlanPortInOverflowDiscards(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table dot1qPortVlanHCStatisticsTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qPortVlanHCStatisticsTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qPortVlanHCStatisticsTable_get_next_data_point;
int dot1qPortVlanHCStatisticsTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qPortVlanHCStatisticsTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      U64 *get_dot1qTpVlanPortHCInFrames(void *data_context, size_t *ret_len);
      U64 *get_dot1qTpVlanPortHCOutFrames(void *data_context, size_t *ret_len);
      U64 *get_dot1qTpVlanPortHCInDiscards(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table dot1qLearningConstraintsTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1qLearningConstraintsTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1qLearningConstraintsTable_get_next_data_point;
int dot1qLearningConstraintsTable_commit_row(void **my_data_context, int new_or_del);
void * dot1qLearningConstraintsTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_dot1qConstraintType(void *data_context, size_t *ret_len);
      int set_dot1qConstraintType(void *data_context, long *val, size_t val_len);
      long *get_dot1qConstraintStatus(void *data_context, size_t *ret_len);
      int set_dot1qConstraintStatus(void *data_context, long *val, size_t val_len);

#endif /* QBRIDGEMIB_ACCESS_H */

