/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf 12909 2005-09-29 22:16:22Z hardaker $
 */
#ifndef QBRIDGEMIB_ENUMS_H
#define QBRIDGEMIB_ENUMS_H

/* enums for column dot1qTpFdbStatus */
           #define DOT1QTPFDBSTATUS_OTHER       1
           #define DOT1QTPFDBSTATUS_INVALID     2
           #define DOT1QTPFDBSTATUS_LEARNED     3
           #define DOT1QTPFDBSTATUS_SELF        4
           #define DOT1QTPFDBSTATUS_MGMT        5

/* enums for column dot1qStaticUnicastStatus */
           #define DOT1QSTATICUNICASTSTATUS_OTHER       1
           #define DOT1QSTATICUNICASTSTATUS_INVALID     2
           #define DOT1QSTATICUNICASTSTATUS_PERMANENT       3
           #define DOT1QSTATICUNICASTSTATUS_DELETEONRESET       4
           #define DOT1QSTATICUNICASTSTATUS_DELETEONTIMEOUT     5

/* enums for column dot1qStaticMulticastStatus */
           #define DOT1QSTATICMULTICASTSTATUS_OTHER     1
           #define DOT1QSTATICMULTICASTSTATUS_INVALID       2
           #define DOT1QSTATICMULTICASTSTATUS_PERMANENT     3
           #define DOT1QSTATICMULTICASTSTATUS_DELETEONRESET     4
           #define DOT1QSTATICMULTICASTSTATUS_DELETEONTIMEOUT       5

/* enums for column dot1qVlanStatus */
           #define DOT1QVLANSTATUS_OTHER        1
           #define DOT1QVLANSTATUS_PERMANENT        2
           #define DOT1QVLANSTATUS_DYNAMICGVRP      3

/* enums for column dot1qVlanStaticRowStatus */
           #define DOT1QVLANSTATICROWSTATUS_ACTIVE      1
           #define DOT1QVLANSTATICROWSTATUS_NOTINSERVICE        2
           #define DOT1QVLANSTATICROWSTATUS_NOTREADY        3
           #define DOT1QVLANSTATICROWSTATUS_CREATEANDGO     4
           #define DOT1QVLANSTATICROWSTATUS_CREATEANDWAIT       5
           #define DOT1QVLANSTATICROWSTATUS_DESTROY     6

/* enums for column dot1qPortAcceptableFrameTypes */
           #define DOT1QPORTACCEPTABLEFRAMETYPES_ADMITALL       1
           #define DOT1QPORTACCEPTABLEFRAMETYPES_ADMITONLYVLANTAGGED        2
           #define DOT1QPORTACCEPTABLEFRAMETYPES_ADMITONLYVLANUNTAGGED         3

/* enums for column dot1qPortIngressFiltering */
           #define DOT1QPORTINGRESSFILTERING_TRUE       1
           #define DOT1QPORTINGRESSFILTERING_FALSE      2

/* enums for column dot1qPortGvrpStatus */
           #define DOT1QPORTGVRPSTATUS_ENABLED      1
           #define DOT1QPORTGVRPSTATUS_DISABLED     2

/* enums for column dot1qConstraintType */
           #define DOT1QCONSTRAINTTYPE_INDEPENDENT      1
           #define DOT1QCONSTRAINTTYPE_SHARED       2

/* enums for column dot1qConstraintStatus */
           #define DOT1QCONSTRAINTSTATUS_ACTIVE     1
           #define DOT1QCONSTRAINTSTATUS_NOTINSERVICE       2
           #define DOT1QCONSTRAINTSTATUS_NOTREADY       3
           #define DOT1QCONSTRAINTSTATUS_CREATEANDGO        4
           #define DOT1QCONSTRAINTSTATUS_CREATEANDWAIT      5
           #define DOT1QCONSTRAINTSTATUS_DESTROY        6


/* enums for scalar dot1qVlanVersionNumber */
#define DOT1QVLANVERSIONNUMBER_VERSION1     1

/* enums for scalar dot1qGvrpStatus */
#define DOT1QGVRPSTATUS_ENABLED     1
#define DOT1QGVRPSTATUS_DISABLED        2

/* enums for scalar dot1qConstraintTypeDefault */
#define DOT1QCONSTRAINTTYPEDEFAULT_INDEPENDENT      1
#define DOT1QCONSTRAINTTYPEDEFAULT_SHARED       2

#endif /* QBRIDGEMIB_ENUMS_H */
