#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#SURVEILLANCEVLANDIR should defined in caller Makefile which is relative path of caller.
SURVEILLANCEVLAN_OBJ := $(SURVEILLANCEVLANDIR)/proto_surveillancevlan.o
