#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#UDLDDIR should defined in caller Makefile which is relative path of caller.
UDLD_OBJ := $(UDLDDIR)/proto_udld.o
