#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************

#IPSGDIR should defined in caller Makefile which is relative path of caller.
IPSG_OBJ := $(IPSGDIR)/proto_isg.o
