#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#DHCPDIR should defined in caller Makefile which is relative path of caller.
DHCP_OBJ := $(DHCPDIR)/proto_dhcp.o

