#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
PSWITCH_USER_MODE = y
include $(PSWITCH_DIR)/make.path.mk
include $(PSWITCH_DIR)/make.config.mk
include $(PSWITCH_DIR)/make.root.linux.mk

CFLAGS_EXTRA += -Werror -Wall -Wuninitialized -Wstrict-prototypes -Wno-strict-aliasing -Wno-format-zero-length  -Werror=old-style-declaration -Werror=ignored-qualifiers -O3 -Os -g
#-Wformat-security
INCLUDE += -I$(SYS_LIBINCLUDE) -I$(SYS_PLATINCLUDE) -I$(SYS_LXINCLUDE) -I$(SYS_PROTOINCLUDE)
INCLUDE += $(LIB_INCLUDE)

TARGET  = obj
OBJS    = $(OBJS_y) $(OBJS_m) 

all: $(OBJS)
	@rm -f $(LIBNAME)*
	$(CC) $(LIB) -shared -Wl,-soname,$(LIBNAME).0 -o $(LIBNAME).0.0 $(OBJS)
	ln -sf $(LIBNAME).0.0 $(LIBNAME).0
	ln -sf $(LIBNAME).0 $(LIBNAME)
	$(SYSINSTALL) $(LIBNAME)*

$(TARGET)/%.o: %.c $(PREREQUISITE) 
	$(CC) $(INCLUDE) $(CFLAGS) $(CFLAGS_EXTRA) -fPIC -c -o $@ $<

romfs:
	$(SYSROMFSINST) $(LIBNAME).0.0 /lib
	ln -sf $(LIBNAME).0.0 $(ROMFSDIR)/lib/$(LIBNAME).0
	ln -sf $(LIBNAME).0 $(ROMFSDIR)/lib/$(LIBNAME)

clean:
	rm -f $(LIBNAME)* $(TARGET)/*

.PHONY: clean romfs
