#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
PSWITCH_DIR := $(CURDIR)/../..

# target
LIBNAME = libcfgtbl.so
OBJS_y  = $(TARGET)/cfgtbl.o $(TARGET)/cfg_board.o

#Put after OBJS
include ../Makefile.lib
