
#ifndef __SKI_MIB_H__
#define __SKI_MIB_H__

#include <ski/ski_core.h>
#include <rsd/rsd_mib.h>

typedef enum ski_mib_cmd_e
{
    
    SKI_MIB_SET_BASE = (SKI_CORE_MOD_MIB * SKI_CORE_MODCMD_TOTAL),
    SKI_MIB_CLR_CNTR,
    SKI_MIB_CLR_CNTR_GLB,
    SKI_MIB_CLR_CNTR_DBG,

    SKI_MIB_GET_BASE = (SKI_MIB_SET_BASE + SKI_CORE_MODCMD_RANGE),
    
    SKI_MIB_GET_ETHER_STATS_DROP_EVENTS,
    SKI_MIB_GET_ETHER_STATS_OCTETS,
    SKI_MIB_GET_ETHER_STATS_PKTS,
    SKI_MIB_GET_ETHER_STATS_BCAST_PKTS,
    SKI_MIB_GET_ETHER_STATS_MCAST_PKTS,
    SKI_MIB_GET_ETHER_STATS_CRC_ALIGN_ERRS,
    SKI_MIB_GET_ETHER_STATS_UNDER_SIZE_PKTS,
    SKI_MIB_GET_ETHER_STATS_OVER_SIZE_PKTS,
    SKI_MIB_GET_ETHER_STATS_FRAGMENTS,
    SKI_MIB_GET_ETHER_STATS_JABBERS,
    SKI_MIB_GET_ETHER_STATS_COLLISIONS,
    SKI_MIB_GET_ETHER_STATS_PKTS_64OCTETS,
    SKI_MIB_GET_ETHER_STATS_PKTS_65TO127OCTETS,
    SKI_MIB_GET_ETHER_STATS_PKTS_128TO255OCTETS,
    SKI_MIB_GET_ETHER_STATS_PKTS_256TO511OCTETS,
    SKI_MIB_GET_ETHER_STATS_PKTS_512TO1023OCTETS,
    SKI_MIB_GET_ETHER_STATS_PKTS_1024TO1518OCTETS,
    SKI_MIB_GET_IF_OUT_UCAST_PKTS,
    SKI_MIB_GET_IF_OUT_NUCAST_PKTS,
    SKI_MIB_GET_IF_OUT_OCTETS,
    
    SKI_MIB_GET_DOT1D_TP_PORT_IN_DISCARDS,
    
    SKI_MIB_GET_DOT1D_TP_LEARNED_ENTRY_DISCARDS,
    
    SKI_MIB_GET_DOT3_STATS_FCS_ERRS,
    SKI_MIB_GET_DOT3_STATS_SINGLE_COLLISION_FRAMES,
    SKI_MIB_GET_DOT3_STATS_MULTIPLE_COLLISION_FRAMES,
    SKI_MIB_GET_DOT3_STATS_DEFERRED_TRANSMISSIONS,
    SKI_MIB_GET_DOT3_STATS_LATE_COLLISIONS,
    SKI_MIB_GET_DOT3_STATS_EXCESSIVE_COLLISIONS,
    SKI_MIB_GET_DOT3_STATS_SYMBOL_ERRORS,
    SKI_MIB_GET_DOT3_STATUS_ALIGNMENT_ERRORS_PKTS,
    SKI_MIB_GET_DOT3_STATUS_FRAMETOOLONGS_ERRORS_PKTS,
    
    SKI_MIB_GET_IF_IN_OCTETS,
    SKI_MIB_GET_IF_IN_UCAST_PKTS,
    SKI_MIB_GET_IF_IN_NUCAST_PKTS,
    SKI_MIB_GET_IF_IN_BCAST_PKTS,
    SKI_MIB_GET_IF_IN_MCAST_PKTS,
    SKI_MIB_GET_IF_IN_DISCARDS_PKTS,
    SKI_MIB_GET_IF_OUT_MCAST_PKTS,
    SKI_MIB_GET_IF_OUT_BCAST_PKTS,
    SKI_MIB_GET_IF_HC_IN_OCTETS,
    SKI_MIB_GET_IF_HC_IN_UCAST_PKTS,
    SKI_MIB_GET_IF_HC_IN_MCAST_PKTS,
    SKI_MIB_GET_IF_HC_IN_BCAST_PKTS,
    SKI_MIB_GET_IF_HC_OUT_OCTETS,
    SKI_MIB_GET_IF_HC_OUT_UCAST_PKTS,
    SKI_MIB_GET_IF_HC_OUT_MCAST_PKTS,
    SKI_MIB_GET_IF_HC_OUT_BCAST_PKTS,

    SKI_MIB_GET_DOT3_CTRL_IN_UNKNOWN_OPCODES,
    SKI_MIB_GET_DOT3_OUT_PAUSE_FRAMES,
    SKI_MIB_GET_DOT3_IN_PAUSE_FRAMES,
    SKI_MIB_GET_SMART_TRIGGER_HIT0,
    SKI_MIB_GET_SMART_TRIGGER_HIT1,

    SKI_MIB_GET_IFOUTDISCARDS_PKTS,

    SKI_MIB_GET_CPU_STATS_PKTS,

    SKI_MIB_GET_DEBUG_GLOBAL_PKTS,
    SKI_MIB_GET_DEBUG_PORT_PKTS,

    SKI_MIB_CMD_END
} ski_mib_cmd_t;

typedef struct ski_mib_cntr_s
{
    sys_logic_port_t    port;
    uint32              type;
    uint64              cntr;
} ski_mib_cntr_t;

typedef struct ski_mib_allCntr_s
{
    sys_mib_allPorts_t  cntr;
} ski_mib_allCntr_t;

typedef union ski_mib_ioctl_u
{
    ski_mib_cntr_t     mibCntr;
    ski_mib_allCntr_t  mibCntrAll;
} ski_mib_ioctl_t;

extern int32 ski_mib_init(void);

#endif  

