
#ifndef __SYS_SWDEF_DOS_H__
#define __SYS_SWDEF_DOS_H__
#define BOND_DOS_IPV6MINFRAGLENGTH_MIN       0
#define BOND_DOS_IPV6MINFRAGLENGTH_MAX       65535
#define BOND_DOS_PINGMAXLENGTH_MIN           0
#define BOND_DOS_PINGMAXLENGTH_MAX           65535
#define BOND_DOS_SMURFLENGTH_MIN             0
#define BOND_DOS_SMURFLENGTH_MAX             32
#define BOND_DOS_TCPHDRMINCHKLENGTH_MIN      0
#define BOND_DOS_TCPHDRMINCHKLENGTH_MAX      31
#define DFLT_DOS_TYPE_EBL                    DEFDB_VAL(DEF_DOS_TYPE_EBL)
#define DFLT_DOS_MAXPINGLEN                  512
#define DFLT_DOS_MINIPV6FRAGLEN              1240
#define DFLT_DOS_SMURFNETMASKLEN             0
#define DFLT_DOS_MINTCPHDRLEN                20
#define DFLT_DOS_PORT_ATTACKPREVENT_EBL      DEFDB_VAL(DEF_DOS_PORT_ATTACKPREVENT_EBL)

#endif 

