
#ifndef __SYS_SWDEF_MCAST_H__
#define __SYS_SWDEF_MCAST_H__
#define CAPA_MCAST_DB_NUM                 1024
#define CAPA_MCAST_GROUP_NUM              DEFDB_VAL(DEF_MCAST_GROUP_NUM)      
#define CAPA_MCAST_PORT_LIMIT_NUM         256                                 
#define CAPA_MCAST_PROFILE_NUM            128

#define CAPA_IGMP_GROUP_NUM               256
#define CAPA_IGMP_MVR_GROUP_NUM           DEFDB_VAL(DEF_IGMP_MVR_GROUP_NUM)   

#ifdef CONFIG_SYS_PROTO_MLD_SNOOPING

#define CAPA_MLD_GROUP_NUM                256
#endif

#define CAPA_L2_MCAST_GROUP_NUM           500
#define BOND_MCAST_PROFILE_MIN            1
#define BOND_MCAST_PROFILE_MAX            CAPA_MCAST_PROFILE_NUM      

#define BOND_MCAST_ROBUST_MIN             1
#define BOND_MCAST_ROBUST_MAX             7
#define BOND_MCAST_QRYINTV_MIN            30
#define BOND_MCAST_QRYINTV_MAX            18000
#define BOND_MCAST_RESPONSE_MIN           5
#define BOND_MCAST_RESPONSE_MAX           20
#define BOND_MCAST_LASTMBRCNT_MIN         1
#define BOND_MCAST_LASTMBRCNT_MAX         7
#define BOND_MCAST_LASTMBRINTV_MIN        1
#define BOND_MCAST_LASTMBRINTV_MAX        25

#ifdef CONFIG_SYS_PROTO_MVR
#define BOND_IGMP_MVR_QRYINTV_MIN         1
#define BOND_IGMP_MVR_QRYINTV_MAX         10
#endif
#define DFLT_IGMP_EBL                     DEFDB_VAL(DEF_IGMP_EBL)
#define DFLT_IGMP_SUPPRE_EBL              DEFDB_VAL(DEF_IGMP_SUPPRE_EBL)
#define DFLT_IGMP_VLAN_EBL                DEFDB_VAL(DEF_IGMP_VLAN_EBL)
#define DFLT_IGMP_IMMEDIATE_LEAVE         DEFDB_VAL(DEF_IGMP_IMMEDIATE_LEAVE)
#define DFLT_IGMP_ROUTER_PIMDVMRP_LEARN   ENABLED
#define DFLT_IGMP_ROUTER_TIMEOUT          (DFLT_IGMP_ROBUSTNESS_VAR * DFLT_IGMP_QUERY_INTV + DFLT_IGMP_QUERY_RESPONSE_INTV)
#define DFLT_IGMP_ROBUSTNESS_VAR          2
#define DFLT_IGMP_GROUP_MEMBERSHIP_INTV   (DFLT_IGMP_ROBUSTNESS_VAR * DFLT_IGMP_QUERY_INTV + DFLT_IGMP_QUERY_RESPONSE_INTV)
#define DFLT_IGMP_QUERY_RESPONSE_INTV     10
#define DFLT_IGMP_QUERY_INTV              125
#define DFLT_IGMP_GSQUERY_RESPONSE_INTV   1
#define DFLT_IGMP_UNKNOWN_MCAST_ACTION    DEFDB_VAL(DEF_IGMP_UNKNOWN_MCAST_ACTION)
#define DFLT_IGMP_LOOKUP_MODE             IGMP_DMAC_VID_MODE
#define DFLT_IGMP_OPERATION_VER           DEFDB_VAL(DEF_IGMP_OPERATION_VER)
#define DFLT_IGMP_MAX_GROUP_ACT           DEFDB_VAL(DEF_IGMP_MAX_GROUP_ACT)
#define DFLT_IGMP_PORT_PROFILE            INVALID_PROFILE_ID

#ifdef CONFIG_SYS_PROTO_MLD_SNOOPING
#define DFLT_MLD_EBL                      DEFDB_VAL(DEF_MLD_EBL)
#define DFLT_MLD_SUPPRE_EBL               DEFDB_VAL(DEF_MLD_SUPPRE_EBL)
#define DFLT_MLD_VLAN_EBL                 DEFDB_VAL(DEF_MLD_VLAN_EBL)
#define DFLT_MLD_IMMEDIATE_LEAVE          DEFDB_VAL(DEF_MLD_IMMEDIATE_LEAVE)
#define DFLT_MLD_ROUTER_PIMDVMRP_LEARN    ENABLED
#define DFLT_MLD_ROUTER_TIMEOUT           (DFLT_MLD_ROBUSTNESS_VAR * DFLT_MLD_QUERY_INTV + DFLT_MLD_QUERY_RESPONSE_INTV)
#define DFLT_MLD_ROBUSTNESS_VAR           2
#define DFLT_MLD_GROUP_MEMBERSHIP_INTV    (DFLT_MLD_ROBUSTNESS_VAR * DFLT_MLD_QUERY_INTV + DFLT_MLD_QUERY_RESPONSE_INTV)
#define DFLT_MLD_QUERY_RESPONSE_INTV      10
#define DFLT_MLD_QUERY_INTV               125
#define DFLT_MLD_GS_QUERY_RESP_INTV       1
#define DFLT_MLD_UNKNOWN_MCAST_ACTION     DEFDB_VAL(DEF_MLD_UNKNOWN_MCAST_ACTION)
#define DFLT_MLD_LOOKUP_MODE              IGMP_DMAC_VID_MODE
#define DFLT_MLD_OPERATION_VER            DEFDB_VAL(DEF_MLD_OPERATION_VER)
#define DFLT_MLD_MAX_GROUP_ACT            DEFDB_VAL(DEF_MLD_MAX_GROUP_ACT)
#define DFLT_MLD_PORT_PROFILE             INVALID_PROFILE_ID
#endif

#ifdef CONFIG_SYS_PROTO_MVR
#define DFLT_IGMP_MVR_ENABLED             DISABLED
#define DFLT_IGMP_MVR_MODE                MVR_MODE_COMPATABLE
#define DFLT_IGMP_MVR_QUERYTIME           1
#define DFLT_IGMP_MVR_VLAN                1
#define DFLT_IGMP_MVR_PORT_TYPE           MVR_TYPE_NONE
#define DFLT_IGMP_MVR_IMMEDIATE_LEAVE     DEFDB_VAL(DEF_IGMP_MVR_IMMEDIATE_LEAVE)
#endif

#define DFLT_MCAST_PORT_LIMIT             DEFDB_VAL(DEF_MCAST_PORT_LIMIT)
#endif 

