
#ifndef __SYS_SWDEF_PORT_H__
#define __SYS_SWDEF_PORT_H__
#define BOND_PORT_ERRDISABLE_RECOVERY_INTERVAL_MIN              30
#define BOND_PORT_ERRDISABLE_RECOVERY_INTERVAL_MAX              86400
#ifdef CONFIG_SYS_JUMBO_FRAME
#define BOND_PORT_JUMBO_FRAME_MIN                               1518
#define BOND_PORT_JUMBO_FRAME_MAX                               10000
#endif
#define DFLT_PORT_EBL                           ENABLED
#define DFLT_PORT_COMBO_AUTO                    PORT_COMBO_MEDIA_AUTO
#define DFLT_PORT_FLOW_CTRL_AUTO                DEFDB_VAL(DEF_PORT_FLOW_CTRL_AUTO_ABILITY)
#define DFLT_PORT_FLOW_CTRL                     DEFDB_VAL(DEF_PORT_FLOW_CTRL_STATUS)
#define DFLT_PORT_BACK_PRESSURE                 DEFDB_VAL(DEF_PORT_BACK_PRESSURE)
#define DFLT_PORT_DESCRIPTION                   DEFDB_STR(DEF_PORT_DESCRIPTION)
#define DFLT_PORT_FIBER_NEGO_EBL                DEFDB_VAL(DEF_PORT_FIBER_NEGO_EBL)

#ifdef CONFIG_SYS_EEE
#define DFLT_PORT_EEE_EBL                       DEFDB_VAL(DEF_PORT_EEE_EBL)
#endif

#ifdef CONFIG_SYS_PORT_ERR_DISABLED
#define DFLT_PORT_ERRDISABLE_RECOVERY           DEFDB_VAL(DEF_PORT_ERRDISABLE_RECOVERY)
#define DFLT_PORT_ERRDISABLE_RECOVERY_INTERVAL  DEFDB_VAL(DEF_PORT_ERRDISABLE_RECOVERY_INTERVAL)
#endif

#ifdef CONFIG_SYS_PORT_ISOLATION
#define DFLT_PORT_PROTECTED                     DEFDB_VAL(DEF_PORT_PROTECTED)
#endif

#ifdef CONFIG_SYS_JUMBO_FRAME
#define DFLT_PORT_MAX_FRAME_SIZE                DEFDB_VAL(DEF_PORT_MAX_FRAME_SIZE)
#endif
#define DFLT_PORT_PREFIX_BRIEF_FA               DEFDB_STR(DEF_PORT_PREFIX_BRIEF_FA)
#define DFLT_PORT_PREFIX_BRIEF_GE               DEFDB_STR(DEF_PORT_PREFIX_BRIEF_GE)
#define DFLT_PORT_PREFIX_BRIEF_MGE              DEFDB_STR(DEF_PORT_PREFIX_BRIEF_MGE)
#define DFLT_PORT_PREFIX_BRIEF_TE               DEFDB_STR(DEF_PORT_PREFIX_BRIEF_TE)
#define DFLT_PORT_PREFIX_BRIEF_LAG              DEFDB_STR(DEF_PORT_PREFIX_BRIEF_LAG)
#define DFLT_PORT_PREFIX_BRIEF_VLAN             "vlan"
#define DFLT_PORT_PREFIX_WEB_FA                 DEFDB_STR(DEF_PORT_PREFIX_WEB_FA)
#define DFLT_PORT_PREFIX_WEB_GE                 DEFDB_STR(DEF_PORT_PREFIX_WEB_GE)
#define DFLT_PORT_PREFIX_WEB_MGE                DEFDB_STR(DEF_PORT_PREFIX_WEB_MGE)
#define DFLT_PORT_PREFIX_WEB_TE                 DEFDB_STR(DEF_PORT_PREFIX_WEB_TE)
#define DFLT_PORT_PREFIX_WEB_LAG                DEFDB_STR(DEF_PORT_PREFIX_WEB_LAG)
#define DFLT_PORT_PREFIX_WEB_VLAN               "VLAN"
#define DFLT_PORT_PREFIX_FA                     DEFDB_STR(DEF_PORT_PREFIX_FA)
#define DFLT_PORT_PREFIX_GE                     DEFDB_STR(DEF_PORT_PREFIX_GE)
#define DFLT_PORT_PREFIX_MGE                    DEFDB_STR(DEF_PORT_PREFIX_MGE)
#define DFLT_PORT_PREFIX_TE                     DEFDB_STR(DEF_PORT_PREFIX_TE)
#define DFLT_PORT_PREFIX_LAG                    DEFDB_STR(DEF_PORT_PREFIX_LAG)
#define DFLT_PORT_PREFIX_VLAN                   "vlan"

#endif 

