
#ifndef __SYS_SWDEF_QOS_H__
#define __SYS_SWDEF_QOS_H__
#define CAPA_QOS_PRI_NUM                        RTK_MAX_NUM_OF_PRIORITY
#define CAPA_QOS_QUEUE_NUM                      8
#define CAPA_QOS_DSCP_NUM                       64
#define CAPA_QOS_COS_NUM                        8
#define CAPA_QOS_IPP_NUM                        8
#define BOND_QOS_QUEUE_WEIGHT_MIN               1
#define BOND_QOS_QUEUE_WEIGHT_MAX               127
#define BOND_QOS_PRI_MIN                        0
#define BOND_QOS_PRI_MAX                        7
#define DFLT_QOS_MODE                           DEFDB_VAL(DEF_QOS_MODE)
#define DFLT_QOS_STRICT_PRI_QUEUE_NUM           DEFDB_VAL(DEF_QOS_STRICT_PRI_QUEUE_NUM)
#define DFLT_QOS_TRUST_TYPE                     DEFDB_VAL(DEF_QOS_TRUST_TYPE)
#define DFLT_QOS_PORT_TRUST_STATE               DEFDB_VAL(DEF_QOS_PORT_TRUST_STATE)
#define DFLT_QOS_PORT_COS                       DEFDB_VAL(DEF_QOS_PORT_COS)
#define DFLT_QOS_PORT_REMARK_COS                DEFDB_VAL(DEF_QOS_PORT_REMARK_COS)
#define DFLT_QOS_PORT_REMARK_DSCP               DEFDB_VAL(DEF_QOS_PORT_REMARK_DSCP)
#define DFLT_QOS_PORT_REMARK_IPP                DEFDB_VAL(DEF_QOS_PORT_REMARK_IPP)

#define DFLT_QOS_QUEUE0_WEIGHT                  1
#define DFLT_QOS_QUEUE1_WEIGHT                  2
#define DFLT_QOS_QUEUE2_WEIGHT                  3
#define DFLT_QOS_QUEUE3_WEIGHT                  4
#define DFLT_QOS_QUEUE4_WEIGHT                  5
#define DFLT_QOS_QUEUE5_WEIGHT                  9
#define DFLT_QOS_QUEUE6_WEIGHT                  13
#define DFLT_QOS_QUEUE7_WEIGHT                  15
#define DFLT_QOS_COS0_QUEUE                     1
#define DFLT_QOS_COS1_QUEUE                     0
#define DFLT_QOS_COS2_QUEUE                     2
#define DFLT_QOS_COS3_QUEUE                     3
#define DFLT_QOS_COS4_QUEUE                     4
#define DFLT_QOS_COS5_QUEUE                     5
#define DFLT_QOS_COS6_QUEUE                     6
#define DFLT_QOS_COS7_QUEUE                     7
#define DFLT_QOS_IPP0_QUEUE                     0
#define DFLT_QOS_IPP1_QUEUE                     1
#define DFLT_QOS_IPP2_QUEUE                     2
#define DFLT_QOS_IPP3_QUEUE                     3
#define DFLT_QOS_IPP4_QUEUE                     4
#define DFLT_QOS_IPP5_QUEUE                     5
#define DFLT_QOS_IPP6_QUEUE                     6
#define DFLT_QOS_IPP7_QUEUE                     7
#define DFLT_QOS_DSCP0_QUEUE                    0
#define DFLT_QOS_DSCP1_QUEUE                    0
#define DFLT_QOS_DSCP2_QUEUE                    0
#define DFLT_QOS_DSCP3_QUEUE                    0
#define DFLT_QOS_DSCP4_QUEUE                    0
#define DFLT_QOS_DSCP5_QUEUE                    0
#define DFLT_QOS_DSCP6_QUEUE                    0
#define DFLT_QOS_DSCP7_QUEUE                    0
#define DFLT_QOS_DSCP8_QUEUE                    1
#define DFLT_QOS_DSCP9_QUEUE                    1
#define DFLT_QOS_DSCP10_QUEUE                   1
#define DFLT_QOS_DSCP11_QUEUE                   1
#define DFLT_QOS_DSCP12_QUEUE                   1
#define DFLT_QOS_DSCP13_QUEUE                   1
#define DFLT_QOS_DSCP14_QUEUE                   1
#define DFLT_QOS_DSCP15_QUEUE                   1
#define DFLT_QOS_DSCP16_QUEUE                   2
#define DFLT_QOS_DSCP17_QUEUE                   2
#define DFLT_QOS_DSCP18_QUEUE                   2
#define DFLT_QOS_DSCP19_QUEUE                   2
#define DFLT_QOS_DSCP20_QUEUE                   2
#define DFLT_QOS_DSCP21_QUEUE                   2
#define DFLT_QOS_DSCP22_QUEUE                   2
#define DFLT_QOS_DSCP23_QUEUE                   2
#define DFLT_QOS_DSCP24_QUEUE                   3
#define DFLT_QOS_DSCP25_QUEUE                   3
#define DFLT_QOS_DSCP26_QUEUE                   3
#define DFLT_QOS_DSCP27_QUEUE                   3
#define DFLT_QOS_DSCP28_QUEUE                   3
#define DFLT_QOS_DSCP29_QUEUE                   3
#define DFLT_QOS_DSCP30_QUEUE                   3
#define DFLT_QOS_DSCP31_QUEUE                   3
#define DFLT_QOS_DSCP32_QUEUE                   4
#define DFLT_QOS_DSCP33_QUEUE                   4
#define DFLT_QOS_DSCP34_QUEUE                   4
#define DFLT_QOS_DSCP35_QUEUE                   4
#define DFLT_QOS_DSCP36_QUEUE                   4
#define DFLT_QOS_DSCP37_QUEUE                   4
#define DFLT_QOS_DSCP38_QUEUE                   4
#define DFLT_QOS_DSCP39_QUEUE                   4
#define DFLT_QOS_DSCP40_QUEUE                   5
#define DFLT_QOS_DSCP41_QUEUE                   5
#define DFLT_QOS_DSCP42_QUEUE                   5
#define DFLT_QOS_DSCP43_QUEUE                   5
#define DFLT_QOS_DSCP44_QUEUE                   5
#define DFLT_QOS_DSCP45_QUEUE                   5
#define DFLT_QOS_DSCP46_QUEUE                   5
#define DFLT_QOS_DSCP47_QUEUE                   5
#define DFLT_QOS_DSCP48_QUEUE                   6
#define DFLT_QOS_DSCP49_QUEUE                   6
#define DFLT_QOS_DSCP50_QUEUE                   6
#define DFLT_QOS_DSCP51_QUEUE                   6
#define DFLT_QOS_DSCP52_QUEUE                   6
#define DFLT_QOS_DSCP53_QUEUE                   6
#define DFLT_QOS_DSCP54_QUEUE                   6
#define DFLT_QOS_DSCP55_QUEUE                   6
#define DFLT_QOS_DSCP56_QUEUE                   7
#define DFLT_QOS_DSCP57_QUEUE                   7
#define DFLT_QOS_DSCP58_QUEUE                   7
#define DFLT_QOS_DSCP59_QUEUE                   7
#define DFLT_QOS_DSCP60_QUEUE                   7
#define DFLT_QOS_DSCP61_QUEUE                   7
#define DFLT_QOS_DSCP62_QUEUE                   7
#define DFLT_QOS_DSCP63_QUEUE                   7

#define DFLT_QOS_QUEUE0_COS                     1
#define DFLT_QOS_QUEUE1_COS                     0
#define DFLT_QOS_QUEUE2_COS                     2
#define DFLT_QOS_QUEUE3_COS                     3
#define DFLT_QOS_QUEUE4_COS                     4
#define DFLT_QOS_QUEUE5_COS                     5
#define DFLT_QOS_QUEUE6_COS                     6
#define DFLT_QOS_QUEUE7_COS                     7
#define DFLT_QOS_QUEUE0_DSCP                    0
#define DFLT_QOS_QUEUE1_DSCP                    8
#define DFLT_QOS_QUEUE2_DSCP                    16
#define DFLT_QOS_QUEUE3_DSCP                    24
#define DFLT_QOS_QUEUE4_DSCP                    32
#define DFLT_QOS_QUEUE5_DSCP                    40
#define DFLT_QOS_QUEUE6_DSCP                    48
#define DFLT_QOS_QUEUE7_DSCP                    56
#define DFLT_QOS_QUEUE0_IPP                     0
#define DFLT_QOS_QUEUE1_IPP                     1
#define DFLT_QOS_QUEUE2_IPP                     2
#define DFLT_QOS_QUEUE3_IPP                     3
#define DFLT_QOS_QUEUE4_IPP                     4
#define DFLT_QOS_QUEUE5_IPP                     5
#define DFLT_QOS_QUEUE6_IPP                     6
#define DFLT_QOS_QUEUE7_IPP                     7
#endif 

