
#ifndef __SYS_SWDEF_VLAN_H__
#define __SYS_SWDEF_VLAN_H__
#define CAPA_VLAN_NUM                       4094
#define CAPA_VLAN_ADMIN_NUM                 DEFDB_VAL(DEF_VLAN_ADMIN_ENTRY_NUM)

#ifdef CONFIG_SYS_VOICEVLAN

#define CAPA_VLAN_VOICE_OUI_NUM             16
#endif

#ifdef CONFIG_SYS_PROTOCOL_VLAN

#define CAPA_VLAN_PROTO_GROUP_NUM           8
#endif

#ifdef CONFIG_SYS_IP_SUBNET

#define CAPA_VLAN_IP_SUBNET_GROUP_NUM       128  
#endif

#ifdef CONFIG_SYS_MACVLAN

#define CAPA_VLAN_MAC_GROUP_NUM             DEFDB_VAL(DEF_VLAN_MAC_GROUP_NUM)
#define CAPA_VLAN_MAC_GROUP_NUM_MAX         256
#endif

#ifdef CONFIG_SYS_SURVEILLANCEVLAN

#define CAPA_VLAN_SURVEILLANCE_OUI_NUM      16
#endif
#define BOND_VLAN_MIN                       1
#define BOND_VLAN_MAX                       4094

#ifdef CONFIG_SYS_VOICEVLAN

#define BOND_VLAN_VOICE_AGING_MIN           30
#define BOND_VLAN_VOICE_AGING_MAX           65536
#endif

#ifdef CONFIG_SYS_SURVEILLANCEVLAN

#define BOND_VLAN_SURVEILLANCE_AGING_MIN    30
#define BOND_VLAN_SURVEILLANCE_AGING_MAX    65536
#endif

#ifdef CONFIG_SYS_MACVLAN

#define BOND_VLAN_MAC_GROUP_MIN             1
#define BOND_VLAN_MAC_GROUP_MAX             2147483647
#endif
#define DFLT_VLAN_PREFIX_NAME               DEFDB_STR(DEF_VLAN_NAME_PREFIX)
#define DFLT_VLAN_RESERVED_VLAN             4095
#define DFLT_VLAN_PORT_MODE                 DEFDB_VAL(DEF_VLAN_PORT_MODE)
#define DFLT_VLAN_TRUNK_ALLOW_VLAN          ""
#define DFLT_VLAN_TRUNK_UPLINK              DEFDB_VAL(DEF_VLAN_PORT_ROLE_UPLINK_EN)
#define DFLT_VLAN_PORT_MODE_CHK             DEFDB_VAL(DEF_VLAN_PORT_MODE_CHK)
#define DFLT_VLAN_IGR_FILTER                DEFDB_VAL(DEF_VLAN_IFILTER_EN)
#define DFLT_VLAN_ACCEPT_FRAME_TYPE         DEFDB_VAL(DEF_VLAN_ACCEPT_FRAME_TYPE)
#define DFLT_VLAN_PVID                      DEFDB_VAL(DEF_VLAN_PVID)
#ifdef CONFIG_SYS_MANAGEMENT_VLAN

#define DFLT_VLAN_MGMT_VLAN                 DEFDB_VAL(DEF_VLAN_MGMVLAN_VID)
#endif

#define DFLT_VLAN_DFLT_VLAN                 1

#define DFLT_VLAN_DFLT_NAME                 DEFDB_STR(DEF_DEFAULT_VLAN_NAME)

#define DFLT_DEFAULT_VLAN_MEMBERSHIP        SYS_VLAN_UNTAGGED

#ifdef CONFIG_SYS_VLAN_QINQ

#define DFLT_VLAN_DOT1QTUNNEL_TPID_0        DEFDB_VAL(DEF_VLAN_DOT1QTUNNEL_TPID_0)
#define DFLT_VLAN_DOT1QTUNNEL_TPID_1        DEFDB_VAL(DEF_VLAN_DOT1QTUNNEL_TPID_1)
#define DFLT_VLAN_DOT1QTUNNEL_TPID_2        DEFDB_VAL(DEF_VLAN_DOT1QTUNNEL_TPID_2)
#define DFLT_VLAN_DOT1QTUNNEL_TPID_3        DEFDB_VAL(DEF_VLAN_DOT1QTUNNEL_TPID_3)

#define DFLT_VLAN_PORT_TPID                 DFLT_VLAN_DOT1QTUNNEL_TPID_0
#else
#define DFLT_VLAN_PORT_TPID                 0x8100
#endif

#ifdef CONFIG_SYS_VOICEVLAN

#define DFLT_VLAN_VOICE_EBL                 DEFDB_VAL(DEF_VLAN_VOICE_ENABLE)
#define DFLT_VLAN_VOICE_PORT_EBL            DEFDB_VAL(DEF_VLAN_VOICE_PORT_ENABLE)
#define DFLT_VLAN_VOICE_PORT_MODE           DEFDB_VAL(DEF_VLAN_VOICE_PORT_MODE)
#define DFLT_VLAN_VOICE_PORT_COS_MODE       DEFDB_VAL(DEF_VLAN_VOICE_PORT_COS_MODE)
#define DFLT_VLAN_VOICE_REMARK_EBL          DEFDB_VAL(DEF_VLAN_VOICE_REMARK_ENABLE)
#define DFLT_VLAN_VOICE_VLAN                DEFDB_VAL(DEF_VLAN_VOICE_VID)
#define DFLT_VLAN_VOICE_PRI                 DEFDB_VAL(DEF_VLAN_VOICE_PRI)
#define DFLT_VLAN_VOICE_AGING               DEFDB_VAL(DEF_VLAN_VOICE_AGING)
#endif

#ifdef CONFIG_SYS_SURVEILLANCEVLAN

#define DFLT_VLAN_SURVEILLANCE_EBL          DEFDB_VAL(DEF_VLAN_SURVEILLANCE_ENABLE)
#define DFLT_VLAN_SURVEILLANCE_REMARK_EBL   DEFDB_VAL(DEF_VLAN_SURVEILLANCE_REMARK_ENABLE)
#define DFLT_VLAN_SURVEILLANCE_VLAN         DEFDB_VAL(DEF_VLAN_SURVEILLANCE_VID)
#define DFLT_VLAN_SURVEILLANCE_PRI          DEFDB_VAL(DEF_VLAN_SURVEILLANCE_PRI)
#define DFLT_VLAN_SURVEILLANCE_AGING        DEFDB_VAL(DEF_VLAN_SURVEILLANCE_AGING)
#define DFLT_VLAN_SURVEILLANCE_PORT_EBL     DEFDB_VAL(DEF_VLAN_SURVEILLANCE_PORT_ENABLE)
#define DFLT_VLAN_SURVEILLANCE_PORT_MODE    DEFDB_VAL(DEF_VLAN_SURVEILLANCE_PORT_MODE)
#define DFLT_VLAN_SURVEILLANCE_PORT_COS_MODE DEFDB_VAL(DEF_VLAN_SURVEILLANCE_PORT_COS_MODE)
#endif

#ifdef CONFIG_SYS_PROTO_GVRP
#define DFLT_GVRP_HOLD_TIME                 10
#define DFLT_GVRP_JOIN_TIME                 20
#define BOND_GVRP_JOIN_TIME_MIN             2
#define BOND_GVRP_JOIN_TIME_MAX             16375
#define DFLT_GVRP_LEAVE_TIME                60
#define BOND_GVRP_LEAVE_TIME_MIN            45
#define BOND_GVRP_LEAVE_TIME_MAX            32760
#define DFLT_GVRP_LEAVEALL_TIME             1000
#define BOND_GVRP_LEAVEALL_TIME_MIN         65
#define BOND_GVRP_LEAVEALL_TIME_MAX         32765

#define DFLT_GVRP_EBL                       DEFDB_VAL(DEF_GVRP_EBL)
#define DFLT_GVRP_PORT_EBL                  DEFDB_VAL(DEF_GVRP_PORT_EBL)
#define DFLT_GVRP_PORT_REG                  GVRP_NORMAL
#define DFLT_GVRP_PORT_FORBID               DISABLED
#endif

#ifdef CONFIG_SYS_PROTO_GARP
#define DFLT_GARP_HOLD_TIME                 10
#define DFLT_GARP_JOIN_TIME                 20
#define BOND_GARP_JOIN_TIME_MIN             2
#define BOND_GARP_JOIN_TIME_MAX             16375
#define DFLT_GARP_LEAVE_TIME                60
#define BOND_GARP_LEAVE_TIME_MIN            45
#define BOND_GARP_LEAVE_TIME_MAX            32760
#define DFLT_GARP_LEAVEALL_TIME             1000
#define BOND_GARP_LEAVEALL_TIME_MIN         65
#define BOND_GARP_LEAVEALL_TIME_MAX         32765

#define DFLT_GMRP_EBL                       DEFDB_VAL(DEF_GMRP_EBL)
#define DFLT_GMRP_PORT_EBL                  DEFDB_VAL(DEF_GMRP_PORT_EBL)
#define DFLT_GMRP_PORT_REG                  GVRP_NORMAL
#define DFLT_GMRP_PORT_FORBID               DISABLED
#endif

#endif 

