
#ifndef __SYS_SWDEF_COMMON_H__
#define __SYS_SWDEF_COMMON_H__
#define SYS_BUF8_LEN                 8
#define SYS_BUF16_LEN                16
#define SYS_BUF32_LEN                32
#define SYS_BUF64_LEN                64
#define SYS_BUF128_LEN               128
#define SYS_BUF256_LEN               256
#define SYS_BUF512_LEN               512
#define SYS_BUF1024_LEN              1024
#define SYS_BUF1536_LEN              1536
#define SYS_BUF2048_LEN              2048
#define SYS_BUF4096_LEN              4096

#define CAPA_NAME_STR_LEN            32
#define CAPA_PORT_STR_LEN            32
#define CAPA_PORTMASK_STR_LEN        256
#define CAPA_PORTDESC_STR_LEN        32
#define CAPA_VLANLIST_STR_LEN        1536
#define CAPA_FILE_FULLNAME_LEN       256
#define CAPA_FILE_NAME_LEN           128
#define CAPA_MAC_STR_LEN             24
#define CAPA_MAC_BYTE_NUM            6
#define CAPA_IPV4_STR_LEN            16
#define CAPA_IPV6_BYTE_NUM           16
#define CAPA_IPV6_STR_LEN            46     
#define CAPA_HOSTNAME_LEN            255    

#ifdef CONFIG_SYS_PROTO_STP
#define CAPA_MST_INSTANCE_NUM        CAPA_STP_MST_INSTANCE_NUM
#else
#define CAPA_MST_INSTANCE_NUM        16
#endif
#define BOND_L4_PORT_MIN             0      
#define BOND_L4_PORT_MAX             65535  
#define DFLT_CPU_PORT_ULTI_QUEUE0_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE1_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE2_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE3_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE4_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE5_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE6_WEIGHT 1
#define DFLT_CPU_PORT_ULTI_QUEUE7_WEIGHT 1
#define DFLT_CPU_PORT_SCHEDULE_ALGO      WRR
#define DFLT_THREAD_PRI_BOARD_EXTGPIO    SYS_THREAD_PRI_HIGH
#ifdef CONFIG_SYS_PROTO_DHCPSNOOPING
#define DFLT_THREAD_PRI_DHCP_RL_TIMER    SYS_THREAD_PRI_HIGH
#endif
#define DFLT_THREAD_PRI_L2_ROUTINE       SYS_THREAD_PRI_LOW
#ifdef CONFIG_SYS_PROTO_DAI
#define DFLT_THREAD_PRI_ARP_RL_TIMER     SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_PROTO_IGMP_SNOOPING
#define DFLT_THREAD_PRI_IGMP_TIMER       SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_PROTO_LLDP
#define DFLT_THREAD_PRI_LLDP_TX          SYS_THREAD_PRI_LOW
#define DFLT_THREAD_PRI_LLDP_TIMER       SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_PROTO_STP
#define DFLT_THREAD_PRI_MSTP_FSM         SYS_THREAD_PRI_HIGH
#define DFLT_THREAD_PRI_MSTP_ROUTINE     SYS_THREAD_PRI_HIGH
#define DFLT_THREAD_PRI_MSTP_TIMER       SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_DOS_PROTECTION
#define DFLT_THREAD_PRI_DOS              SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_PROTO_ISG
#define DFLT_THREAD_PRI_IPSG_TIMER       SYS_THREAD_PRI_DFLT
#endif
#ifdef CONFIG_SYS_PORT_SECURITY
#define DFLT_THREAD_PRI_PORTSEC_TX      SYS_THREAD_PRI_LOW
#endif
#ifdef CONFIG_SYS_PROTO_UDLD
#define DFLT_THREAD_PRI_UDLD_TX          SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_SURVEILLANCEVLAN
#define DFLT_THREAD_PRI_SURVEVLAN_TIMER  SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_VOICEVLAN
#define DFLT_THREAD_PRI_VOICEVLAN_TIMER  SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_L3_ROUTE
#define DFLT_THREAD_PRI_L3_TIMER         SYS_THREAD_PRI_DFLT
#endif
#ifdef CONFIG_SYS_ADVANCE_DNS
#define DFLT_THREAD_PRI_DNS_TIMER        SYS_THREAD_PRI_DFLT
#endif
#ifdef CONFIG_SYS_PROTO_ERPS
#define DFLT_THREAD_PRI_ERPS_TIMER       SYS_THREAD_PRI_HIGH
#endif
#ifdef CONFIG_SYS_PROTO_LOOPBACK
#define DFLT_THREAD_PRI_LOOPBACK_TX          SYS_THREAD_PRI_LOW
#define DFLT_THREAD_PRI_LOOPBACK_TIMER       SYS_THREAD_PRI_HIGH
#endif

#endif 

