
#ifndef __SYS_SWDEF_ISG_H__
#define __SYS_SWDEF_ISG_H__
#define CAPA_IPSG_ENTRY_NUM           DEFDB_VAL(DEF_IPSG_ENTRY_NUM)
#define BOND_IPSG_PORT_ENTRY_MIN      1
#define BOND_IPSG_PORT_ENTRY_MAX      50
#define BOND_IPSG_DB_TIMEOUT_MIN      0
#define BOND_IPSG_DB_TIMEOUT_MAX      86400
#define BOND_IPSG_DB_WRITE_DELAY_MIN  15
#define BOND_IPSG_DB_WRITE_DELAY_MAX  86400
#define DFLT_IPSG_PORT_EBL             DEFDB_VAL(DEF_IPSG_PORT_EBL)
#define DFLT_IPSG_PORT_MAX_ENTRY       DEFDB_VAL(DEF_IPSG_PORT_MAX_ENTRY)
#define DFLT_IPSG_DB_TIMEOUT           DEFDB_VAL(DEF_IPSG_DB_TIMEOUT)
#define DFLT_IPSG_DB_WRITE_DELAY       DEFDB_VAL(DEF_IPSG_DB_WRITE_DELAY)
#endif 

