
#ifndef __SYS_SWDEF_AUTHMGR_H__
#define __SYS_SWDEF_AUTHMGR_H__
#define CAPA_AUTHMGR_SESSION_NUM                DEFDB_VAL(DEF_AUTHMGR_SESSION_NUM)
#ifdef CONFIG_SYS_PROTO_MACAUTH
#define CAPA_AUTHMGR_MACAUTH_LOCAL_NUM          256
#endif
#ifdef CONFIG_SYS_PROTO_WEBAUTH
#define CAPA_AUTHMGR_WEBAUTH_LOCAL_NUM          64
#endif
#ifdef CONFIG_SYS_PROTO_DOT1X
#define CAPA_AUTHMGR_DOT1X_USERNAME_LEN         255
#define CAPA_AUTHMGR_DOT1X_STATE_AVP_LEN        128
#endif
#define BOND_AUTHMGR_REAUTH_PERIOD_MIN          300
#define BOND_AUTHMGR_REAUTH_PERIOD_MAX          2147483647
#define BOND_AUTHMGR_INACT_TIMEOUT_MIN          60
#define BOND_AUTHMGR_INACT_TIMEOUT_MAX          65535
#define BOND_AUTHMGR_QUIET_PERIOD_MIN           0
#define BOND_AUTHMGR_QUIET_PERIOD_MAX           65535
#ifdef CONFIG_SYS_PROTO_DOT1X
#define BOND_AUTHMGR_EAP_TX_PERIOD_MIN          1
#define BOND_AUTHMGR_EAP_TX_PERIOD_MAX          65535
#define BOND_AUTHMGR_SUPP_TIMEOUT_MIN           1
#define BOND_AUTHMGR_SUPP_TIMEOUT_MAX           65535
#define BOND_AUTHMGR_SRV_TIMEOUT_MIN            1
#define BOND_AUTHMGR_SRV_TIMEOUT_MAX            65535
#define BOND_AUTHMGR_MAX_REQ_MIN                1
#define BOND_AUTHMGR_MAX_REQ_MAX                10
#endif
#define BOND_AUTHMGR_MAX_HOST_MIN               1
#define BOND_AUTHMGR_MAX_HOST_MAX               CAPA_AUTHMGR_SESSION_NUM
#ifdef CONFIG_SYS_PROTO_WEBAUTH
#define BOND_AUTHMGR_WEBAUTH_LOGIN_NUM_MIN      3
#define BOND_AUTHMGR_WEBAUTH_LOGIN_NUM_MAX      10
#endif
#ifdef CONFIG_SYS_PROTO_DOT1X
#define DFLT_AUTHMGR_DOT1X_EBL                  DEFDB_VAL(DEF_AUTHMGR_DOT1X_EBL)
#endif
#ifdef CONFIG_SYS_PROTO_MACAUTH
#define DFLT_AUTHMGR_MAC_EBL                    DEFDB_VAL(DEF_AUTHMGR_MAC_EBL)
#endif
#ifdef CONFIG_SYS_PROTO_WEBAUTH
#define DFLT_AUTHMGR_WEB_EBL                    DEFDB_VAL(DEF_AUTHMGR_WEB_EBL)
#endif
#define DFLT_AUTHMGR_GUEST_VLAN                 DEFDB_VAL(DEF_AUTHMGR_GUEST_VLAN)               
#ifdef CONFIG_SYS_PROTO_MACAUTH
#define DFLT_AUTHMGR_RADIUS_USER_DELIMIT        DEFDB_VAL(DEF_AUTHMGR_RADIUS_USER_DELIMIT)
#define DFLT_AUTHMGR_RADIUS_USER_GAP            DEFDB_VAL(DEF_AUTHMGR_RADIUS_USER_GAP)
#define DFLT_AUTHMGR_RADIUS_USER_CASE           DEFDB_VAL(DEF_AUTHMGR_RADIUS_USER_CASE)
#endif
#define DFLT_AUTHMGR_PORT_CTRL                  DEFDB_VAL(DEF_AUTHMGR_PORT_CTRL)
#ifdef CONFIG_SYS_PROTO_DOT1X
#define DFLT_AUTHMGR_PORT_DOT1X_EBL             DEFDB_VAL(DEF_AUTHMGR_PORT_DOT1X_EBL)
#endif
#ifdef CONFIG_SYS_PROTO_MACAUTH
#define DFLT_AUTHMGR_PORT_MAC_EBL               DEFDB_VAL(DEF_AUTHMGR_PORT_MAC_EBL)
#endif
#ifdef CONFIG_SYS_PROTO_WEBAUTH
#define DFLT_AUTHMGR_PORT_WEB_EBL               DEFDB_VAL(DEF_AUTHMGR_PORT_WEB_EBL)
#endif
#define DFLT_AUTHMGR_PORT_ORDER_FIRST           DEFDB_VAL(DEF_AUTHMGR_PORT_ORDER_FIRST)
#define DFLT_AUTHMGR_PORT_METHOD_ORDER_FIRST    DEFDB_VAL(DEF_AUTHMGR_PORT_METHOD_ORDER_FIRST)
#define DFLT_AUTHMGR_PORT_MODE                  DEFDB_VAL(DEF_AUTHMGR_PORT_MODE)
#define DFLT_AUTHMGR_PORT_REAUTH_EBL            DEFDB_VAL(DEF_AUTHMGR_PORT_REAUTH_EBL)
#define DFLT_AUTHMGR_PORT_GUEST_VLAN_EBL        DEFDB_VAL(DEF_AUTHMGR_PORT_GUEST_VLAN_EBL)
#define DFLT_AUTHMGR_PORT_MAX_HOSTS             DEFDB_VAL(DEF_AUTHMGR_PORT_MAX_HOSTS)
#define DFLT_AUTHMGR_PORT_VLAN_ASSIGN_MODE      DEFDB_VAL(DEF_AUTHMGR_PORT_VLAN_ASSIGN_MODE)
#define DFLT_AUTHMGR_PORT_REAUTH_PERIOD         DEFDB_VAL(DEF_AUTHMGR_PORT_REAUTH_PERIOD)
#define DFLT_AUTHMGR_PORT_INACT_PERIOD          DEFDB_VAL(DEF_AUTHMGR_PORT_INACT_PERIOD)
#define DFLT_AUTHMGR_PORT_QUIET_PERIOD          DEFDB_VAL(DEF_AUTHMGR_PORT_QUIET_PERIOD)
#ifdef CONFIG_SYS_PROTO_DOT1X
#define DFLT_AUTHMGR_PORT_MAX_REQ               DEFDB_VAL(DEF_AUTHMGR_PORT_MAX_REQ)
#define DFLT_AUTHMGR_PORT_EAP_TX_PERIOD         DEFDB_VAL(DEF_AUTHMGR_PORT_EAP_TX_PERIOD)
#define DFLT_AUTHMGR_PORT_SUPP_TIMEOUT          DEFDB_VAL(DEF_AUTHMGR_PORT_SUPP_TIMEOUT)
#define DFLT_AUTHMGR_PORT_SRV_TIMEOUT           DEFDB_VAL(DEF_AUTHMGR_PORT_SRV_TIMEOUT)
#endif
#ifdef CONFIG_SYS_PROTO_WEBAUTH
#define DFLT_AUTHMGR_PORT_WEBAUTH_LOGIN_ATTEMPT DEFDB_VAL(DEF_AUTHMGR_PORT_WEBAUTH_LOGIN_ATTEMPT)
#endif

#endif 

