
#ifndef __SYS_SWDEF_SNMP_H__
#define __SYS_SWDEF_SNMP_H__
#define CAPA_SNMP_COMMUNITY_NUM         8
#define CAPA_SNMP_VIEW_NUM              16
#define CAPA_SNMP_USER_NUM              8
#define CAPA_SNMP_GROUP_NUM             (CAPA_SNMP_COMMUNITY_NUM + CAPA_SNMP_USER_NUM)
#define CAPA_SNMP_HOST_NUM              DEFDB_VAL(DEF_SNMP_HOST_NUM)
#define CAPA_SNMP_HOST_NUM_MAX          8
#define CAPA_SNMP_REMOTE_ENGINEID_NUM   8

#define CAPA_SNMP_COMMUNITY_LEN         20
#define CAPA_SNMP_VIEW_NAME_LEN         30
#define CAPA_SNMP_GROUP_NAME_LEN        30  
#define CAPA_SNMP_SEC_NAME_LEN          32
#define CAPA_SNMP_SOURCE_NET_LEN        18
#define CAPA_SNMP_CONTEXT_LEN           16
#define CAPA_SNMP_USER_NAME_LEN         30
#define CAPA_SNMP_VIEW_SUBTREE_LEN      20
#define CAPA_SNMP_OID_STR_LEN           128
#define BOND_SNMP_AUTH_KEY_LEN_MIN      8
#define BOND_SNMP_AUTH_KEY_LEN_MAX      32
#define BOND_SNMP_PRIV_KEY_LEN_MIN      8
#define BOND_SNMP_PRIV_KEY_LEN_MAX      64

#define BOND_SNMP_NOTIFY_PORT_MIN       1
#define BOND_SNMP_NOTIFY_PORT_MAX       65535
#define BOND_SNMP_NOTIFY_TIMEOUT_MIN    1
#define BOND_SNMP_NOTIFY_TIMEOUT_MAX    300
#define BOND_SNMP_NOTIFY_RETRY_MIN      1
#define BOND_SNMP_NOTIFY_RETRY_MAX      255

#define BOND_SNMP_ENGINEID_LEN_MIN      10
#define BOND_SNMP_ENGINEID_LEN_MAX      64
#define DFLT_SNMP_EBL                   DEFDB_VAL(DEF_SNMP_EBL)

#ifdef CONFIG_SYS_MIB_TRAP
#define DFLT_SNMP_TRAP_EBL              DEFDB_VAL(DEF_SNMP_TRAP_EBL)
#endif
#ifdef CONFIG_SYS_SNMPV3
#define DFLT_SNMP_ENTERPRISE_NUM        DEFDB_STR(DEF_SNMP_ENTERPRISE)       
#define DFLT_SNMP_COMMUNITY             DEFDB_STR(DEF_SNMP_COMMUNITY)
#define DFLT_SNMP_COMMUNITY_ACCESS      DEFDB_VAL(DEF_SNMP_COMMUNITY_ACCESS)
#endif

#define DFLT_SNMP_VIEW_STR              "all"
#ifdef CONFIG_SYS_SNMPV3
#define DFLT_SNMP_VIEWTYPE              SNMP_VIEWTYPE_INCLUDE
#define DFLT_SNMP_VIEW_SUBTREE_STR      "1"
#endif

#define DFLT_SNMP_NOTIFACTION_PORT      162
#define DFLT_SNMP_INFORM_TIMEOUT        15
#define DFLT_SNMP_INFORM_RETRY          3
#endif 

