
#ifndef __SYS_SWDEF_L2_H__
#define __SYS_SWDEF_L2_H__
#define CAPA_L2_STATIC_MAC_NUM                DEFDB_VAL(DEF_L2_STATIC_MAC_NUM)
#ifdef CONFIG_SYS_BLACK_HOLE_MAC
#define CAPA_L2_FILTER_MAC_NUM                DEFDB_VAL(DEF_L2_FILTER_MAC_NUM)
#endif
#define CAPA_L2_MAC_CAM_ENTRY_NUM             64
#define CAPA_L2_MAC_ENTRY_MAX_NUM             L2_HW_ENTRY_NUM
#define CAPA_L2_MAC_DISABLE_LEARNING_MAX_NUM  L2_HW_DISABLE_LEARN_NUM

#define CAPA_L2_MOVE_MAC_NUM                  100
#define BOND_L2_MAC_AGING_MIN              DEFDB_VAL(DEF_L2_MAC_AGING_MIN)
#define BOND_L2_MAC_AGING_MAX              DEFDB_VAL(DEF_L2_MAC_AGING_MAX)
#ifdef CONFIG_SYS_L3_ROUTE
#define DFLT_L2_SOFTWARE_DATABSE_MODE     ENABLED
#else
#define DFLT_L2_SOFTWARE_DATABSE_MODE     DISABLED
#endif
#define DFLT_L2_AGING_TIME                DEFDB_VAL(DEF_L2_AGING_TIME)
#endif 

