
#ifndef __SYS_SWDEF_SECURITY_H__
#define __SYS_SWDEF_SECURITY_H__
#define CAPA_PSECURE_LIMIT_NUM          DEFDB_VAL(DEF_PSECURE_LIMIT_NUM)
#ifdef CONFIG_SYS_PORT_SECURITY
#define BOND_PSECURE_LIMITNUM_MIN       1
#define BOND_PSECURE_LIMITNUM_MAX       CAPA_PSECURE_LIMIT_NUM
#define BOND_PSECURE_RATELIMIT_MIN      1
#define BOND_PSECURE_RATELIMIT_MAX      600
#endif
#ifdef CONFIG_SYS_PORT_SECURITY
#define DFLT_PSECURE_EBL                DEFDB_VAL(DEF_PSECURE_EBL)
#define DFLT_PSECURE_RATELIMIT          DEFDB_VAL(DEF_PSECURE_RATELIMIT)
#define DFLT_PSECURE_PORT_EBL           DEFDB_VAL(DEF_PSECURE_PORT_EBL)
#define DFLT_PSECURE_PORT_LIMITNUM      DEFDB_VAL(DEF_PSECURE_PORT_LIMITNUM)
#define DFLT_PSECURE_PORT_VIOLATION     DEFDB_VAL(DEF_PSECURE_PORT_VIOLATION)
#define DFLT_PSECURE_PORT_STICKY        DEFDB_VAL(DEF_PSECURE_PORT_STICKY)
#endif
#endif 

