
#ifndef __SYS_SWDEF_RATE_H__
#define __SYS_SWDEF_RATE_H__
#define BOND_RATE_UNLIMITED                  0xFFFFF   

#define BOND_RATE_STORM_BPS_MIN              16
#define BOND_RATE_STORM_BPS_MAX              1000000
#define BOND_RATE_STORM_PPS_MIN              1
#define BOND_RATE_STORM_PPS_MAX              0x3FFFF

#define BOND_RATE_BANDWIDTH_MIN              16
#define BOND_RATE_BANDWIDTH_MAX              1000000
#define BOND_RATE_BANDWIDTH_BURST_MIN        1
#define BOND_RATE_BANDWIDTH_BURST_MAX        0xFFFF
#define DFLT_RATE_STORM_MODE                  DEFDB_VAL(DEF_RATE_STORM_MODE)
#define DFLT_RATE_STORM_PREABMLE              DEFDB_VAL(DEF_RATE_STORM_PREABMLE)
#define DFLT_RATE_STORM_PORT_EBL              DEFDB_VAL(DEF_RATE_STORM_PORT_EBL)
#define DFLT_RATE_STORM_BCAST_EBL             DEFDB_VAL(DEF_RATE_STORM_BCAST_EBL)
#define DFLT_RATE_STORM_MCAST_EBL             DISABLED    
#define DFLT_RATE_STORM_UMCAST_EBL            DEFDB_VAL(DEF_RATE_STORM_UMCAST_EBL)
#define DFLT_RATE_STORM_UUCAST_EBL            DEFDB_VAL(DEF_RATE_STORM_UUCAST_EBL)
#define DFLT_RATE_STORM_CTRL                  DEFDB_VAL(DEF_RATE_STORM_CTRL)
#define DFLT_RATE_STORM_ACTION                DEFDB_VAL(DEF_RATE_STORM_ACTION)

#define DFLT_RATE_FWD_IGR_PREABMLE            DEFDB_VAL(DEF_RATE_FWD_IGR_PREABMLE)
#define DFLT_RATE_IGR_BURST_THRESH            0x8000
#define DFLT_RATE_PORT_IGR                    0xFFFF
#define DFLT_RATE_PORT_IGR_EBL                DEFDB_VAL(DEF_RATE_PORT_IGR_EBL)
#define DFLT_RATE_PORT_EGR_FE                 0x186a
#define DFLT_RATE_PORT_EGR_GE                 0xF424
#define DFLT_RATE_PORT_EGR_EBL                DEFDB_VAL(DEF_RATE_PORT_EGR_EBL)
#define DFLT_RATE_PORT_EGR_BURST_THRESH       0x8000      
#define DFLT_RATE_QUEUE_EGR_BURST_THRESH      0x8000      

#endif 

