
#ifndef __SYS_SWDEF_DHCP_H__
#define __SYS_SWDEF_DHCP_H__
#define BOND_DHCP_SNOOPING_RATELIMIT_MIN                1
#define BOND_DHCP_SNOOPING_RATELIMIT_MAX                300
#define DFLT_DHCP_SNOOPING_EBL                          DEFDB_VAL(DEF_DHCP_SNOOPING_EBL)
#define DFLT_DHCP_SNOOPING_PORT_TRUST                   DEFDB_VAL(DEF_DHCP_SNOOPING_PORT_TRUST)
#define DFLT_DHCP_SNOOPING_PORT_OPTION82_ENABLE         DEFDB_VAL(DEF_DHCP_SNOOPING_PORT_OPTION82_ENABLE)
#define DFLT_DHCP_SNOOPING_PORT_OPTION82_ACTION         DEFDB_VAL(DEF_DHCP_SNOOPING_PORT_OPTION82_ACTION)
#define DFLT_DHCP_SNOOPING_RATE_LIMIT                   DEFDB_VAL(DEF_DHCP_SNOOPING_RATE_LIMIT)
#define DFLT_DHCP_SERVER_EBL                          DEFDB_VAL(DEF_DHCP_SERVER_EBL)

#endif 

