
#ifndef __SYS_SWDEF_SYSLOG_H__
#define __SYS_SWDEF_SYSLOG_H__
#define CAPA_LOG_HOST_NUM                   DEFDB_VAL(DEF_LOG_HOST_NUM)
#define BOND_LOG_AGGREGATION_INTERVAL_MIN   15
#define BOND_LOG_AGGREGATION_INTERVAL_MAX   3600
#define BOND_LOG_HOST_PORT_MIN              1
#define BOND_LOG_HOST_PORT_MAX              65535
#define DFLT_LOG_EBL                        DEFDB_VAL(DEF_LOG_EBL)
#define DFLT_LOG_BUFFERED_EBL               DEFDB_VAL(DEF_LOG_BUFFERED_EBL)
#define DFLT_LOG_CONSOLE_EBL                DEFDB_VAL(DEF_LOG_CONSOLE_EBL)
#define DFLT_LOG_FILE_EBL                   DEFDB_VAL(DEF_LOG_FILE_EBL)
#define DFLT_LOG_AGGREGATION_EBL            DEFDB_VAL(DEF_LOG_AGGREGATION_EBL)
#define DFLT_LOG_AGGREGATION_INTERVAL       300
#define DFLT_LOG_HOST_PORT                  514
#define DFLT_LOG_HOST_DELAY_TIME            60
#define DFLT_LOG_BUFFERED_SEVERITY          DEFDB_VAL(DEF_LOG_BUFFERED_SEVERITY)
#define DFLT_LOG_BUFFERED_TOTAL             DEFDB_VAL(DEF_LOG_BUFFERED_TOTAL)
#define DFLT_LOG_CONSOLE_SEVERITY           DEFDB_VAL(DEF_LOG_CONSOLE_SEVERITY)
#define DFLT_LOG_FILE_SEVERITY              DEFDB_VAL(DEF_LOG_FILE_SEVERITY)
#define DFLT_LOG_FILE_TOTAL                 DEFDB_VAL(DEF_LOG_FILE_TOTAL)
#define DFLT_LOG_HOST_SEVERITY              DEFDB_VAL(DEF_LOG_HOST_SEVERITY)

#endif 

