/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */
#ifndef SNMPTRAPS_H
#define SNMPTRAPS_H

#include <libipc/smdMsgRequest.h>
#include <libvty/thread.h>
#include <libsal/sal_snmp.h>
#include <libsal/sal_sys_line.h>


#define SNMP_TRAP_POLL_TIMER   3

#define SNMP_DBG_TARGET_FILE1 "/tmp/SNMP_DEBUG1"
#if 0
#define SNMP_DBG1(a,args...) \
 do { \
	 char tmp_str[256] = ""; \
	 char cmd_str[300] = ""; \
	 sprintf(tmp_str, "[SNMP_DBG] %s:%d:"#a"", __FUNCTION__,__LINE__, ##args); \
	 sprintf(cmd_str, "echo \"%s\" >> %s", tmp_str, SNMP_DBG_TARGET_FILE1); \
	 system(cmd_str); \
 } while (0)
#else
#define SNMP_DBG1(a,args...) {}
#endif


int snmpTrapAppWrapFunction(void);
int snmpTrapAppWrapProcess(SMD_MSG *pMsg);
static int trap_thread_read (struct thread *thread);

int netsnmp_trap_send(void);
void netsnmp_trap_process(void *input);
int  snmptrap_thread_create(char    *pName, int     stack_size, int     thread_pri, void    (f)(void *), void    *pArg);
void init_snmptrap_thread(void);


/* function declarations */
int send_coldStart_trap(void);
int send_warmStart_trap(void);
int send_linkDown_trap(char *buf);
int send_linkUp_trap(char *buf);
int send_authenticationFailure_trap(char *pSecName);
int send_psePortOnOff_trap(char *buf);
int send_pseMainUsage_trap(char *buf);
int monitorSysReadySnmpTrapTimerProcess(struct thread *t);

#endif /* SNMPTRAPS_H */
