/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "snmpTraps.h"
#include <common/sys_type.h>
//new add for trap
#include <pthread.h>
#include <signal.h>
#include <string.h>
#include <common/sys_def.h>
#include <osal/thread.h>
#include <osal/lib.h>
#include <osal/print.h>
#include <osal/sem.h>
#include <osal/time.h>
#include <osal/memory.h>
#include <libcustom/sal_custom.h>
#include <libsal/sal_mib_private.h>
#include <libipc/vosMsg.h>
#include <libipc/smdCmdWrap.h>
#include <libvty/thread.h>
#include "snmpCmtraps.h"
#include <libsal/sal_time.h>


/* Master of threads. */
struct thread_master *master;

static oid snmptrap_std_oid[] = {1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0};
static int  _isSysStartTime = TRUE;
SMD_WRAP_CMD snmpTrapServerWrap[TRAP_FUNC_MAX];

osal_thread_t snmptrap_thread_create(char *pName, int stack_size, int thread_pri, void (f)(void *), void *pArg)
{
    pthread_attr_t  attr;
    pthread_t       id;

    if (0 != pthread_attr_init(&attr))
    {
        /* thread property configuration error */
        return (osal_thread_t)NULL;
    }

    pthread_attr_setstacksize(&attr, stack_size);

    if (pthread_create(&id, NULL, (void *)f, (void *)pArg))
    {
        return (osal_thread_t)NULL;
    }

    return ((osal_thread_t)id);
} /* end of osal_thread_create */
void netsnmp_trap_process(void *input)
{
    static int i = 0;
	int iMsgHd;
	uchar_t buff[2048]; /*接收消息流缓冲区*/
	VOS_MSG_ADDR			 clientAddr;
	SMD_MSG 				 *pSmdMsg;
	int iRet = 0;
	struct thread thread;
	ulong_t 				*pulTimerHande;

    /*OEM trap节点替换*/
	netsnmp_trap_oid_oem_init();

	/* Prepare master thread. */
	master = thread_master_create ();

	vosMsgInit(SNMP_TRAP_SERVER_PATH, VOS_MSG_SOURCE_PROCESS, &iMsgHd);
	
	thread_add_read (master, trap_thread_read, (void *)iMsgHd, iMsgHd);

    /*命令参数解析函数注册*/
    snmpTrapAppWrapFunction();

	/*只运行一次*/
	//netsnmp_trap_send();
	thread_add_timer(master, monitorSysReadySnmpTrapTimerProcess, NULL, 4);

	/* Execute each thread. */
	while (thread_fetch (master, &thread))
	  thread_call (&thread);

#if 0
    while(1)
    {
        //netsnmp_trap_send();

        
        //sleep(SNMP_TRAP_POLL_TIMER);  /* PASS_SECONDS Sec */
    }
#endif
    pthread_exit(0);
    snmp_log(LOG_DEBUG, "Net-snmp trap process thread is exit !\n");
}

void init_snmptrap_thread(void)
{

    if ((int *)NULL == (snmptrap_thread_create("Net-snmp Trap Thread", 32768, 35, (void *)netsnmp_trap_process, NULL)))
    {
        snmp_log(LOG_DEBUG, "init_traps failure \n");
    }

}

int32 netsnmp_trap_send_mux(char *buf)
{
    int32 trapCode;

    if (NULL == buf)
        return SYS_ERR_FAILED;

    trapCode = atoi(buf);
    //snmp_log(LOG_DEBUG, "Snmp trap code:%d \n", trapCode);

    switch(trapCode)
    {
        case SNMP_TRAP_CODE_COLD_START:
            send_coldStart_trap();
            break;

        case SNMP_TRAP_CODE_WARM_START:
            send_warmStart_trap();
            break;

        case SNMP_TRAP_CODE_LINKDOWN:
            send_linkDown_trap(buf);
            break;

        case SNMP_TRAP_CODE_LINKUP:
            send_linkUp_trap(buf);
            break;

/*
        case SNMP_TRAP_CODE_AUTH_FAILD:
            send_authenticationFailure_trap();
            break;
*/
        case SNMP_TRAP_CODE_PORT_SECURITY:
            send_portSecurity_trap(buf);
            break;

         default:
            break;
    }

    //10ms
    usleep(10*1000);
    return SYS_ERR_OK;
}



int netsnmp_trap_send(void)
{
    uint64 sysUptime = 0;
    int i;
    sys_snmp_notifyMsg_t notifyMsg;
    uint32 trapCode = 0;

    if (_isSysStartTime)
    {
        sal_snmp_sysUpTimeGep_get(&sysUptime);
        if (sysUptime/100 > SNMP_SYS_STARTTIME_KEEP)
        {
            _isSysStartTime = FALSE;
        }
    }
    //start time, not process
    if (_isSysStartTime)
        return SYS_ERR_FAILED;

    for (i = 0; i < SNMP_NOTIFY_MAX_BUF; i++)
    {
        SYS_MEM_CLEAR(notifyMsg);
        SYS_ERR_CONTINUE(_sal_snmp_notifyMsg_get(i, &notifyMsg));
        if (notifyMsg.valid)
        {
        	trapCode = atoi(notifyMsg.trapMsg);
        	if(trapCode > SNMP_CMTRAP_CODE_START)
        	{
				netsnmp_cmTrap_send_mux(trapCode, notifyMsg.trapMsg);
        	}
        	else 
        	{
            	netsnmp_trap_send_mux(notifyMsg.trapMsg);
            }
            
            notifyMsg.valid = FALSE;
            _sal_snmp_notifyMsg_set(i, &notifyMsg);
        }
    }
	return SYS_ERR_OK;
}

int monitorSysReadySnmpTrapTimerProcess(struct thread *t)
{
	int ret = 0;
	ret = netsnmp_trap_send();
	if(ret != SYS_ERR_OK)
		thread_add_timer(master, monitorSysReadySnmpTrapTimerProcess, NULL, 4);
		
    return 0;
}

int
send_coldStart_trap( void )
{
    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    oid snmptrap_std_oid[] = {1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0};
    oid snmptrap_logTime_oid[] = {1,3,6,1,1,1,3,0};
    oid op_user_msg_oid[] = {  1,3,6,1,4,49763,1,1,2,1,4,3 };
    netsnmp_variable_list  *var_list = NULL;
    char buf[516] = {0};
   	sys_time_str_t            timestring;
	//获取时间
	SYS_MEM_CLEAR(timestring);
	sal_time_currentTimeStr_get(&timestring);
    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_std_oid, OID_LENGTH(snmptrap_std_oid),
        ASN_OBJECT_ID,
        snmptrap_std_oid, sizeof(snmptrap_std_oid));
        
        
	//日志时间
	snmp_varlist_add_variable(&var_list,
        snmptrap_logTime_oid, OID_LENGTH(snmptrap_logTime_oid),
        ASN_OCTET_STR,
        (void *)timestring.tstr, osal_strlen(timestring.tstr));

	//日志类型
    osal_sprintf(buf, "System Cold Start");
   	//snmp_log(LOG_DEBUG, "send trap: %s \n", buf);
    snmp_varlist_add_variable(&var_list,
        op_user_msg_oid, OID_LENGTH(op_user_msg_oid),
        ASN_OCTET_STR,
        (void *)buf, osal_strlen(buf));

    send_trap_vars(SNMP_TRAP_COLDSTART, 1, var_list);
    snmp_free_varbind(var_list );
    return SYS_ERR_OK;
}
int
send_warmStart_trap( void )
{
    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    netsnmp_variable_list  *var_list = NULL;
    char buf[516] = {0};
   	sys_time_str_t            timestring;
	oid snmptrap_std_oid[] = {1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0};
    oid snmptrap_logTime_oid[] = {1,3,6,1,1,1,3,0};
    oid op_user_msg_oid[] = { 1,3,6,1,4,49763,1,1,2,1,4,3 };
	//获取时间
	SYS_MEM_CLEAR(timestring);
	sal_time_currentTimeStr_get(&timestring);
    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_std_oid, OID_LENGTH(snmptrap_std_oid),
        ASN_OBJECT_ID,
        snmptrap_std_oid, sizeof(snmptrap_std_oid));
        
        
	//日志时间
	snmp_varlist_add_variable(&var_list,
        snmptrap_logTime_oid, OID_LENGTH(snmptrap_logTime_oid),
        ASN_OCTET_STR,
        (void *)timestring.tstr, osal_strlen(timestring.tstr));

	//日志类型
    osal_sprintf(buf, "System Warm Start");
   	//snmp_log(LOG_DEBUG, "send trap: %s \n", buf);
    snmp_varlist_add_variable(&var_list,
        op_user_msg_oid, OID_LENGTH(op_user_msg_oid),
        ASN_OCTET_STR,
        (void *)buf, osal_strlen(buf));

    send_trap_vars(SNMP_TRAP_WARMSTART, 1, var_list);
    snmp_free_varbind(var_list );
    return SYS_ERR_OK;
}
int
send_linkDown_trap(char *buf)
{
    char *pTemp = NULL;
    char trapType[24];    /*日志类型*/
    netsnmp_variable_list  *var_list = NULL;
	char *pTemp2 = NULL;
    uint32 typelen = 0;
    oid ifOperStatus_oid[11] = { 1,3,6,1,2,1,2,2,1,8,0};
    oid snmptrap_logType_oid[] = {1, 3, 6, 1, 4, 1, 27282, 1, 1, 2, 1, 1};
    oid snmptrap_logTime_oid[] = {1, 3, 6, 1, 4, 1, 27282, 1, 1, 2, 1, 2};
    sys_time_str_t            timestring;
	//获取时间
	SYS_MEM_CLEAR(timestring);
	sal_time_currentTimeStr_get(&timestring);
	
	if(buf == NULL)
    	return SYS_ERR_FAILED;
	//snmp_log(LOG_DEBUG, "%s %d time=%s type=%s  detail=%s\n", __func__, __LINE__, trapInfo->trapTime, trapInfo->trapType , trapInfo->trapDetail);

    /*
     * Set the snmpTrapOid.0 value
     */
	//日志时间
	//日志时间
	  snmp_varlist_add_variable(&var_list,
		  snmptrap_logTime_oid, OID_LENGTH(snmptrap_logTime_oid),
		  ASN_OCTET_STR,
		  (void *)timestring.tstr, osal_strlen(timestring.tstr));

    //日志类型
    osal_sprintf(trapType, "Port status");
    snmp_varlist_add_variable(&var_list,
        snmptrap_logType_oid, OID_LENGTH(snmptrap_logType_oid),
        ASN_OCTET_STR,
        (void *)trapType, osal_strlen(trapType));

    //snmp_log(LOG_DEBUG, "trap info: %s \n", pTemp2);     


    //日志内容
    snmp_varlist_add_variable(&var_list,
       	ifOperStatus_oid, OID_LENGTH(ifOperStatus_oid),
        ASN_OCTET_STR,
        (void *)buf, osal_strlen(buf));
	//snmp_log(LOG_DEBUG, "send trap detail: %s \n", trapInfo->trapDetail);

    send_trap_vars(SNMP_TRAP_ENTERPRISESPECIFIC, 1, var_list);
    snmp_free_varbind(var_list );
    return SYS_ERR_OK;
}


int
send_linkUp_trap(char *buf)
{

    char *pTemp = NULL;
    char trapType[24];    /*日志类型*/
    netsnmp_variable_list  *var_list = NULL;
	char *pTemp2 = NULL;
    uint32 typelen = 0;
    oid ifOperStatus_oid[11] = { 1,3,6,1,2,1,2,2,1,8,0};
    oid snmptrap_logType_oid[] = {1, 3, 6, 1, 4, 1, 27282, 1, 1, 2, 1, 1};
    oid snmptrap_logTime_oid[] = {1, 3, 6, 1, 4, 1, 27282, 1, 1, 2, 1, 2};
    sys_time_str_t            timestring;
	//获取时间
	SYS_MEM_CLEAR(timestring);
	sal_time_currentTimeStr_get(&timestring);
    
	if(buf == NULL)
    	return SYS_ERR_FAILED;
	//snmp_log(LOG_DEBUG, "%s %d time=%s type=%s  detail=%s\n", __func__, __LINE__, trapInfo->trapTime, trapInfo->trapType , trapInfo->trapDetail);

    /*
     * Set the snmpTrapOid.0 value
     */
	//日志时间
	  snmp_varlist_add_variable(&var_list,
		  snmptrap_logTime_oid, OID_LENGTH(snmptrap_logTime_oid),
		  ASN_OCTET_STR,
		  (void *)timestring.tstr, osal_strlen(timestring.tstr));

    //日志类型
    osal_sprintf(trapType, "Port status");
    snmp_varlist_add_variable(&var_list,
        snmptrap_logType_oid, OID_LENGTH(snmptrap_logType_oid),
        ASN_OCTET_STR,
        (void *)trapType, osal_strlen(trapType));

    //snmp_log(LOG_DEBUG, "trap info: %s \n", pTemp2);     


    //日志内容
    snmp_varlist_add_variable(&var_list,
       	ifOperStatus_oid, OID_LENGTH(ifOperStatus_oid),
        ASN_OCTET_STR,
        (void *)buf, osal_strlen(buf));
	//snmp_log(LOG_DEBUG, "send trap detail: %s \n", trapInfo->trapDetail);

    send_trap_vars(SNMP_TRAP_ENTERPRISESPECIFIC, 1, var_list);
    snmp_free_varbind(var_list );
    return SYS_ERR_OK;
}

int
send_authenticationFailure_trap(char *pSecName)
{
    sys_enable_t enable = DISABLED, snmp_enable = DISABLED;

    if (pSecName == NULL)
        return SYS_ERR_FAILED;

    sal_snmp_enable_get(&snmp_enable);
#ifdef CONFIG_SYS_MIB_TRAP
    sal_snmp_trapEnable_get(SNMP_TRAP_CLASS_AUTHENTICATE, &enable);
#endif
    if(DISABLED == enable || DISABLED == snmp_enable)
    {
        SNMP_LOG(LOG_SNMP_TRAP_DROP);
        return SYS_ERR_OK;
    }


    /*
     * Set the snmpTrapOid.0 value
     */
    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */

    //sal_snmp_authenticationFailure_send();
    send_trap_vars(SNMP_TRAP_AUTHFAIL, 1, NULL);

    //snmp_log(LOG_DEBUG,"Run snmp log host: %s, name: %s \n", pHost, pSecName);
    SNMP_LOG(LOG_SNMP_AUTH_FAIL, pSecName);

    return SYS_ERR_OK;

}

int send_portSecurity_trap(char *buf)
{
    char *pTemp = NULL;
    netsnmp_variable_list  *var_list = NULL;

    oid portSec_trap_oid[] = {1,3,6,1,4,1,9,6,1,101,0,170};
    oid portSec_msg_oid[] = {1,3,6,1,4,1,9,6,1,101,2,3,1,0};

    pTemp = osal_strchr(buf, ' ');
    if (NULL == pTemp)
        return SYS_ERR_FAILED;

    pTemp++;
    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_std_oid, OID_LENGTH(snmptrap_std_oid),
        ASN_OBJECT_ID,
        portSec_trap_oid, sizeof(portSec_trap_oid));

    snmp_varlist_add_variable(&var_list,
        portSec_msg_oid, OID_LENGTH(portSec_msg_oid),
        ASN_OCTET_STR,
        (void *)pTemp, osal_strlen(pTemp));

    send_trap_vars(SNMP_TRAP_ENTERPRISESPECIFIC, 1, var_list);
    snmp_free_varbind(var_list );

    return SYS_ERR_OK;
}

int send_psePortOnOff_trap(char *buf)
{
    char *pTemp = NULL;
    sys_logic_port_t lport;
    sys_user_port_t  uport;
    uint32  pseGrpId = 1;
    uint32 powerVal = 0;

    oid  psePort_DectStatus_oid[] = {1, 3, 6, 1, 2, 1, 105, 1, 1, 1, 6, 0,0};
    oid  psePort_trap_oid[] = { 1, 3, 6, 1, 2, 1, 105, 0, 1 };

    netsnmp_variable_list  *var_list = NULL;

    pTemp = osal_strchr(buf, ' ');
    if (NULL == pTemp)
        return SYS_ERR_FAILED;
    lport = atoi(++pTemp);
    if (IS_LOGIC_PORT_INVALID(lport))
        return SYS_ERR_FAILED;

    uport = LP2UP(lport);

    pTemp = osal_strchr(pTemp, ' ');
    if (NULL == pTemp)
        return SYS_ERR_FAILED;
    pseGrpId = atoi(++pTemp);

    pTemp = osal_strchr(pTemp, ' ');
    if (NULL == pTemp)
        return SYS_ERR_FAILED;
    powerVal = atoi(++pTemp);

    psePort_DectStatus_oid[11] = pseGrpId;
    psePort_DectStatus_oid[12] = uport;

     /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_std_oid, OID_LENGTH(snmptrap_std_oid),
        ASN_OBJECT_ID,
        psePort_trap_oid, sizeof(psePort_trap_oid));

    snmp_varlist_add_variable(&var_list,
        psePort_DectStatus_oid, OID_LENGTH(psePort_DectStatus_oid),
        ASN_INTEGER,
        (void *)&powerVal, sizeof(int));

    send_trap_vars(SNMP_TRAP_ENTERPRISESPECIFIC, 1, var_list);
    snmp_free_varbind(var_list );

    return SYS_ERR_OK;
}


int send_pseMainUsage_trap(char *buf)
{
    char *pTemp = NULL;
    netsnmp_variable_list  *var_list = NULL;
    uint32 powerUsage = 0;
    uint32 PseConsumptionPower = 0;

    oid  pse_power_usage_oid[] = { 1,3, 6, 1, 2, 1, 105, 0, 2};
    oid  pse_power_Cspt_oid[] = { 1, 3, 6, 1, 2, 1, 105, 1, 3, 1, 1, 4, 1};

    pTemp = osal_strchr(buf, ' ');
    if (NULL == pTemp)
        return SYS_ERR_FAILED;
    powerUsage = atoi(++pTemp);
    //power off
    if (0 == powerUsage)
        pse_power_usage_oid[8] = 3;

    pTemp = osal_strchr(pTemp, ' ');
    if (NULL == pTemp)
        return SYS_ERR_FAILED;
    PseConsumptionPower = atoi(++pTemp);

     /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_std_oid, OID_LENGTH(snmptrap_std_oid),
        ASN_OBJECT_ID,
        pse_power_usage_oid, sizeof(pse_power_usage_oid));

    snmp_varlist_add_variable(&var_list,
        pse_power_Cspt_oid, OID_LENGTH(pse_power_Cspt_oid),
        ASN_INTEGER,
        (void *)&PseConsumptionPower, sizeof(int));

    send_trap_vars(SNMP_TRAP_ENTERPRISESPECIFIC, 1, var_list);
    snmp_free_varbind(var_list );

    return SYS_ERR_OK;
}
/*操作日志的消息封装 第一个参数为要封装的消息 第二个参数时间，第三个为类型， 第四个为进程ID 第五个为内容*/
int32 snmpTrapOperatingMessageEncapsulation(snmp_trapFormat_t *pMsg, char* timestr, char* type, uint32 pid, char* detail)
{
	//snmp_trapFormat_t info;
	sys_line_session_t session;
	char typestr[50] ={0};
	va_list args;
	int i = 0;

	if(pMsg == NULL && timestr == NULL)
		return -1;
			
	osal_memset(pMsg, 0, sizeof(snmp_trapFormat_t));
	osal_memset(&session, 0, sizeof(sys_line_session_t));

	/*填充时间*/
	osal_sprintf(pMsg->trapTime, "%s", timestr);
	
	/*填充操作类型*/
	osal_sprintf(pMsg->trapType, "%s", type);

	/*选填用户操作信息*/
	sal_sys_lineSession_by_pid_get(pid, &session, typestr);
    if(osal_strcmp(typestr, "snmp") != 0)
    {	
		osal_sprintf(pMsg->trapUser,"%s user:%s %s", typestr, session.user, session.host);
    }
    else
    {
		osal_sprintf(pMsg->trapUser,"snmp");
    }
	/*详细内容填充*/
    osal_sprintf(pMsg->trapDetail, "%s", detail);

	//snmp_log(LOG_DEBUG, "%s %d type=%s user=%s detail=%s\n", __func__, __LINE__, pMsg->trapType ,pMsg->trapUser, pMsg->trapDetail);

    return  0;
}

int32 snmpTrapConfigChangeMessageEncapsulation(snmp_trapFormat_t *pMsg, char* timestr, char* detail, uint32 option)
{
	char typestr[50] ={0};
	va_list args;
	int i = 0;

	if((pMsg == NULL) || (timestr == NULL))
		return -1;
			
	osal_memset(pMsg, 0, sizeof(snmp_trapFormat_t));

	/*填充时间*/
	osal_sprintf(pMsg->trapTime, "%s", timestr);
	
	/*详细内容填充*/
    osal_sprintf(pMsg->trapDetail, "%s", detail);
    pMsg->status1 = option;

    return  0;
}


/*操作日志的消息封装 第一个参数为要封装的消息 第二个参数时间，第三个为端口号， 第四个为端口状态 第五个为系统IP*/
int32 snmpTrapPortLinkStatusMessageEncapsulation(snmp_trapFormat_t *pMsg, char* timestr, uint32 portId, uint32 status1, char* sysIp, uint32 status2)
{
	//snmp_trapFormat_t info;
	va_list args;
	int i = 0;

	if(pMsg == NULL && timestr == NULL)
		return -1;
			
	osal_memset(pMsg, 0, sizeof(snmp_trapFormat_t));

	/*填充时间*/
	osal_sprintf(pMsg->trapTime, "%s", timestr);
	
	/*填充端口号*/
	pMsg->portId = portId;

	/*填充状态*/
	pMsg->status1 = status1;//实际连接是否使能，1使能，2非使能
	pMsg->status2 = status2;//配置是否使能，1使能，2非使能
	
	/*填充系统IP*/
	osal_sprintf(pMsg->sysIp, "%s", sysIp);
    return  0;
}


int32 snmpTrapLoginStatusMessageEncapsulation(snmp_trapFormat_t *pMsg, char* timestr, char *userName, uint32 status1, uint32 status2, char* hostIp)
{
	//snmp_trapFormat_t info;
	va_list args;
	int i = 0;

	if((pMsg == NULL) || (timestr == NULL)||(userName == NULL)||(hostIp == NULL))
		return -1;
			
	osal_memset(pMsg, 0, sizeof(snmp_trapFormat_t));

	/*填充时间*/
	osal_sprintf(pMsg->trapTime, "%s", timestr);
	
	/*填充用户名*/
	osal_sprintf(pMsg->trapUser, "%s", userName);

	/*填充状态*/
	pMsg->status1 = status1;//登录类型，ssh、telnet、console
	pMsg->status2 = status2;//登录成功或失败或退出
	
	/*填充系统IP*/
	osal_sprintf(pMsg->sysIp, "%s", hostIp);
    return  0;
}

int32 snmpTrapUserOperationMessageEncapsulation(snmp_trapFormat_t *pMsg, char* timestr, char *userName, char* hostIp, char *daital)
{
	//snmp_trapFormat_t info;
	va_list args;
	int i = 0;

	if((pMsg == NULL) || (timestr == NULL)||(userName == NULL)||(hostIp == NULL)||(daital == NULL))
		return -1;
			
	osal_memset(pMsg, 0, sizeof(snmp_trapFormat_t));

	/*填充时间*/
	osal_sprintf(pMsg->trapTime, "%s", timestr);
	
	/*填充用户名*/
	osal_sprintf(pMsg->trapUser, "%s", userName);

	
	/*填充系统IP*/
	osal_sprintf(pMsg->sysIp, "%s", hostIp);

	osal_sprintf(pMsg->trapDetail, "%s", daital);
	
    return  0;
}


/*系统消息封装 第一个参数为要封装的消息 第二个参数时间，第三个为类型， 第四个为内容*/
uint32 snmpTrapMessageEncapsulation(snmp_trapFormat_t *pMsg, char* timestr, char* type, char* detail)
{
	sys_line_session_t session;
	char typestr[50] ={0};

	int i = 0;

	if(pMsg == NULL)
		return -1;
					
	osal_memset(pMsg, 0, sizeof(snmp_trapFormat_t));
	osal_memset(&session, 0, sizeof(sys_line_session_t));
	/*填充时间*/
	osal_sprintf(pMsg->trapTime, "%s", timestr);
	
	/*填充操作类型*/
	osal_sprintf(pMsg->trapType, "%s", type);

	/*详细内容填充*/
	osal_sprintf(pMsg->trapDetail, "%s", detail);


	//snmp_log(LOG_DEBUG, "%s %d type=%s user=%s detail=%s\n", __func__, __LINE__, pMsg->trapType ,pMsg->trapUser, pMsg->trapDetail);

    return  0;
}

int snmpTrapWrapOperateMessage(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;

    if (3!= ulArgsNum)
    {
        return SYS_ERR_FAILED;
    }
    
   	/*操作类消息封装*/ 
	snmpTrapConfigChangeMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf, *((uint32*)args[2].pBuf));

	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_OPERATE, &Info);

    return 0;
}

int snmpTrapWrapPortLinkStatus(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
    char buf[32];
    char *var = "link down";
	snmp_trapFormat_t Info;

    if ( 5 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }

    {
	   	/*操作类消息封装*/ 
		snmpTrapPortLinkStatusMessageEncapsulation(&Info, (char *)args[0].pBuf, *((uint32*)args[1].pBuf), *((uint32*)args[2].pBuf), (char*)args[3].pBuf,*((uint32*)args[4].pBuf));

		netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_LINK, &Info);
	}

    return 0;
}

int snmpTrapWrapLoginAAAStatus(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;
	//snmp_log(LOG_DEBUG, "%s %d args1=%s args2=%s args3=%s\n", __func__, __LINE__, (char*)args[0].pBuf ,(char*)args[1].pBuf, (char*)args[2].pBuf);

    if ( 5 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }
    
  
   	/*操作类消息封装*/ 
	snmpTrapLoginStatusMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf,  *((uint32*)args[2].pBuf), *((uint32*)args[3].pBuf), (char *)args[4].pBuf);
	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_LOGIN, &Info);
	
    return 0;
}

int snmpTrapWrapUserOperationStatus(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;
	//snmp_log(LOG_DEBUG, "%s %d args1=%s args2=%s args3=%s\n", __func__, __LINE__, (char*)args[0].pBuf ,(char*)args[1].pBuf, (char*)args[2].pBuf);

    if ( 4 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }
    
  
   	/*操作类消息封装*/ 
	snmpTrapUserOperationMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf,  (char *)args[2].pBuf, (char *)args[3].pBuf);

	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_USER_OPERATION, &Info);
	
    return 0;
}

int snmpTrapWrapUserOperationInfo(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;
	//snmp_log(LOG_DEBUG, "%s %d args1=%s args2=%s args3=%s\n", __func__, __LINE__, (char*)args[0].pBuf ,(char*)args[1].pBuf, (char*)args[2].pBuf);

    if ( 4 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }
    
  
   	/*操作类消息封装*/ 
	snmpTrapUserOperationMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf,  (char *)args[2].pBuf, (char *)args[3].pBuf);

	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_USER_OPERATION_INFO, &Info);
	
    return 0;
}



int snmpTrapWrapLoginPasswordChStatus(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;
	//snmp_log(LOG_DEBUG, "%s %d args1=%s args2=%s args3=%s\n", __func__, __LINE__, (char*)args[0].pBuf ,(char*)args[1].pBuf, (char*)args[2].pBuf);

    if ( 5 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }
    
  
   	/*操作类消息封装*/ 
	snmpTrapLoginStatusMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf,  *((uint32*)args[2].pBuf), *((uint32*)args[3].pBuf), (char *)args[4].pBuf);

	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_PASSWORD_CHANGE, &Info);
	
    return 0;
}

int snmpTrapWrapSystemStart(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;
	//snmp_log(LOG_DEBUG, "%s %d args1=%s args2=%s args3=%s\n", __func__, __LINE__, (char*)args[0].pBuf ,(char*)args[1].pBuf, (char*)args[2].pBuf);

    if ( 3 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }
   	/*操作类消息封装*/ 
	snmpTrapMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf,  (char*)args[2].pBuf);

	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_START, &Info);

    return 0;
}

int snmpTrapWrapSystemReboot(SMD_MSG *pMsg, SMD_ARG args[], ulong_t ulArgsNum)
{
	snmp_trapFormat_t Info;
	//snmp_log(LOG_DEBUG, "%s %d args1=%s args2=%s args3=%s\n", __func__, __LINE__, (char*)args[0].pBuf ,(char*)args[1].pBuf, (char*)args[2].pBuf);

    if ( 4 != ulArgsNum )
    {
        return SYS_ERR_FAILED;
    }
   	/*操作类消息封装*/ 
	snmpTrapOperatingMessageEncapsulation(&Info, (char *)args[0].pBuf, (char *)args[1].pBuf,   *((uint32*)args[2].pBuf), (char*)args[3].pBuf);

	netsnmp_cmTrap_send_mux_new(SNMP_CMTRAP_CODE_REBOOT, &Info);

    return 0;
}

/******************************************************************************
函数名称：snmpTrapAppWrapFunction
功能描述：注册库函数消息流解析函数
输入参数：无
输出参数：无
函数返回：VD_E_NONE, 成功
          SYS_ERR_FAILED，执行失败
          VD_E_PARAM，参数错误
其它说明：在进程接收消息之前调用
******************************************************************************/
int snmpTrapAppWrapFunction(void)
{
    int iRet = SYS_ERR_OK;

    memset(snmpTrapServerWrap, 0, (TRAP_FUNC_MAX * sizeof(SMD_WRAP_CMD)));
	if(snmpTrapServerWrap == NULL)
	{
		snmp_log(LOG_DEBUG, "\r %s %d pSmdWrap == NULL\n", __func__, __LINE__);
	}

	iRet += smdAppWrapRegister(TRAP_FUNC_START, 0, snmpTrapWrapSystemStart, snmpTrapServerWrap, TRAP_FUNC_MAX);
	iRet += smdAppWrapRegister(TRAP_FUNC_REBOOT, 0, snmpTrapWrapSystemReboot, snmpTrapServerWrap, TRAP_FUNC_MAX);
	iRet += smdAppWrapRegister(TRAP_FUNC_OPERATE, 0, snmpTrapWrapOperateMessage, snmpTrapServerWrap, TRAP_FUNC_MAX);
	iRet += smdAppWrapRegister(TRAP_FUNC_PORT_LINK, 0, snmpTrapWrapPortLinkStatus, snmpTrapServerWrap, TRAP_FUNC_MAX);
	iRet += smdAppWrapRegister(TRAP_FUNC_LOGIN_MESSAGES, 0, snmpTrapWrapLoginAAAStatus, snmpTrapServerWrap, TRAP_FUNC_MAX);
	iRet += smdAppWrapRegister(TRAP_FUNC_LOGIN_PASSWORD_CHANGE, 0, snmpTrapWrapLoginPasswordChStatus, snmpTrapServerWrap, TRAP_FUNC_MAX);
	iRet += smdAppWrapRegister(TRAP_FUNC_USER_OPERATION, 0, snmpTrapWrapUserOperationStatus, snmpTrapServerWrap, TRAP_FUNC_MAX);
    iRet += smdAppWrapRegister(TRAP_FUNC_USER_OPERATION_INFO, 0, snmpTrapWrapUserOperationInfo, snmpTrapServerWrap, TRAP_FUNC_MAX);


    if ( SYS_ERR_OK != iRet )
    {
        //smdDebugPrintf(SMD_DEBUG_WRAP_ERR, "%s:register failed", __func__);
    }

    return iRet;
}

int snmpTrapAppWrapProcess(SMD_MSG *pMsg)
{
	int iRet = SYS_ERR_OK;
	iRet = smdCfgAppWrapProcess(pMsg, snmpTrapServerWrap, TRAP_FUNC_MAX);
	if ( SYS_ERR_OK != iRet )
    {
        snmp_log( LOG_DEBUG, "%s:register failed", __func__);
    }
    return iRet;
}

/* Read data via smd socket. */
static int
trap_thread_read (struct thread *thread)
{
  int iRet = 0;
  int i;
  int nbytes;
  unsigned char buf[1024];
  SMD_MSG            *pSmdMsg;
  VOS_MSG_ADDR        clientAddr;

  int sock = THREAD_FD (thread);
  //snmp_log(LOG_DEBUG, "%s %d\n", __func__, __LINE__);

  //while(1)
  {
	  /* Read raw data from socket */
	  iRet = vosMsgRecv(sock, buf, 1024, VOS_TIMEOUT_NOWAIT, &clientAddr);
	  if (iRet < 0)
	  {
	  	  goto end;
	  }
	  else
	  {
		/*此处要做响应处理*/
		pSmdMsg = (SMD_MSG *)buf;
		switch ( pSmdMsg->usType )
	    {

	        case SMD_MSG_TYPE_TRAP:
	        	//snmp_log(LOG_DEBUG, "%s %d\n", __func__, __LINE__);
	            iRet = snmpTrapAppWrapProcess(pSmdMsg);
	            break;
	        
	        default:
	            snmp_log(LOG_DEBUG, "\r\n%s:vosMsgRecv receive unkown msg %d", __func__, pSmdMsg->usType);
	            goto end;
	    }

		iRet = vosMsgResp(sock, iRet, pSmdMsg, pSmdMsg->usArgsBufLen + sizeof(SMD_MSG), &clientAddr);
	  }
	}
end:
  thread_add_read (master, trap_thread_read, (void *)sock, sock);
  return 0;
}


