/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <net-snmp/agent/sysORTable.h>

#if HAVE_STDLIB_H
#include <stdlib.h>
#endif
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#if HAVE_STRING_H
#include <string.h>
#else
#include <strings.h>
#endif
#include <sys/types.h>

#include <ctype.h>
#if HAVE_UTSNAME_H
#include <utsname.h>
#else
#if HAVE_SYS_UTSNAME_H
#include <sys/utsname.h>
#endif
#endif
#if HAVE_NETINET_IN_H
#include <netinet/in.h>
#endif

#include "util_funcs.h"
#include "system_mib.h"
#include "struct.h"
#include "sysORTable.h"

#include <libsal/sal_sys.h>
#include <libsal/sal_util.h>
#include <libsal/sal_snmp.h>
#include <libfds/fds_export.h>

/*
 * system_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid system_variables_oid[] = { 1,3,6,1,2,1,1 };

#define SYSDESCR        1
#define SYSOBJECTID     2
#define SYSUPTIME       3
#define SYSCONTACT      4
#define SYSNAME     5
#define SYSLOCATION     6
#define SYSSERVICES     7
#define SYSORLASTCHANGE     8
#define SYSORINDEX      9
#define SYSORID     10
#define SYSORDESCR      11
#define SYSORUPTIME     12

#define SYS_STRING_LEN      256

char            version_descr[CAPA_SYS_DESC_LEN+1] = NETSNMP_VERS_DESC;
char            sysContact[CAPA_SYS_CONTACT_LEN+1] ;
char            sysName[CAPA_SYS_NAME_LEN+1] ;
char            sysLocation[CAPA_SYS_LOCATION_LEN+1];
oid             sysObjectID[MAX_OID_LEN];
size_t          sysObjectIDLength;


extern oid      version_sysoid[];
extern int      version_sysoid_len;

int             sysServices = 79; /*support layer 1,2,3,4,7*/
int             sysServicesConfiged = 0;


oid             system_module_oid[] = { SNMP_OID_SNMPMODULES, 1 };
int             system_module_oid_len =
    sizeof(system_module_oid) / sizeof(oid);
int             system_module_count = 0;

#ifdef USING_MIBII_SYSORTABLE_MODULE
extern u_long             sysORLastChange;
#endif
/*
 * variable4 system_variables:
 *   this variable defines function callbacks and type return information
 *   for the system mib section
 */

struct variable1 system_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */
{SYSDESCR,  ASN_OCTET_STR,  RONLY ,  var_system, 1,  { 1 }},

{SYSOBJECTID,  ASN_OBJECT_ID,  RONLY ,  var_system, 1,  { 2 }},

{SYSUPTIME,  ASN_TIMETICKS,  RONLY ,  var_system, 1,  { 3 }},

{SYSCONTACT,  ASN_OCTET_STR,  RWRITE,  var_system, 1,  { 4 }},

{SYSNAME,  ASN_OCTET_STR,  RWRITE,  var_system, 1,  { 5 }},

{SYSLOCATION,  ASN_OCTET_STR,  RWRITE,  var_system, 1,  { 6 }},

{SYSSERVICES,  ASN_INTEGER,  RONLY ,  var_system, 1,  { 7 }},

{SYSORLASTCHANGE,  ASN_TIMETICKS,  RONLY ,  var_system, 1,  { 8 }},

};
/*    (L = length of the oidsuffix) */


/** Initializes the system module */
void
init_system_mib(void)
{
    struct utsname  utsName;

    DEBUGMSGTL(("system", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("system", system_variables, variable1,
               system_variables_oid);

     if (++system_module_count == 3)
        REGISTER_SYSOR_ENTRY(system_module_oid,
                             "The MIB module for SNMPv2 entities");

    /* place any other initialization junk you need here */
}

/*
 * var_system():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_system(struct variable *vp,
                oid     *name,
                size_t  *length,
                int     exact,
                size_t  *var_len,
                WriteMethod **write_method)
{
    /* variables we may use later */
     static u_long   ulret;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /*
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case SYSDESCR:
    {
        char sysModel[CAPA_SYS_NAME_LEN];
        SYS_MEM_CLEAR(sysModel);
        sal_sys_bdinfoVar_get("modelname", sysModel);
        osal_strcpy(version_descr, sysModel);
        *var_len = osal_strlen(version_descr);
        return (u_char *) version_descr;
    }
    case SYSOBJECTID:
        fds_sys_objid_array_get((uint8 *)sysObjectID);
        sysObjectIDLength = SYS_OBJECT_ID_LEN;
        *var_len = sysObjectIDLength * sizeof(sysObjectID[0]);
        return (u_char *)sysObjectID;
    case SYSUPTIME:
        ulret = netsnmp_get_agent_uptime();
        return ((u_char *) & ulret);
    case SYSCONTACT:
        sal_sys_systemContact_get(sysContact);
        *var_len = osal_strlen(sysContact);
        *write_method = write_sysContact;
        return (u_char *) sysContact;
    case SYSNAME:
         sal_sys_systemName_get(sysName);
        *var_len = osal_strlen(sysName);
        *write_method = write_sysName;
        return (u_char *) sysName;
    case SYSLOCATION:
        sal_sys_systemLocation_get(sysLocation);
        *var_len = osal_strlen(sysLocation);
        *write_method = write_sysLocation;
        return (u_char *) sysLocation;
    case SYSSERVICES:
         ulret = sysServices;
        return (u_char *) & ulret;
    case SYSORLASTCHANGE:
       ulret = sysORLastChange;
        return ((u_char *) & ulret);

    default:
        DEBUGMSGTL(("snmpd", "unknown sub-id %d in var_system\n",
                    vp->magic));
    }
    return NULL;
}


int
write_sysContact(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;
    u_char  *cp;
    int count;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to system not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if ((var_val_len > CAPA_SYS_CONTACT_LEN) || (var_val_len < 1)) {
              fprintf(stderr,"write to system: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          osal_memset(sysContact,0,sizeof(sysContact));
          osal_memcpy(sysContact, var_val, var_val_len);
          SYS_SNMP_ERR_CHK(STRING_VALIDATE(sysContact, TRUE), SNMP_ERR_WRONGVALUE);
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;
           osal_memset(sysContact,0,sizeof(sysContact));
           osal_memcpy(sysContact, var_val, var_val_len);
           SYS_SNMP_ERR_CHK(sal_sys_systemContact_set(sysContact), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

#if 0
#ifdef CONFIG_SYS_UI_SNMP
    /* update snmp config file */
            sal_snmp_confFile_update();
#endif
#endif
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_sysName(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;
    u_char  *cp;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to system not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if ((var_val_len > CAPA_SYS_NAME_LEN) || (var_val_len < 1)){
              fprintf(stderr,"write to system: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          osal_memset(sysName,0,sizeof(sysName));
          osal_memcpy(sysName, var_val, var_val_len);
          SYS_SNMP_ERR_CHK(STRING_VALIDATE(sysName, TRUE), SNMP_ERR_WRONGVALUE);
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;
           osal_memset(sysName,0,sizeof(sysName));
           osal_memcpy(sysName, var_val, var_val_len);
           SYS_SNMP_ERR_CHK(sal_sys_systemName_set(sysName), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_sysLocation(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    char value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to system not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if ((var_val_len > CAPA_SYS_LOCATION_LEN) || (var_val_len < 1)) {
              fprintf(stderr,"write to system: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }

          osal_memset(sysLocation,0,sizeof(sysLocation));
          osal_memcpy(sysLocation, var_val, var_val_len);
          SYS_SNMP_ERR_CHK(STRING_VALIDATE(sysLocation, TRUE), SNMP_ERR_WRONGVALUE);
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (char *) var_val;
          osal_memset(sysLocation,0,sizeof(sysLocation));
          osal_memcpy(sysLocation, var_val, var_val_len);
          SYS_SNMP_ERR_CHK(sal_sys_systemLocation_set(sysLocation), SNMP_ERR_RESOURCEUNAVAILABLE);
          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */

          break;
    }

    return SNMP_ERR_NOERROR;
}

