#***********************************************************
#
# Copyright (C) 2010 Realtek Semiconductor Corp.
#
# Makefile -- Build instructions for switch global setting
#
#***********************************************************
#AUTHMGRDIR should defined in caller Makefile which is relative path of caller.
AUTHMGR_OBJ := \
	 $(AUTHMGRDIR)/proto_authmgr.o \
	 $(AUTHMGRDIR)/proto_authmgr_pktfmt.o \
	 $(AUTHMGRDIR)/proto_authmgr_action.o \
	 $(AUTHMGRDIR)/proto_dot1x.o \
	 $(AUTHMGRDIR)/proto_dot1x_eapol.o \
	 $(AUTHMGRDIR)/proto_dot1x_sm_backend.o \
	 $(AUTHMGRDIR)/proto_dot1x_sm_pae.o \
	 $(AUTHMGRDIR)/proto_dot1x_sm_reauth.o \
	 $(AUTHMGRDIR)/proto_dot1x_sm_timer.o \
	 $(AUTHMGRDIR)/proto_macauth.o \
	 $(AUTHMGRDIR)/proto_macauth_sm.o \
	 $(AUTHMGRDIR)/proto_webauth.o \
	 $(AUTHMGRDIR)/proto_webauth_sm.o \

