ifdef PSWITCH_DIR
SYS_ROOTDIR          := $(PSWITCH_DIR)
endif

	## Source Path Level-1 ##
SYS_APPDIR            = $(SYS_ROOTDIR)/app
SYS_CFGDIR            = $(SYS_ROOTDIR)/config
SYS_INSTDIR           = $(SYS_ROOTDIR)/install
SYS_LIBDIR            = $(SYS_ROOTDIR)/lib
SYS_PLATDIR           = $(SYS_ROOTDIR)/plat
SYS_PROTODIR          = $(SYS_ROOTDIR)/proto
SYS_SVNDIR            = $(SYS_ROOTDIR)/.svn
SYS_UTDIR             = $(SYS_ROOTDIR)/ut
SYS_VENDORDIR         = $(SYS_ROOTDIR)/vendor

	## Source Path Level-2 ##
SYS_APP_CLIDIR        = $(SYS_APPDIR)/cli
SYS_APP_CUSTOMDIR     = $(SYS_APPDIR)/custom
SYS_APP_HTTPDDIR      = $(SYS_APPDIR)/httpd
SYS_APP_INITDDIR      = $(SYS_APPDIR)/initd
SYS_APP_KSIDDIR       = $(SYS_APPDIR)/ksid
SYS_APP_LLDPDDIR      = $(SYS_APPDIR)/lldpd
SYS_APP_POLLDDIR      = $(SYS_APPDIR)/polld
SYS_APP_SNMPDIR       = $(SYS_APPDIR)/snmp
SYS_APP_WEBUIDIR      = $(SYS_APPDIR)/webui

SYS_LIB_CFGDIR        = $(SYS_LIBDIR)/libcfg
SYS_LIB_CUSDIR        = $(SYS_LIBDIR)/libcustom
SYS_LIB_FDSDIR        = $(SYS_LIBDIR)/libfds
SYS_LIB_GCCDIR        = $(SYS_LIBDIR)/libgcc
SYS_LIB_GLUEDIR       = $(SYS_LIBDIR)/libglue
SYS_LIB_SALDIR        = $(SYS_LIBDIR)/libsal
SYS_LIB_SSLDIR        = $(SYS_LIBDIR)/libssl
SYS_LIB_VTYDIR        = $(SYS_LIBDIR)/libvty
SYS_LIB_CLICMDDIR     = $(SYS_LIBDIR)/libclicmd
SYS_LIB_IPC           = $(SYS_LIBDIR)/libipc
SYS_LIB_UCI           = $(SYS_LIBDIR)/libuci

SYS_PROTO_L2GDIR      = $(SYS_PROTODIR)
SYS_PROTO_AUTHMGRDIR  = $(SYS_PROTODIR)/authmgr
SYS_PROTO_ACLDIR      = $(SYS_PROTODIR)/acl
SYS_PROTO_DAIDIR      = $(SYS_PROTODIR)/dai
SYS_PROTO_DHCPDIR     = $(SYS_PROTODIR)/dhcp
SYS_PROTO_GVRPDIR     = $(SYS_PROTODIR)/gvrp
SYS_PROTO_GARPDIR     = $(SYS_PROTODIR)/garp
SYS_PROTO_IGMPDIR     = $(SYS_PROTODIR)/igmp
SYS_PROTO_IPSGDIR     = $(SYS_PROTODIR)/isg
SYS_PROTO_LACPDIR     = $(SYS_PROTODIR)/lacp
SYS_PROTO_LLDPDIR     = $(SYS_PROTODIR)/lldp
SYS_PROTO_STPDIR      = $(SYS_PROTODIR)/stp
SYS_PROTO_UDLDDIR     = $(SYS_PROTODIR)/udld
SYS_PROTO_VOICEVLANDIR = $(SYS_PROTODIR)/voice_vlan
SYS_PROTO_MACVLANDIR  = $(SYS_PROTODIR)/macvlan
SYS_PROTO_SURVEILLANCEVLANDIR = $(SYS_PROTODIR)/surveillancevlan
SYS_PROTO_ERPSDIR      = $(SYS_PROTODIR)/erps
SYS_PROTO_LOOPBACKDIR  = $(SYS_PROTODIR)/loopback

SYS_PLAT_COMMONDIR    = $(SYS_PLATDIR)/common
SYS_PLAT_LXDIR        = $(SYS_PLATDIR)/linux
SYS_PLAT_RSDDIR       = $(SYS_PLATDIR)/rsd

	## Source Path Level-3 ##
SYS_PLAT_LX_BOARDDIR  = $(SYS_PLAT_LXDIR)/board
SYS_PLAT_LX_BOARDCONFDIR  = $(SYS_PLAT_LXDIR)/board_conf
SYS_PLAT_LX_DEFDBDIR  = $(SYS_PLAT_LXDIR)/defdb
SYS_PLAT_LX_KSIDIR    = $(SYS_PLAT_LXDIR)/ksi
SYS_PLAT_LX_NETDIR    = $(SYS_PLAT_LXDIR)/net
SYS_PLAT_LX_OSALDIR   = $(SYS_PLAT_LXDIR)/osal
SYS_PLAT_LX_SKIDIR    = $(SYS_PLAT_LXDIR)/ski
SYS_PLAT_LX_CUSDIR    = $(SYS_PLAT_LXDIR)/custom
SYS_APP_SNMPVENDORDIR = $(SYS_APP_SNMPDIR)/vendor

	## Source Path Level-4 ##
SYS_PLAT_LX_SKI_CHIPDIR    = $(SYS_PLAT_LX_SKIDIR)/chip
SYS_PLAT_LX_SKI_PROTODIR   = $(SYS_PLAT_LX_SKIDIR)/proto

	## Source Path Level-5 ##
SYS_PLAT_LX_SKI_PROTO_L2GDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)
SYS_PLAT_LX_SKI_PROTO_ACLDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)/acl
SYS_PLAT_LX_SKI_PROTO_AUTHMGRDIR = $(SYS_PLAT_LX_SKI_PROTODIR)/authmgr
SYS_PLAT_LX_SKI_PROTO_DAIDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)/dai
SYS_PLAT_LX_SKI_PROTO_DHCPDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/dhcp
SYS_PLAT_LX_SKI_PROTO_GVRPDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/gvrp
SYS_PLAT_LX_SKI_PROTO_GARPDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/garp
SYS_PLAT_LX_SKI_PROTO_IGMPDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/igmp
SYS_PLAT_LX_SKI_PROTO_ISGDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)/isg
SYS_PLAT_LX_SKI_PROTO_LACPDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/lacp
SYS_PLAT_LX_SKI_PROTO_LLDPDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/lldp
SYS_PLAT_LX_SKI_PROTO_STPDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)/stp
SYS_PLAT_LX_SKI_PROTO_UDLDDIR  = $(SYS_PLAT_LX_SKI_PROTODIR)/udld
SYS_PLAT_LX_SKI_PROTO_VOICEVLANDIR = $(SYS_PLAT_LX_SKI_PROTODIR)/voice_vlan
SYS_PLAT_LX_SKI_PROTO_MACVLANDIR = $(SYS_PLAT_LX_SKI_PROTODIR)/macvlan
SYS_PLAT_LX_SKI_PROTO_SURVEILLANCEVLANDIR = $(SYS_PLAT_LX_SKI_PROTODIR)/surveillancevlan
SYS_PLAT_LX_SKI_PROTO_ERPSDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)/erps
SYS_PLAT_LX_SKI_PROTO_LOOPBACKDIR   = $(SYS_PLAT_LX_SKI_PROTODIR)/loopback

	## Include Path Level-1 ##
SYS_APPINCLUDE        = $(SYS_APPDIR)
SYS_LIBINCLUDE        = $(SYS_LIBDIR)
SYS_PLATINCLUDE       = $(SYS_PLATDIR)
SYS_PROTOINCLUDE      = $(SYS_PROTODIR)

	## Include Path Level-2 ##
SYS_LXINCLUDE         = $(SYS_PLAT_LXDIR)

	## Include Path Level-3 ##
SYS_KSIINCLUDE        = $(SYS_PLAT_LX_KSIDIR)
SYS_GLUEINCLUDE       = $(SYS_LIB_GLUEDIR)
SYS_SSLINCLUDE        = $(SYS_LIB_SSLDIR)/include
SYS_BOARDINCLUDE      = $(SYS_PLAT_LX_BOARDDIR)
SYS_SKIINCLUDE        = $(SYS_PLAT_LX_SKIDIR)
SYS_IPCINCLUDE        = $(SYS_LIB_IPC)

	## Vendor Custom Path ##
SYS_VENDOR_ROOTDIR     = $(SYS_VENDORDIR)/$(CONFIG_VENDOR)/$(CONFIG_PRODUCT)
SYS_VENDOR_CLIDIR      = $(SYS_VENDOR_ROOTDIR)/cli
SYS_VENDOR_CUSTOMDIR   = $(SYS_VENDOR_ROOTDIR)/custom
SYS_VENDOR_CUSTOMAPPDIR= $(SYS_VENDOR_ROOTDIR)/custom/app
SYS_VENDOR_WEBUIDIR    = $(SYS_VENDOR_ROOTDIR)/webui
SYS_VENDOR_CLICMDDIR   = $(SYS_VENDOR_CLIDIR)/libclicmd
SYS_VENDOR_SNMPDIR     = $(SYS_VENDOR_ROOTDIR)/snmp
SYS_VENDOR_DEFDBDIR    = $(SYS_VENDOR_ROOTDIR)/custom/defdb
SYS_VENDOR_SDKDIR      = $(SYS_VENDOR_ROOTDIR)/sdk
SYS_VENDOR_BOARDDIR    = $(SYS_VENDOR_CUSTOMDIR)/board
SYS_VENDOR_LIBDIR      = $(SYS_VENDOR_CUSTOMDIR)/lib
SYS_VENDOR_MODDIR      = $(SYS_VENDOR_CUSTOMDIR)/module
SYS_VENDOR_WEBPANELDIR = $(SYS_VENDOR_CUSTOMDIR)/webui
SYS_VENDOR_WEBLOGODIR  = $(SYS_VENDOR_WEBPANELDIR)/logo
